//! **Generated data** (HFX, 2026-10-08) for the census task inference v4 (`census::listing::task_of`). Do not edit by hand:
//! regenerate with `tools/hf_census/inference_v4/` (its module docstrings name the pinned sources and the order to run them).
//!
//! * [`HF_AUTOMAP_TASKS_V1`]: transformers 5.17.0's auto-model tables (`MODEL_FOR_<KIND>_MAPPING_NAMES`), each table read as
//!   the pipeline task it serves ([`HF_AUTOMAP_TABLE_TASKS_V1`]); a class listed under exactly ONE task is that task, a class under
//!   two (`BartForConditionalGeneration`: fill-mask and text2text) is not listed. `MODEL_MAPPING_NAMES` (bare `AutoModel`), pre-training,
//!   backbones and the multimodal-LM table name no task and are not read.
//! * [`GGUF_CONVERTER_TASKS_V1`]: llama.cpp @030ebb55's converter (`conversion/*.py`, `@ModelBase.register(<HF classes>)` with
//!   `model_arch`): a GGUF `general.architecture` whose registered Hugging Face classes ALL name one task (by the head-class suffixes
//!   inference v2 reads, then the table above) is that task. An architecture registered for classes of two tasks is not listed, and
//!   neither is one the hand table of inference v2 already names (`task_of_gguf_architecture` decides those, unchanged).

/// The transformers version the class table was read from.
pub const HF_AUTOMAP_SOURCE_V1: &str = "transformers 5.17.0";
/// The llama.cpp commit the converter table was read from.
pub const GGUF_CONVERTER_SOURCE_V1: &str = "llama.cpp 030ebb558a5820b444a8f836ed5cdd46c9b4bd7a (conversion/*.py)";

/// The auto-model tables read, and the task each serves.
pub const HF_AUTOMAP_TABLE_TASKS_V1: &[(&str, &str)] = &[
    ("MODEL_FOR_AUDIO_CLASSIFICATION_MAPPING_NAMES", "audio-classification"),
    ("MODEL_FOR_CAUSAL_LM_MAPPING_NAMES", "text-generation"),
    ("MODEL_FOR_CTC_MAPPING_NAMES", "automatic-speech-recognition"),
    ("MODEL_FOR_DEPTH_ESTIMATION_MAPPING_NAMES", "depth-estimation"),
    ("MODEL_FOR_DOCUMENT_QUESTION_ANSWERING_MAPPING_NAMES", "document-question-answering"),
    ("MODEL_FOR_IMAGE_CLASSIFICATION_MAPPING_NAMES", "image-classification"),
    ("MODEL_FOR_IMAGE_SEGMENTATION_MAPPING_NAMES", "image-segmentation"),
    ("MODEL_FOR_IMAGE_TEXT_TO_TEXT_MAPPING_NAMES", "image-text-to-text"),
    ("MODEL_FOR_IMAGE_TO_IMAGE_MAPPING_NAMES", "image-to-image"),
    ("MODEL_FOR_INSTANCE_SEGMENTATION_MAPPING_NAMES", "image-segmentation"),
    ("MODEL_FOR_KEYPOINT_DETECTION_MAPPING_NAMES", "keypoint-detection"),
    ("MODEL_FOR_MASKED_LM_MAPPING_NAMES", "fill-mask"),
    ("MODEL_FOR_MASK_GENERATION_MAPPING_NAMES", "mask-generation"),
    ("MODEL_FOR_MULTIPLE_CHOICE_MAPPING_NAMES", "multiple-choice"),
    ("MODEL_FOR_OBJECT_DETECTION_MAPPING_NAMES", "object-detection"),
    ("MODEL_FOR_QUESTION_ANSWERING_MAPPING_NAMES", "question-answering"),
    ("MODEL_FOR_SEMANTIC_SEGMENTATION_MAPPING_NAMES", "image-segmentation"),
    ("MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING_NAMES", "text-classification"),
    ("MODEL_FOR_SEQ_TO_SEQ_CAUSAL_LM_MAPPING_NAMES", "text2text-generation"),
    ("MODEL_FOR_SPEECH_SEQ_2_SEQ_MAPPING_NAMES", "automatic-speech-recognition"),
    ("MODEL_FOR_TABLE_QUESTION_ANSWERING_MAPPING_NAMES", "table-question-answering"),
    ("MODEL_FOR_TEXT_TO_SPECTROGRAM_MAPPING_NAMES", "text-to-speech"),
    ("MODEL_FOR_TEXT_TO_WAVEFORM_MAPPING_NAMES", "text-to-speech"),
    ("MODEL_FOR_TIME_SERIES_PREDICTION_MAPPING_NAMES", "time-series-forecasting"),
    ("MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING_NAMES", "token-classification"),
    ("MODEL_FOR_UNIVERSAL_SEGMENTATION_MAPPING_NAMES", "image-segmentation"),
    ("MODEL_FOR_VIDEO_CLASSIFICATION_MAPPING_NAMES", "video-classification"),
    ("MODEL_FOR_VISUAL_QUESTION_ANSWERING_MAPPING_NAMES", "visual-question-answering"),
    ("MODEL_FOR_ZERO_SHOT_IMAGE_CLASSIFICATION_MAPPING_NAMES", "zero-shot-image-classification"),
    ("MODEL_FOR_ZERO_SHOT_OBJECT_DETECTION_MAPPING_NAMES", "zero-shot-object-detection"),
];

/// (class, task), sorted by class: transformers' own classes listed under exactly one task.
pub const HF_AUTOMAP_TASKS_V1: &[(&str, &str)] = &[
    ("ASTForAudioClassification", "audio-classification"),
    ("AXK1ForCausalLM", "text-generation"),
    ("AXK1ForSequenceClassification", "text-classification"),
    ("AXK1ForTokenClassification", "token-classification"),
    ("AXK2ForCausalLM", "text-generation"),
    ("AXK2ForSequenceClassification", "text-classification"),
    ("AXK2ForTokenClassification", "token-classification"),
    ("AfmoeForCausalLM", "text-generation"),
    ("AlbertForMaskedLM", "fill-mask"),
    ("AlbertForMultipleChoice", "multiple-choice"),
    ("AlbertForQuestionAnswering", "question-answering"),
    ("AlbertForSequenceClassification", "text-classification"),
    ("AlbertForTokenClassification", "token-classification"),
    ("AlignModel", "zero-shot-image-classification"),
    ("AltCLIPModel", "zero-shot-image-classification"),
    ("ApertusForCausalLM", "text-generation"),
    ("ApertusForTokenClassification", "token-classification"),
    ("ArceeForCausalLM", "text-generation"),
    ("ArceeForQuestionAnswering", "question-answering"),
    ("ArceeForSequenceClassification", "text-classification"),
    ("ArceeForTokenClassification", "token-classification"),
    ("AriaForConditionalGeneration", "image-text-to-text"),
    ("AriaTextForCausalLM", "text-generation"),
    ("AudioFlamingo3ForConditionalGeneration", "text2text-generation"),
    ("AyaVisionForConditionalGeneration", "image-text-to-text"),
    ("BambaForCausalLM", "text-generation"),
    ("BarkModel", "text-to-speech"),
    ("BartForCausalLM", "text-generation"),
    ("BartForQuestionAnswering", "question-answering"),
    ("BartForSequenceClassification", "text-classification"),
    ("BeitForImageClassification", "image-classification"),
    ("BeitForSemanticSegmentation", "image-segmentation"),
    ("BertForMaskedLM", "fill-mask"),
    ("BertForMultipleChoice", "multiple-choice"),
    ("BertForQuestionAnswering", "question-answering"),
    ("BertForSequenceClassification", "text-classification"),
    ("BertForTokenClassification", "token-classification"),
    ("BertGenerationDecoder", "text-generation"),
    ("BertLMHeadModel", "text-generation"),
    ("BigBirdForCausalLM", "text-generation"),
    ("BigBirdForMaskedLM", "fill-mask"),
    ("BigBirdForMultipleChoice", "multiple-choice"),
    ("BigBirdForQuestionAnswering", "question-answering"),
    ("BigBirdForSequenceClassification", "text-classification"),
    ("BigBirdForTokenClassification", "token-classification"),
    ("BigBirdPegasusForCausalLM", "text-generation"),
    ("BigBirdPegasusForConditionalGeneration", "text2text-generation"),
    ("BigBirdPegasusForQuestionAnswering", "question-answering"),
    ("BigBirdPegasusForSequenceClassification", "text-classification"),
    ("BioGptForCausalLM", "text-generation"),
    ("BioGptForSequenceClassification", "text-classification"),
    ("BioGptForTokenClassification", "token-classification"),
    ("BitForImageClassification", "image-classification"),
    ("BitNetForCausalLM", "text-generation"),
    ("BlenderbotForCausalLM", "text-generation"),
    ("BlenderbotForConditionalGeneration", "text2text-generation"),
    ("BlenderbotSmallForCausalLM", "text-generation"),
    ("BlenderbotSmallForConditionalGeneration", "text2text-generation"),
    ("Blip2ForImageTextRetrieval", "zero-shot-image-classification"),
    ("BlipForConditionalGeneration", "image-text-to-text"),
    ("BlipForQuestionAnswering", "visual-question-answering"),
    ("BlipModel", "zero-shot-image-classification"),
    ("BloomForCausalLM", "text-generation"),
    ("BloomForQuestionAnswering", "question-answering"),
    ("BloomForSequenceClassification", "text-classification"),
    ("BloomForTokenClassification", "token-classification"),
    ("BltForCausalLM", "text-generation"),
    ("BrosForTokenClassification", "token-classification"),
    ("CHMv2ForDepthEstimation", "depth-estimation"),
    ("CLIPForImageClassification", "image-classification"),
    ("CLIPModel", "zero-shot-image-classification"),
    ("CLIPSegModel", "zero-shot-image-classification"),
    ("CTRLForSequenceClassification", "text-classification"),
    ("CTRLLMHeadModel", "text-generation"),
    ("CamembertForCausalLM", "text-generation"),
    ("CamembertForMaskedLM", "fill-mask"),
    ("CamembertForMultipleChoice", "multiple-choice"),
    ("CamembertForQuestionAnswering", "question-answering"),
    ("CamembertForSequenceClassification", "text-classification"),
    ("CamembertForTokenClassification", "token-classification"),
    ("CanaryForConditionalGeneration", "automatic-speech-recognition"),
    ("CanineForMultipleChoice", "multiple-choice"),
    ("CanineForQuestionAnswering", "question-answering"),
    ("CanineForSequenceClassification", "text-classification"),
    ("CanineForTokenClassification", "token-classification"),
    ("ChameleonForConditionalGeneration", "image-text-to-text"),
    ("ChineseCLIPModel", "zero-shot-image-classification"),
    ("CodeGenForCausalLM", "text-generation"),
    ("Cohere2ForCausalLM", "text-generation"),
    ("Cohere2MoeForCausalLM", "text-generation"),
    ("Cohere2VisionForConditionalGeneration", "image-text-to-text"),
    ("CohereAsrForConditionalGeneration", "automatic-speech-recognition"),
    ("CohereCompassForCausalLM", "text-generation"),
    ("CohereCompassForConditionalGeneration", "image-text-to-text"),
    ("CohereCompassTextForSequenceClassification", "text-classification"),
    ("CohereForCausalLM", "text-generation"),
    ("ConditionalDetrForObjectDetection", "object-detection"),
    ("ConvBertForMaskedLM", "fill-mask"),
    ("ConvBertForMultipleChoice", "multiple-choice"),
    ("ConvBertForQuestionAnswering", "question-answering"),
    ("ConvBertForSequenceClassification", "text-classification"),
    ("ConvBertForTokenClassification", "token-classification"),
    ("ConvNextForImageClassification", "image-classification"),
    ("ConvNextV2ForImageClassification", "image-classification"),
    ("Cosmos3EdgeForConditionalGeneration", "image-text-to-text"),
    ("Cosmos3OmniForConditionalGeneration", "image-text-to-text"),
    ("CpmAntForCausalLM", "text-generation"),
    ("CsmForConditionalGeneration", "text-to-speech"),
    ("CvtForImageClassification", "image-classification"),
    ("CwmForCausalLM", "text-generation"),
    ("DFineForObjectDetection", "object-detection"),
    ("DPTForDepthEstimation", "depth-estimation"),
    ("DPTForSemanticSegmentation", "image-segmentation"),
    ("DabDetrForObjectDetection", "object-detection"),
    ("Data2VecAudioForCTC", "automatic-speech-recognition"),
    ("Data2VecAudioForSequenceClassification", "audio-classification"),
    ("Data2VecTextForCausalLM", "text-generation"),
    ("Data2VecTextForMaskedLM", "fill-mask"),
    ("Data2VecTextForMultipleChoice", "multiple-choice"),
    ("Data2VecTextForQuestionAnswering", "question-answering"),
    ("Data2VecTextForSequenceClassification", "text-classification"),
    ("Data2VecTextForTokenClassification", "token-classification"),
    ("Data2VecVisionForImageClassification", "image-classification"),
    ("Data2VecVisionForSemanticSegmentation", "image-segmentation"),
    ("DbrxForCausalLM", "text-generation"),
    ("DebertaForMaskedLM", "fill-mask"),
    ("DebertaForQuestionAnswering", "question-answering"),
    ("DebertaForSequenceClassification", "text-classification"),
    ("DebertaForTokenClassification", "token-classification"),
    ("DebertaV2ForMaskedLM", "fill-mask"),
    ("DebertaV2ForMultipleChoice", "multiple-choice"),
    ("DebertaV2ForQuestionAnswering", "question-answering"),
    ("DebertaV2ForSequenceClassification", "text-classification"),
    ("DebertaV2ForTokenClassification", "token-classification"),
    ("DeepseekOcr2ForConditionalGeneration", "image-text-to-text"),
    ("DeepseekV2ForCausalLM", "text-generation"),
    ("DeepseekV2ForSequenceClassification", "text-classification"),
    ("DeepseekV32ForCausalLM", "text-generation"),
    ("DeepseekV3ForCausalLM", "text-generation"),
    ("DeepseekV3ForSequenceClassification", "text-classification"),
    ("DeepseekV3ForTokenClassification", "token-classification"),
    ("DeepseekV4ForCausalLM", "text-generation"),
    ("DeepseekVLForConditionalGeneration", "image-text-to-text"),
    ("DeepseekVLHybridForConditionalGeneration", "image-text-to-text"),
    ("DeformableDetrForObjectDetection", "object-detection"),
    ("DeiTForImageClassification", "image-classification"),
    ("DeiTForImageClassificationWithTeacher", "image-classification"),
    ("Deimv2ForObjectDetection", "object-detection"),
    ("DepthAnythingForDepthEstimation", "depth-estimation"),
    ("DepthProForDepthEstimation", "depth-estimation"),
    ("DetrForObjectDetection", "object-detection"),
    ("DetrForSegmentation", "image-segmentation"),
    ("DiaForConditionalGeneration", "automatic-speech-recognition"),
    ("DiffLlamaForCausalLM", "text-generation"),
    ("DiffLlamaForQuestionAnswering", "question-answering"),
    ("DiffLlamaForSequenceClassification", "text-classification"),
    ("DiffLlamaForTokenClassification", "token-classification"),
    ("DiffusionGemmaForBlockDiffusion", "image-text-to-text"),
    ("DinatForImageClassification", "image-classification"),
    ("Dinov2ForImageClassification", "image-classification"),
    ("Dinov2WithRegistersForImageClassification", "image-classification"),
    ("DistilBertForMaskedLM", "fill-mask"),
    ("DistilBertForMultipleChoice", "multiple-choice"),
    ("DistilBertForQuestionAnswering", "question-answering"),
    ("DistilBertForSequenceClassification", "text-classification"),
    ("DistilBertForTokenClassification", "token-classification"),
    ("DogeForCausalLM", "text-generation"),
    ("DogeForSequenceClassification", "text-classification"),
    ("DonutSwinForImageClassification", "image-classification"),
    ("Dots1ForCausalLM", "text-generation"),
    ("EdgeTamModel", "mask-generation"),
    ("EfficientNetForImageClassification", "image-classification"),
    ("ElectraForCausalLM", "text-generation"),
    ("ElectraForMaskedLM", "fill-mask"),
    ("ElectraForMultipleChoice", "multiple-choice"),
    ("ElectraForQuestionAnswering", "question-answering"),
    ("ElectraForSequenceClassification", "text-classification"),
    ("ElectraForTokenClassification", "token-classification"),
    ("Emu3ForCausalLM", "text-generation"),
    ("Emu3ForConditionalGeneration", "image-text-to-text"),
    ("EncoderDecoderModel", "text2text-generation"),
    ("EomtDinov3ForUniversalSegmentation", "image-segmentation"),
    ("EomtForUniversalSegmentation", "image-segmentation"),
    ("Ernie4_5ForCausalLM", "text-generation"),
    ("Ernie4_5_MoeForCausalLM", "text-generation"),
    ("Ernie4_5_VLMoeForConditionalGeneration", "image-text-to-text"),
    ("ErnieForCausalLM", "text-generation"),
    ("ErnieForMaskedLM", "fill-mask"),
    ("ErnieForMultipleChoice", "multiple-choice"),
    ("ErnieForQuestionAnswering", "question-answering"),
    ("ErnieForSequenceClassification", "text-classification"),
    ("ErnieForTokenClassification", "token-classification"),
    ("EsmForMaskedLM", "fill-mask"),
    ("EsmForSequenceClassification", "text-classification"),
    ("EsmForTokenClassification", "token-classification"),
    ("EsmcForMaskedLM", "fill-mask"),
    ("EsmcForSequenceClassification", "text-classification"),
    ("EsmcForTokenClassification", "token-classification"),
    ("EuroBertForMaskedLM", "fill-mask"),
    ("EuroBertForSequenceClassification", "text-classification"),
    ("EuroBertForTokenClassification", "token-classification"),
    ("EvollaForProteinText2Text", "image-text-to-text"),
    ("Exaone4ForCausalLM", "text-generation"),
    ("Exaone4ForQuestionAnswering", "question-answering"),
    ("Exaone4ForSequenceClassification", "text-classification"),
    ("Exaone4ForTokenClassification", "token-classification"),
    ("Exaone4_5_ForConditionalGeneration", "image-text-to-text"),
    ("ExaoneMoeForCausalLM", "text-generation"),
    ("FNetForMaskedLM", "fill-mask"),
    ("FNetForMultipleChoice", "multiple-choice"),
    ("FNetForQuestionAnswering", "question-answering"),
    ("FNetForSequenceClassification", "text-classification"),
    ("FNetForTokenClassification", "token-classification"),
    ("FSMTForConditionalGeneration", "text2text-generation"),
    ("FalconForCausalLM", "text-generation"),
    ("FalconForQuestionAnswering", "question-answering"),
    ("FalconForSequenceClassification", "text-classification"),
    ("FalconForTokenClassification", "token-classification"),
    ("FalconH1ForCausalLM", "text-generation"),
    ("FalconMambaForCausalLM", "text-generation"),
    ("FastSpeech2ConformerModel", "text-to-speech"),
    ("FastSpeech2ConformerWithHifiGan", "text-to-speech"),
    ("FastVlmForConditionalGeneration", "image-text-to-text"),
    ("FlaubertForMultipleChoice", "multiple-choice"),
    ("FlaubertForQuestionAnsweringSimple", "question-answering"),
    ("FlaubertForSequenceClassification", "text-classification"),
    ("FlaubertForTokenClassification", "token-classification"),
    ("FlaubertWithLMHeadModel", "fill-mask"),
    ("FlexOlmoForCausalLM", "text-generation"),
    ("Florence2ForConditionalGeneration", "image-text-to-text"),
    ("FocalNetForImageClassification", "image-classification"),
    ("FunAsrNanoForConditionalGeneration", "automatic-speech-recognition"),
    ("FunnelForMaskedLM", "fill-mask"),
    ("FunnelForMultipleChoice", "multiple-choice"),
    ("FunnelForQuestionAnswering", "question-answering"),
    ("FunnelForSequenceClassification", "text-classification"),
    ("FunnelForTokenClassification", "token-classification"),
    ("GLPNForDepthEstimation", "depth-estimation"),
    ("GPT2ForQuestionAnswering", "question-answering"),
    ("GPT2ForSequenceClassification", "text-classification"),
    ("GPT2ForTokenClassification", "token-classification"),
    ("GPT2LMHeadModel", "text-generation"),
    ("GPTBigCodeForCausalLM", "text-generation"),
    ("GPTBigCodeForSequenceClassification", "text-classification"),
    ("GPTBigCodeForTokenClassification", "token-classification"),
    ("GPTJForCausalLM", "text-generation"),
    ("GPTJForQuestionAnswering", "question-answering"),
    ("GPTJForSequenceClassification", "text-classification"),
    ("GPTNeoForCausalLM", "text-generation"),
    ("GPTNeoForQuestionAnswering", "question-answering"),
    ("GPTNeoForSequenceClassification", "text-classification"),
    ("GPTNeoForTokenClassification", "token-classification"),
    ("GPTNeoXForCausalLM", "text-generation"),
    ("GPTNeoXForQuestionAnswering", "question-answering"),
    ("GPTNeoXForSequenceClassification", "text-classification"),
    ("GPTNeoXForTokenClassification", "token-classification"),
    ("GPTNeoXJapaneseForCausalLM", "text-generation"),
    ("Gemma2ForCausalLM", "text-generation"),
    ("Gemma2ForSequenceClassification", "text-classification"),
    ("Gemma2ForTokenClassification", "token-classification"),
    ("Gemma3ForCausalLM", "text-generation"),
    ("Gemma3ForSequenceClassification", "text-classification"),
    ("Gemma3TextForSequenceClassification", "text-classification"),
    ("Gemma3nForCausalLM", "text-generation"),
    ("Gemma4AssistantForCausalLM", "text-generation"),
    ("Gemma4ForCausalLM", "text-generation"),
    ("Gemma4UnifiedAssistantForCausalLM", "text-generation"),
    ("Gemma4UnifiedForCausalLM", "text-generation"),
    ("GemmaForCausalLM", "text-generation"),
    ("GemmaForSequenceClassification", "text-classification"),
    ("GemmaForTokenClassification", "token-classification"),
    ("Glm46VForConditionalGeneration", "image-text-to-text"),
    ("Glm4ForCausalLM", "text-generation"),
    ("Glm4ForSequenceClassification", "text-classification"),
    ("Glm4ForTokenClassification", "token-classification"),
    ("Glm4MoeForCausalLM", "text-generation"),
    ("Glm4MoeLiteForCausalLM", "text-generation"),
    ("Glm4vForConditionalGeneration", "image-text-to-text"),
    ("Glm4vMoeForConditionalGeneration", "image-text-to-text"),
    ("Glm5NextForConditionalGeneration", "image-text-to-text"),
    ("GlmAsrForConditionalGeneration", "text2text-generation"),
    ("GlmForCausalLM", "text-generation"),
    ("GlmForSequenceClassification", "text-classification"),
    ("GlmForTokenClassification", "token-classification"),
    ("GlmMoeDsaForCausalLM", "text-generation"),
    ("GlmOcrForConditionalGeneration", "image-text-to-text"),
    ("GptOssForCausalLM", "text-generation"),
    ("GptOssForSequenceClassification", "text-classification"),
    ("GptOssForTokenClassification", "token-classification"),
    ("Granite4VisionForConditionalGeneration", "image-text-to-text"),
    ("GraniteForCausalLM", "text-generation"),
    ("GraniteMoeForCausalLM", "text-generation"),
    ("GraniteMoeHybridForCausalLM", "text-generation"),
    ("GraniteMoeSWAForCausalLM", "text-generation"),
    ("GraniteMoeSharedForCausalLM", "text-generation"),
    ("GraniteSWAForCausalLM", "text-generation"),
    ("GraniteSpeech5ForCTC", "automatic-speech-recognition"),
    ("GroundingDinoForObjectDetection", "zero-shot-object-detection"),
    ("HGNetV2ForImageClassification", "image-classification"),
    ("HYV3ForCausalLM", "text-generation"),
    ("HYV4ForCausalLM", "text-generation"),
    ("HeliumForCausalLM", "text-generation"),
    ("HeliumForSequenceClassification", "text-classification"),
    ("HeliumForTokenClassification", "token-classification"),
    ("HieraForImageClassification", "image-classification"),
    ("HiggsAudioV2ForConditionalGeneration", "text-to-speech"),
    ("HrmTextForCausalLM", "text-generation"),
    ("HubertForCTC", "automatic-speech-recognition"),
    ("HubertForSequenceClassification", "audio-classification"),
    ("HunYuanDenseV1ForCausalLM", "text-generation"),
    ("HunYuanDenseV1ForSequenceClassification", "text-classification"),
    ("HunYuanMoEV1ForCausalLM", "text-generation"),
    ("HunYuanMoEV1ForSequenceClassification", "text-classification"),
    ("HunYuanVLForConditionalGeneration", "image-text-to-text"),
    ("HyperCLOVAXForCausalLM", "text-generation"),
    ("IBertForMaskedLM", "fill-mask"),
    ("IBertForMultipleChoice", "multiple-choice"),
    ("IBertForQuestionAnswering", "question-answering"),
    ("IBertForSequenceClassification", "text-classification"),
    ("IBertForTokenClassification", "token-classification"),
    ("IJepaForImageClassification", "image-classification"),
    ("Idefics2ForConditionalGeneration", "image-text-to-text"),
    ("Idefics3ForConditionalGeneration", "image-text-to-text"),
    ("IdeficsForVisionText2Text", "image-text-to-text"),
    ("ImageGPTForImageClassification", "image-classification"),
    ("InklingForCausalLM", "text-generation"),
    ("InklingForConditionalGeneration", "image-text-to-text"),
    ("InstructBlipForConditionalGeneration", "image-text-to-text"),
    ("InstructBlipVideoForConditionalGeneration", "image-text-to-text"),
    ("InternVLForConditionalGeneration", "image-text-to-text"),
    ("Jais2ForCausalLM", "text-generation"),
    ("JambaForCausalLM", "text-generation"),
    ("JambaForSequenceClassification", "text-classification"),
    ("JanusForConditionalGeneration", "image-text-to-text"),
    ("JetMoeForCausalLM", "text-generation"),
    ("JetMoeForSequenceClassification", "text-classification"),
    ("JinaEmbeddingsV3ForMaskedLM", "fill-mask"),
    ("JinaEmbeddingsV3ForQuestionAnswering", "question-answering"),
    ("JinaEmbeddingsV3ForSequenceClassification", "text-classification"),
    ("JinaEmbeddingsV3ForTokenClassification", "token-classification"),
    ("KimiLinearForCausalLM", "text-generation"),
    ("Kimi_K25ForConditionalGeneration", "image-text-to-text"),
    ("Kosmos2ForConditionalGeneration", "image-text-to-text"),
    ("Kosmos2_5ForConditionalGeneration", "image-text-to-text"),
    ("KyutaiSpeechToTextForConditionalGeneration", "automatic-speech-recognition"),
    ("LEDForConditionalGeneration", "text2text-generation"),
    ("LEDForQuestionAnswering", "question-answering"),
    ("LagunaForCausalLM", "text-generation"),
    ("LasrForCTC", "automatic-speech-recognition"),
    ("LayoutLMForMaskedLM", "fill-mask"),
    ("LayoutLMForQuestionAnswering", "document-question-answering"),
    ("LayoutLMForSequenceClassification", "text-classification"),
    ("LayoutLMForTokenClassification", "token-classification"),
    ("LayoutLMv2ForSequenceClassification", "text-classification"),
    ("LayoutLMv2ForTokenClassification", "token-classification"),
    ("LayoutLMv3ForSequenceClassification", "text-classification"),
    ("LayoutLMv3ForTokenClassification", "token-classification"),
    ("LevitForImageClassification", "image-classification"),
    ("LevitForImageClassificationWithTeacher", "image-classification"),
    ("Lfm2ForCausalLM", "text-generation"),
    ("Lfm2MoeForCausalLM", "text-generation"),
    ("Lfm2VlForConditionalGeneration", "image-text-to-text"),
    ("LightOnOcrForConditionalGeneration", "image-text-to-text"),
    ("LiltForQuestionAnswering", "question-answering"),
    ("LiltForSequenceClassification", "text-classification"),
    ("LiltForTokenClassification", "token-classification"),
    ("Llama4ForCausalLM", "text-generation"),
    ("Llama4ForConditionalGeneration", "image-text-to-text"),
    ("LlamaForCausalLM", "text-generation"),
    ("LlamaForQuestionAnswering", "question-answering"),
    ("LlamaForSequenceClassification", "text-classification"),
    ("LlamaForTokenClassification", "token-classification"),
    ("LlavaForConditionalGeneration", "image-text-to-text"),
    ("LlavaNextForConditionalGeneration", "image-text-to-text"),
    ("LlavaNextVideoForConditionalGeneration", "image-text-to-text"),
    ("LlavaOnevisionForConditionalGeneration", "image-text-to-text"),
    ("LongT5ForConditionalGeneration", "text2text-generation"),
    ("LongcatFlashForCausalLM", "text-generation"),
    ("LongformerForMaskedLM", "fill-mask"),
    ("LongformerForMultipleChoice", "multiple-choice"),
    ("LongformerForQuestionAnswering", "question-answering"),
    ("LongformerForSequenceClassification", "text-classification"),
    ("LongformerForTokenClassification", "token-classification"),
    ("LukeForMaskedLM", "fill-mask"),
    ("LukeForMultipleChoice", "multiple-choice"),
    ("LukeForQuestionAnswering", "question-answering"),
    ("LukeForSequenceClassification", "text-classification"),
    ("LukeForTokenClassification", "token-classification"),
    ("LwDetrForObjectDetection", "object-detection"),
    ("LxmertForQuestionAnswering", "question-answering"),
    ("M2M100ForConditionalGeneration", "text2text-generation"),
    ("MBartForCausalLM", "text-generation"),
    ("MBartForQuestionAnswering", "question-answering"),
    ("MBartForSequenceClassification", "text-classification"),
    ("MMGroundingDinoForObjectDetection", "zero-shot-object-detection"),
    ("MPNetForMaskedLM", "fill-mask"),
    ("MPNetForMultipleChoice", "multiple-choice"),
    ("MPNetForQuestionAnswering", "question-answering"),
    ("MPNetForSequenceClassification", "text-classification"),
    ("MPNetForTokenClassification", "token-classification"),
    ("MT5ForConditionalGeneration", "text2text-generation"),
    ("MT5ForQuestionAnswering", "question-answering"),
    ("MT5ForSequenceClassification", "text-classification"),
    ("MT5ForTokenClassification", "token-classification"),
    ("Mamba2ForCausalLM", "text-generation"),
    ("MambaForCausalLM", "text-generation"),
    ("MarianForCausalLM", "text-generation"),
    ("MarianMTModel", "text2text-generation"),
    ("MarkupLMForQuestionAnswering", "question-answering"),
    ("MarkupLMForSequenceClassification", "text-classification"),
    ("MarkupLMForTokenClassification", "token-classification"),
    ("Mask2FormerForUniversalSegmentation", "image-segmentation"),
    ("MaskFormerForInstanceSegmentation", "image-segmentation"),
    ("MegatronBertForCausalLM", "text-generation"),
    ("MegatronBertForMaskedLM", "fill-mask"),
    ("MegatronBertForMultipleChoice", "multiple-choice"),
    ("MegatronBertForQuestionAnswering", "question-answering"),
    ("MegatronBertForSequenceClassification", "text-classification"),
    ("MegatronBertForTokenClassification", "token-classification"),
    ("MellumForCausalLM", "text-generation"),
    ("MetaClip2ForImageClassification", "image-classification"),
    ("MetaClip2Model", "zero-shot-image-classification"),
    ("MiMoV2FlashForCausalLM", "text-generation"),
    ("MiniCPM3ForCausalLM", "text-generation"),
    ("MiniCPM3ForSequenceClassification", "text-classification"),
    ("MiniCPMV4_6ForConditionalGeneration", "image-text-to-text"),
    ("MiniMaxForCausalLM", "text-generation"),
    ("MiniMaxForQuestionAnswering", "question-answering"),
    ("MiniMaxForSequenceClassification", "text-classification"),
    ("MiniMaxForTokenClassification", "token-classification"),
    ("MiniMaxM2ForCausalLM", "text-generation"),
    ("MiniMaxM3SparseForConditionalGeneration", "image-text-to-text"),
    ("MiniMaxM3VLForCausalLM", "text-generation"),
    ("Ministral3ForCausalLM", "text-generation"),
    ("Ministral3ForQuestionAnswering", "question-answering"),
    ("Ministral3ForSequenceClassification", "text-classification"),
    ("Ministral3ForTokenClassification", "token-classification"),
    ("MinistralForCausalLM", "text-generation"),
    ("MinistralForQuestionAnswering", "question-answering"),
    ("MinistralForSequenceClassification", "text-classification"),
    ("MinistralForTokenClassification", "token-classification"),
    ("Mistral3ForConditionalGeneration", "image-text-to-text"),
    ("Mistral4ForCausalLM", "image-text-to-text"),
    ("Mistral4ForSequenceClassification", "text-classification"),
    ("Mistral4ForTokenClassification", "token-classification"),
    ("MistralForCausalLM", "text-generation"),
    ("MistralForQuestionAnswering", "question-answering"),
    ("MistralForSequenceClassification", "text-classification"),
    ("MistralForTokenClassification", "token-classification"),
    ("MixtralForCausalLM", "text-generation"),
    ("MixtralForQuestionAnswering", "question-answering"),
    ("MixtralForSequenceClassification", "text-classification"),
    ("MixtralForTokenClassification", "token-classification"),
    ("MllamaForCausalLM", "text-generation"),
    ("MllamaForConditionalGeneration", "image-text-to-text"),
    ("MobileBertForMaskedLM", "fill-mask"),
    ("MobileBertForMultipleChoice", "multiple-choice"),
    ("MobileBertForQuestionAnswering", "question-answering"),
    ("MobileBertForSequenceClassification", "text-classification"),
    ("MobileBertForTokenClassification", "token-classification"),
    ("MobileNetV1ForImageClassification", "image-classification"),
    ("MobileNetV2ForImageClassification", "image-classification"),
    ("MobileNetV2ForSemanticSegmentation", "image-segmentation"),
    ("MobileViTForImageClassification", "image-classification"),
    ("MobileViTForSemanticSegmentation", "image-segmentation"),
    ("MobileViTV2ForImageClassification", "image-classification"),
    ("MobileViTV2ForSemanticSegmentation", "image-segmentation"),
    ("ModernBertDecoderForCausalLM", "text-generation"),
    ("ModernBertDecoderForSequenceClassification", "text-classification"),
    ("ModernBertForMaskedLM", "fill-mask"),
    ("ModernBertForMultipleChoice", "multiple-choice"),
    ("ModernBertForQuestionAnswering", "question-answering"),
    ("ModernBertForSequenceClassification", "text-classification"),
    ("ModernBertForTokenClassification", "token-classification"),
    ("ModernVBertForMaskedLM", "fill-mask"),
    ("ModernVBertForSequenceClassification", "text-classification"),
    ("ModernVBertForTokenClassification", "token-classification"),
    ("MoonshineForConditionalGeneration", "automatic-speech-recognition"),
    ("MoonshineStreamingForConditionalGeneration", "automatic-speech-recognition"),
    ("MoshiForCausalLM", "text-generation"),
    ("MptForCausalLM", "text-generation"),
    ("MptForQuestionAnswering", "question-answering"),
    ("MptForSequenceClassification", "text-classification"),
    ("MptForTokenClassification", "token-classification"),
    ("MraForMaskedLM", "fill-mask"),
    ("MraForMultipleChoice", "multiple-choice"),
    ("MraForQuestionAnswering", "question-answering"),
    ("MraForSequenceClassification", "text-classification"),
    ("MraForTokenClassification", "token-classification"),
    ("MuseGlimmerForConditionalGeneration", "image-text-to-text"),
    ("MusicFlamingoForConditionalGeneration", "text2text-generation"),
    ("MusicgenForCausalLM", "text-generation"),
    ("MusicgenForConditionalGeneration", "text-to-speech"),
    ("MusicgenMelodyForCausalLM", "text-generation"),
    ("MusicgenMelodyForConditionalGeneration", "text-to-speech"),
    ("MvpForCausalLM", "text-generation"),
    ("MvpForQuestionAnswering", "question-answering"),
    ("MvpForSequenceClassification", "text-classification"),
    ("NanoChatForCausalLM", "text-generation"),
    ("NemotronForCausalLM", "text-generation"),
    ("NemotronForQuestionAnswering", "question-answering"),
    ("NemotronForSequenceClassification", "text-classification"),
    ("NemotronForTokenClassification", "token-classification"),
    ("NemotronHForCausalLM", "text-generation"),
    ("NeoMMEForMaskedLM", "fill-mask"),
    ("NllbMoeForConditionalGeneration", "text2text-generation"),
    ("NomicBertForMaskedLM", "fill-mask"),
    ("NomicBertForSequenceClassification", "text-classification"),
    ("NomicBertForTokenClassification", "token-classification"),
    ("NystromformerForMaskedLM", "fill-mask"),
    ("NystromformerForMultipleChoice", "multiple-choice"),
    ("NystromformerForQuestionAnswering", "question-answering"),
    ("NystromformerForSequenceClassification", "text-classification"),
    ("NystromformerForTokenClassification", "token-classification"),
    ("OPTForCausalLM", "text-generation"),
    ("OPTForQuestionAnswering", "question-answering"),
    ("OPTForSequenceClassification", "text-classification"),
    ("Olmo2ForCausalLM", "text-generation"),
    ("Olmo2ForSequenceClassification", "text-classification"),
    ("Olmo3ForCausalLM", "text-generation"),
    ("Olmo3ForSequenceClassification", "text-classification"),
    ("OlmoForCausalLM", "text-generation"),
    ("OlmoForSequenceClassification", "text-classification"),
    ("OlmoHybridForCausalLM", "text-generation"),
    ("OlmoeForCausalLM", "text-generation"),
    ("OmDetTurboForObjectDetection", "zero-shot-object-detection"),
    ("OneFormerForUniversalSegmentation", "image-segmentation"),
    ("OpenAIGPTForSequenceClassification", "text-classification"),
    ("OpenAIGPTLMHeadModel", "text-generation"),
    ("OpenAIPrivacyFilterForTokenClassification", "token-classification"),
    ("Ovis2ForConditionalGeneration", "image-text-to-text"),
    ("OwlViTForObjectDetection", "zero-shot-object-detection"),
    ("Owlv2ForObjectDetection", "zero-shot-object-detection"),
    ("PI0ForConditionalGeneration", "image-text-to-text"),
    ("PLBartForCausalLM", "text-generation"),
    ("PLBartForConditionalGeneration", "text2text-generation"),
    ("PLBartForSequenceClassification", "text-classification"),
    ("PPDocLayoutV2ForObjectDetection", "object-detection"),
    ("PPDocLayoutV3ForObjectDetection", "object-detection"),
    ("PPFormulaNetForConditionalGeneration", "image-text-to-text"),
    ("PPLCNetForImageClassification", "image-classification"),
    ("PPOCRV5MobileDetForObjectDetection", "object-detection"),
    ("PPOCRV5ServerDetForObjectDetection", "object-detection"),
    ("PPOCRV6MediumDetForObjectDetection", "object-detection"),
    ("PPOCRV6SmallDetForObjectDetection", "object-detection"),
    ("PaddleOCRVLForConditionalGeneration", "image-text-to-text"),
    ("PaliGemmaForConditionalGeneration", "image-text-to-text"),
    ("ParakeetForCTC", "automatic-speech-recognition"),
    ("PegasusForCausalLM", "text-generation"),
    ("PegasusForConditionalGeneration", "text2text-generation"),
    ("PegasusXForConditionalGeneration", "text2text-generation"),
    ("PerceiverForImageClassificationConvProcessing", "image-classification"),
    ("PerceiverForImageClassificationFourier", "image-classification"),
    ("PerceiverForImageClassificationLearned", "image-classification"),
    ("PerceiverForMaskedLM", "fill-mask"),
    ("PerceiverForSequenceClassification", "text-classification"),
    ("PerceptionLMForConditionalGeneration", "image-text-to-text"),
    ("PersimmonForCausalLM", "text-generation"),
    ("PersimmonForSequenceClassification", "text-classification"),
    ("PersimmonForTokenClassification", "token-classification"),
    ("Phi3ForCausalLM", "text-generation"),
    ("Phi3ForSequenceClassification", "text-classification"),
    ("Phi3ForTokenClassification", "token-classification"),
    ("Phi4MultimodalForCausalLM", "text-generation"),
    ("PhiForCausalLM", "text-generation"),
    ("PhiForSequenceClassification", "text-classification"),
    ("PhiForTokenClassification", "token-classification"),
    ("PhimoeForCausalLM", "text-generation"),
    ("PhimoeForSequenceClassification", "text-classification"),
    ("Pix2StructForConditionalGeneration", "image-text-to-text"),
    ("PoolFormerForImageClassification", "image-classification"),
    ("Pop2PianoForConditionalGeneration", "automatic-speech-recognition"),
    ("PromptDepthAnythingForDepthEstimation", "depth-estimation"),
    ("ProphetNetForCausalLM", "text-generation"),
    ("ProphetNetForConditionalGeneration", "text2text-generation"),
    ("PvtForImageClassification", "image-classification"),
    ("PvtV2ForImageClassification", "image-classification"),
    ("QianfanOCRForConditionalGeneration", "image-text-to-text"),
    ("Qwen2AudioForConditionalGeneration", "text2text-generation"),
    ("Qwen2ForCausalLM", "text-generation"),
    ("Qwen2ForQuestionAnswering", "question-answering"),
    ("Qwen2ForSequenceClassification", "text-classification"),
    ("Qwen2ForTokenClassification", "token-classification"),
    ("Qwen2MoeForCausalLM", "text-generation"),
    ("Qwen2MoeForQuestionAnswering", "question-answering"),
    ("Qwen2MoeForSequenceClassification", "text-classification"),
    ("Qwen2MoeForTokenClassification", "token-classification"),
    ("Qwen2VLForConditionalGeneration", "image-text-to-text"),
    ("Qwen2_5OmniForConditionalGeneration", "text-to-speech"),
    ("Qwen2_5OmniThinkerForConditionalGeneration", "image-text-to-text"),
    ("Qwen2_5_VLForConditionalGeneration", "image-text-to-text"),
    ("Qwen3ASRForTokenClassification", "token-classification"),
    ("Qwen3ForCausalLM", "text-generation"),
    ("Qwen3ForQuestionAnswering", "question-answering"),
    ("Qwen3ForSequenceClassification", "text-classification"),
    ("Qwen3ForTokenClassification", "token-classification"),
    ("Qwen3MoeForCausalLM", "text-generation"),
    ("Qwen3MoeForQuestionAnswering", "question-answering"),
    ("Qwen3MoeForSequenceClassification", "text-classification"),
    ("Qwen3MoeForTokenClassification", "token-classification"),
    ("Qwen3NextForCausalLM", "text-generation"),
    ("Qwen3NextForQuestionAnswering", "question-answering"),
    ("Qwen3NextForSequenceClassification", "text-classification"),
    ("Qwen3NextForTokenClassification", "token-classification"),
    ("Qwen3OmniMoeForConditionalGeneration", "text-to-speech"),
    ("Qwen3OmniMoeThinkerForConditionalGeneration", "image-text-to-text"),
    ("Qwen3VLForConditionalGeneration", "image-text-to-text"),
    ("Qwen3VLMoeForConditionalGeneration", "image-text-to-text"),
    ("Qwen3_5ForCausalLM", "text-generation"),
    ("Qwen3_5ForConditionalGeneration", "image-text-to-text"),
    ("Qwen3_5ForSequenceClassification", "text-classification"),
    ("Qwen3_5ForTokenClassification", "token-classification"),
    ("Qwen3_5MoeForCausalLM", "text-generation"),
    ("Qwen3_5MoeForConditionalGeneration", "image-text-to-text"),
    ("Qwen3_5TextForSequenceClassification", "text-classification"),
    ("Qwen4ExpForCausalLM", "text-generation"),
    ("Qwen4ExpForConditionalGeneration", "image-text-to-text"),
    ("RTDetrForObjectDetection", "object-detection"),
    ("RTDetrV2ForObjectDetection", "object-detection"),
    ("RecurrentGemmaForCausalLM", "text-generation"),
    ("ReformerForMaskedLM", "fill-mask"),
    ("ReformerForQuestionAnswering", "question-answering"),
    ("ReformerForSequenceClassification", "text-classification"),
    ("ReformerModelWithLMHead", "text-generation"),
    ("RegNetForImageClassification", "image-classification"),
    ("RemBertForCausalLM", "text-generation"),
    ("RemBertForMaskedLM", "fill-mask"),
    ("RemBertForMultipleChoice", "multiple-choice"),
    ("RemBertForQuestionAnswering", "question-answering"),
    ("RemBertForSequenceClassification", "text-classification"),
    ("RemBertForTokenClassification", "token-classification"),
    ("ResNetForImageClassification", "image-classification"),
    ("RfDetrForInstanceSegmentation", "image-segmentation"),
    ("RfDetrForObjectDetection", "object-detection"),
    ("RoCBertForCausalLM", "text-generation"),
    ("RoCBertForMaskedLM", "fill-mask"),
    ("RoCBertForMultipleChoice", "multiple-choice"),
    ("RoCBertForQuestionAnswering", "question-answering"),
    ("RoCBertForSequenceClassification", "text-classification"),
    ("RoCBertForTokenClassification", "token-classification"),
    ("RoFormerForCausalLM", "text-generation"),
    ("RoFormerForMaskedLM", "fill-mask"),
    ("RoFormerForMultipleChoice", "multiple-choice"),
    ("RoFormerForQuestionAnswering", "question-answering"),
    ("RoFormerForSequenceClassification", "text-classification"),
    ("RoFormerForTokenClassification", "token-classification"),
    ("RobertaForCausalLM", "text-generation"),
    ("RobertaForMaskedLM", "fill-mask"),
    ("RobertaForMultipleChoice", "multiple-choice"),
    ("RobertaForQuestionAnswering", "question-answering"),
    ("RobertaForSequenceClassification", "text-classification"),
    ("RobertaForTokenClassification", "token-classification"),
    ("RobertaPreLayerNormForCausalLM", "text-generation"),
    ("RobertaPreLayerNormForMaskedLM", "fill-mask"),
    ("RobertaPreLayerNormForMultipleChoice", "multiple-choice"),
    ("RobertaPreLayerNormForQuestionAnswering", "question-answering"),
    ("RobertaPreLayerNormForSequenceClassification", "text-classification"),
    ("RobertaPreLayerNormForTokenClassification", "token-classification"),
    ("RwkvForCausalLM", "text-generation"),
    ("SEWDForCTC", "automatic-speech-recognition"),
    ("SEWDForSequenceClassification", "audio-classification"),
    ("SEWForCTC", "automatic-speech-recognition"),
    ("SEWForSequenceClassification", "audio-classification"),
    ("Sam2Model", "mask-generation"),
    ("Sam3TrackerModel", "mask-generation"),
    ("SamHQModel", "mask-generation"),
    ("SamModel", "mask-generation"),
    ("Sapiens2ForSemanticSegmentation", "image-segmentation"),
    ("SeamlessM4TForSpeechToText", "automatic-speech-recognition"),
    ("SeamlessM4TForTextToSpeech", "text-to-speech"),
    ("SeamlessM4TForTextToText", "text2text-generation"),
    ("SeamlessM4Tv2ForSpeechToText", "automatic-speech-recognition"),
    ("SeamlessM4Tv2ForTextToSpeech", "text-to-speech"),
    ("SeamlessM4Tv2ForTextToText", "text2text-generation"),
    ("SeedOssForCausalLM", "text-generation"),
    ("SeedOssForQuestionAnswering", "question-answering"),
    ("SeedOssForSequenceClassification", "text-classification"),
    ("SeedOssForTokenClassification", "token-classification"),
    ("SegformerForImageClassification", "image-classification"),
    ("SegformerForSemanticSegmentation", "image-segmentation"),
    ("ShieldGemma2ForImageClassification", "image-classification"),
    ("Siglip2ForImageClassification", "image-classification"),
    ("Siglip2Model", "zero-shot-image-classification"),
    ("SiglipForImageClassification", "image-classification"),
    ("SiglipModel", "zero-shot-image-classification"),
    ("SmolLM3ForCausalLM", "text-generation"),
    ("SmolLM3ForQuestionAnswering", "question-answering"),
    ("SmolLM3ForSequenceClassification", "text-classification"),
    ("SmolLM3ForTokenClassification", "token-classification"),
    ("SmolVLMForConditionalGeneration", "image-text-to-text"),
    ("SolarOpenForCausalLM", "text-generation"),
    ("Speech2TextForConditionalGeneration", "automatic-speech-recognition"),
    ("SpeechEncoderDecoderModel", "automatic-speech-recognition"),
    ("SpeechT5ForSpeechToText", "automatic-speech-recognition"),
    ("SpeechT5ForTextToSpeech", "text-to-speech"),
    ("SplinterForQuestionAnswering", "question-answering"),
    ("SqueezeBertForMaskedLM", "fill-mask"),
    ("SqueezeBertForMultipleChoice", "multiple-choice"),
    ("SqueezeBertForQuestionAnswering", "question-answering"),
    ("SqueezeBertForSequenceClassification", "text-classification"),
    ("SqueezeBertForTokenClassification", "token-classification"),
    ("StableLmForCausalLM", "text-generation"),
    ("StableLmForSequenceClassification", "text-classification"),
    ("StableLmForTokenClassification", "token-classification"),
    ("Starcoder2ForCausalLM", "text-generation"),
    ("Starcoder2ForSequenceClassification", "text-classification"),
    ("Starcoder2ForTokenClassification", "token-classification"),
    ("Step3p7ForConditionalGeneration", "image-text-to-text"),
    ("SuperPointForKeypointDetection", "keypoint-detection"),
    ("SwiftFormerForImageClassification", "image-classification"),
    ("Swin2SRForImageSuperResolution", "image-to-image"),
    ("SwinForImageClassification", "image-classification"),
    ("Swinv2ForImageClassification", "image-classification"),
    ("SwitchTransformersForConditionalGeneration", "text2text-generation"),
    ("T5ForConditionalGeneration", "text2text-generation"),
    ("T5ForQuestionAnswering", "question-answering"),
    ("T5ForSequenceClassification", "text-classification"),
    ("T5ForTokenClassification", "token-classification"),
    ("T5Gemma2ForSequenceClassification", "text-classification"),
    ("T5Gemma2ForTokenClassification", "token-classification"),
    ("T5GemmaForConditionalGeneration", "text2text-generation"),
    ("T5GemmaForSequenceClassification", "text-classification"),
    ("T5GemmaForTokenClassification", "token-classification"),
    ("TableTransformerForObjectDetection", "object-detection"),
    ("TapasForMaskedLM", "fill-mask"),
    ("TapasForQuestionAnswering", "table-question-answering"),
    ("TapasForSequenceClassification", "text-classification"),
    ("TextNetForImageClassification", "image-classification"),
    ("TimesFm2_5ModelForPrediction", "time-series-forecasting"),
    ("TimesFmModelForPrediction", "time-series-forecasting"),
    ("TimesformerForVideoClassification", "video-classification"),
    ("TimmWrapperForImageClassification", "image-classification"),
    ("Tipsv2DptForDepthEstimation", "depth-estimation"),
    ("Tipsv2DptForSemanticSegmentation", "image-segmentation"),
    ("Tipsv2Model", "zero-shot-image-classification"),
    ("TrOCRForCausalLM", "text-generation"),
    ("UMT5ForConditionalGeneration", "text2text-generation"),
    ("UMT5ForQuestionAnswering", "question-answering"),
    ("UMT5ForSequenceClassification", "text-classification"),
    ("UMT5ForTokenClassification", "token-classification"),
    ("UdopForConditionalGeneration", "image-text-to-text"),
    ("UniSpeechForCTC", "automatic-speech-recognition"),
    ("UniSpeechForSequenceClassification", "audio-classification"),
    ("UniSpeechSatForCTC", "automatic-speech-recognition"),
    ("UniSpeechSatForSequenceClassification", "audio-classification"),
    ("UperNetForSemanticSegmentation", "image-segmentation"),
    ("VJEPA2ForVideoClassification", "video-classification"),
    ("VaultGemmaForCausalLM", "text-generation"),
    ("ViTForImageClassification", "image-classification"),
    ("ViTMSNForImageClassification", "image-classification"),
    ("VideoLlama3ForConditionalGeneration", "image-text-to-text"),
    ("VideoLlavaForConditionalGeneration", "image-text-to-text"),
    ("VideoMAEForVideoClassification", "video-classification"),
    ("VideoPrismClipModel", "zero-shot-image-classification"),
    ("VideoPrismForVideoClassification", "video-classification"),
    ("VideomtForUniversalSegmentation", "image-segmentation"),
    ("ViltForQuestionAnswering", "visual-question-answering"),
    ("VipLlavaForConditionalGeneration", "image-text-to-text"),
    ("VisionEncoderDecoderModel", "image-text-to-text"),
    ("VitsModel", "text-to-speech"),
    ("VivitForVideoClassification", "video-classification"),
    ("Wav2Vec2BertForCTC", "automatic-speech-recognition"),
    ("Wav2Vec2BertForSequenceClassification", "audio-classification"),
    ("Wav2Vec2ConformerForCTC", "automatic-speech-recognition"),
    ("Wav2Vec2ConformerForSequenceClassification", "audio-classification"),
    ("Wav2Vec2ForCTC", "automatic-speech-recognition"),
    ("Wav2Vec2ForSequenceClassification", "audio-classification"),
    ("WavLMForCTC", "automatic-speech-recognition"),
    ("WavLMForSequenceClassification", "audio-classification"),
    ("WhisperForAudioClassification", "audio-classification"),
    ("WhisperForCausalLM", "text-generation"),
    ("WhisperForConditionalGeneration", "automatic-speech-recognition"),
    ("XGLMForCausalLM", "text-generation"),
    ("XLMForMultipleChoice", "multiple-choice"),
    ("XLMForQuestionAnsweringSimple", "question-answering"),
    ("XLMForSequenceClassification", "text-classification"),
    ("XLMForTokenClassification", "token-classification"),
    ("XLMRobertaForCausalLM", "text-generation"),
    ("XLMRobertaForMaskedLM", "fill-mask"),
    ("XLMRobertaForMultipleChoice", "multiple-choice"),
    ("XLMRobertaForQuestionAnswering", "question-answering"),
    ("XLMRobertaForSequenceClassification", "text-classification"),
    ("XLMRobertaForTokenClassification", "token-classification"),
    ("XLMRobertaXLForCausalLM", "text-generation"),
    ("XLMRobertaXLForMaskedLM", "fill-mask"),
    ("XLMRobertaXLForMultipleChoice", "multiple-choice"),
    ("XLMRobertaXLForQuestionAnswering", "question-answering"),
    ("XLMRobertaXLForSequenceClassification", "text-classification"),
    ("XLMRobertaXLForTokenClassification", "token-classification"),
    ("XLNetForMultipleChoice", "multiple-choice"),
    ("XLNetForQuestionAnsweringSimple", "question-answering"),
    ("XLNetForSequenceClassification", "text-classification"),
    ("XLNetForTokenClassification", "token-classification"),
    ("XLNetLMHeadModel", "text-generation"),
    ("XmodForCausalLM", "text-generation"),
    ("XmodForMaskedLM", "fill-mask"),
    ("XmodForMultipleChoice", "multiple-choice"),
    ("XmodForQuestionAnswering", "question-answering"),
    ("XmodForSequenceClassification", "text-classification"),
    ("XmodForTokenClassification", "token-classification"),
    ("YolosForObjectDetection", "object-detection"),
    ("YosoForMaskedLM", "fill-mask"),
    ("YosoForMultipleChoice", "multiple-choice"),
    ("YosoForQuestionAnswering", "question-answering"),
    ("YosoForSequenceClassification", "text-classification"),
    ("YosoForTokenClassification", "token-classification"),
    ("YoutuForCausalLM", "text-generation"),
    ("Zamba2ForCausalLM", "text-generation"),
    ("Zamba2ForSequenceClassification", "text-classification"),
    ("ZambaForCausalLM", "text-generation"),
    ("ZambaForSequenceClassification", "text-classification"),
    ("ZayaForCausalLM", "text-generation"),
    ("ZoeDepthForDepthEstimation", "depth-estimation"),
    ("xLSTMForCausalLM", "text-generation"),
];

/// (GGUF architecture, task), sorted: every Hugging Face class llama.cpp's converter registers for the architecture names this task.
pub const GGUF_CONVERTER_TASKS_V1: &[(&str, &str)] = &[
    ("afmoe", "text-generation"),            // AfmoeForCausalLM
    ("arwkv7", "text-generation"),           // RwkvHybridForCausalLM
    ("chameleon", "image-text-to-text"),     // ChameleonForConditionalGeneration
    ("codeshell", "text-generation"),        // CodeShellForCausalLM
    ("cogvlm", "text-generation"),           // CogVLMForCausalLM
    ("cohere2moe", "text-generation"),       // Cohere2MoeForCausalLM
    ("deci", "text-generation"),             // DeciLMForCausalLM
    ("deepseek32", "text-generation"),       // DeepseekV32ForCausalLM
    ("exaone-moe", "text-generation"),       // ExaoneMoEForCausalLM, ExaoneMoeForCausalLM
    ("gemma4-assistant", "text-generation"), // Gemma4AssistantForCausalLM, Gemma4UnifiedAssistantForCausalLM
    ("glm-dsa", "text-generation"),          // GlmMoeDsaForCausalLM
    ("graniteswitch", "text-generation"),    // GraniteSwitchForCausalLM
    ("grok", "text-generation"),             // Grok1ForCausalLM, GrokForCausalLM
    ("grovemoe", "text-generation"),         // GroveMoeForCausalLM, modeling_grove_moe.GroveMoeForCausalLM
    ("hunyuan_vl", "image-text-to-text"),    // HunYuanVLForConditionalGeneration
    ("hy_v3", "text-generation"),            // HYV3ForCausalLM
    ("jais2", "text-generation"),            // Jais2ForCausalLM
    ("laguna", "text-generation"),           // LagunaForCausalLM
    ("maincoder", "text-generation"),        // MaincoderForCausalLM
    ("mellum", "text-generation"),           // MellumForCausalLM
    ("mimo2", "text-generation"),            // MiMoV2FlashForCausalLM, MiMoV2ForCausalLM
    ("muse-glimmer", "image-text-to-text"),  // MuseGlimmerForConditionalGeneration
    ("nanbeige", "text-generation"),         // NanbeigeForCausalLM
    ("paddleocr", "image-text-to-text"),     // PaddleOCRVLForConditionalGeneration
    ("pangu-embedded", "text-generation"),   // PanguEmbeddedForCausalLM
    ("plamo3", "text-generation"),           // PLaMo3ForCausalLM, Plamo3ForCausalLM
    ("plm", "text-generation"),              // PLMForCausalLM
    ("rwkv6qwen2", "text-generation"),       // RWKV6Qwen2ForCausalLM
    ("smallthinker", "text-generation"),     // SmallThinkerForCausalLM
    ("talkie", "text-generation"),           // TalkieForCausalLM
    ("xverse", "text-generation"),           // XverseForCausalLM
];

/// llama.cpp @030ebb55's model architectures (`LLM_ARCH_NAMES`, `src/llama-arch.cpp`) less `clip` (a projector, not a model): a GGUF
/// whose `general.architecture` is one of them is a model file of a known runtime — a model class, whether or not a task is derivable.
pub const LLAMA_CPP_MODEL_ARCHS_V1: &[&str] = &[
    "afmoe",
    "apertus",
    "arcee",
    "arctic",
    "arwkv7",
    "baichuan",
    "bailingmoe",
    "bailingmoe2",
    "bert",
    "bitnet",
    "bloom",
    "chameleon",
    "chatglm",
    "codeshell",
    "cogvlm",
    "cohere2",
    "cohere2moe",
    "command-r",
    "dbrx",
    "deci",
    "deepseek",
    "deepseek2",
    "deepseek2-ocr",
    "deepseek32",
    "deepseek4",
    "dflash",
    "dots1",
    "dream",
    "eagle3",
    "ernie4_5",
    "ernie4_5-moe",
    "eurobert",
    "exaone",
    "exaone-moe",
    "exaone4",
    "falcon",
    "falcon-h1",
    "gemma",
    "gemma-embedding",
    "gemma2",
    "gemma3",
    "gemma3n",
    "gemma4",
    "gemma4-assistant",
    "glm-dsa",
    "glm4",
    "glm4moe",
    "gpt-oss",
    "gpt2",
    "gptj",
    "gptneox",
    "granite",
    "granitehybrid",
    "granitemoe",
    "graniteswitch",
    "grok",
    "grovemoe",
    "hunyuan-dense",
    "hunyuan-moe",
    "hunyuan_vl",
    "hy_v3",
    "internlm2",
    "jais",
    "jais2",
    "jamba",
    "jina-bert-v2",
    "jina-bert-v3",
    "kimi-linear",
    "laguna",
    "lfm2",
    "lfm2moe",
    "llada",
    "llada-moe",
    "llama",
    "llama-embed",
    "llama4",
    "maincoder",
    "mamba",
    "mamba2",
    "mellum",
    "mimo2",
    "minicpm",
    "minicpm3",
    "minimax-m2",
    "minimax-m3",
    "mistral3",
    "mistral4",
    "modern-bert",
    "mpt",
    "muse-glimmer",
    "nanbeige",
    "nemotron",
    "nemotron_h",
    "nemotron_h_moe",
    "neo-bert",
    "nomic-bert",
    "nomic-bert-moe",
    "olmo",
    "olmo2",
    "olmoe",
    "openelm",
    "orion",
    "paddleocr",
    "pangu-embedded",
    "phi2",
    "phi3",
    "phimoe",
    "plamo",
    "plamo2",
    "plamo3",
    "plm",
    "qwen",
    "qwen2",
    "qwen2moe",
    "qwen2vl",
    "qwen3",
    "qwen35",
    "qwen35moe",
    "qwen3moe",
    "qwen3next",
    "qwen3tts",
    "qwen3vl",
    "qwen3vlmoe",
    "refact",
    "rnd1",
    "rwkv6",
    "rwkv6qwen2",
    "rwkv7",
    "seed_oss",
    "smallthinker",
    "smollm3",
    "stablelm",
    "starcoder",
    "starcoder2",
    "step35",
    "t5",
    "t5encoder",
    "talkie",
    "wavtokenizer-dec",
    "xverse",
];

/// The task transformers' auto-model tables give `class`, when exactly one.
pub fn hf_automap_task_v1(class: &str) -> Option<&'static str> {
    HF_AUTOMAP_TASKS_V1.binary_search_by(|(c, _)| (*c).cmp(class)).ok().map(|i| HF_AUTOMAP_TASKS_V1[i].1)
}

/// The task llama.cpp's converter fixes for a GGUF architecture, when its registered classes name exactly one.
pub fn gguf_converter_task_v1(arch: &str) -> Option<&'static str> {
    GGUF_CONVERTER_TASKS_V1.binary_search_by(|(a, _)| (*a).cmp(arch)).ok().map(|i| GGUF_CONVERTER_TASKS_V1[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tables_are_sorted_unique_and_read_by_binary_search() {
        for w in HF_AUTOMAP_TASKS_V1.windows(2) {
            assert!(w[0].0 < w[1].0, "{} before {}", w[0].0, w[1].0);
        }
        for w in GGUF_CONVERTER_TASKS_V1.windows(2) {
            assert!(w[0].0 < w[1].0);
        }
        for w in LLAMA_CPP_MODEL_ARCHS_V1.windows(2) {
            assert!(w[0] < w[1]);
        }
        assert_eq!(hf_automap_task_v1("MarianMTModel"), Some("text2text-generation"));
        assert_eq!(hf_automap_task_v1("CLIPModel"), Some("zero-shot-image-classification"));
        // A class transformers lists under two tasks is not a task: never guessed.
        assert_eq!(hf_automap_task_v1("BartForConditionalGeneration"), None);
        assert_eq!(hf_automap_task_v1("CustomResearchModel"), None);
        assert_eq!(gguf_converter_task_v1("glm-dsa"), Some("text-generation"));
        assert_eq!(gguf_converter_task_v1("qwen3"), None, "decided by inference v2's hand table, not here");
        assert!(!LLAMA_CPP_MODEL_ARCHS_V1.contains(&"clip"), "a projector is not a model");
        assert!(LLAMA_CPP_MODEL_ARCHS_V1.contains(&"qwen3tts"));
    }
}
