//! **The reduced SD3 / MMDiT pipeline as a registered generative class** (RFC-0003 activation step 6): the gate, the
//! container, a job, and the court battery over the lowered programs.
//!
//! The fixture is the lowerer's (`misaka_palw_tir_lower::diffusion::fixture::build_sd3_tiny`, generated by
//! `tools/gen_diffusers_sd3_fixture.py`); a checkout without it skips with a line saying so. The battery plants a lie
//! (`GenPlantV1`, what `misaka palw gen-claim --plant` commits) at the FIRST leaf of every commit-point KIND of the
//! class — (stage, block, primitive), and the `Fixed` state checkpoints — and requires the cone close at that leaf to
//! convict it, the honest run to be acquitted at the same leaf, and the close to fit the one-move carrier
//! (PALW-GEN-21). It also plants the cases the RFC names: a lie at the latent's first position (the leaf whose cone reads
//! the noise: forged noise), at the denoiser's first carry (the leaf whose cone reads the stage edge: forged edge), a
//! forged output digest (the output close), and a lane outside its node's proven interval (PALW-TIR-33, G21).

use kaspa_consensus_core::config::params::{ForkActivation, Params, palw_t12_shipped_params};
use kaspa_consensus_core::palw_court_v2::{PalwCourtV2Error, PalwCourtVerdictProofV2, palw_gen_close_verdict_for_row_v1};
use kaspa_consensus_core::palw_freeprompt_v3::{PALW_FP_PRIVACY_PUBLIC_DA, PALW_FP_PROMPT_MODE_USER};
use kaspa_consensus_core::palw_gen_class_v1::*;
use kaspa_consensus_core::palw_gen_job_v1::*;
use kaspa_consensus_core::palw_gen_one_move_v1::{palw_gen_one_move_max_proof_bytes_v1, palw_gen_one_move_proof_is_admissible_v1};
use kaspa_consensus_core::palw_gen_step_v1::PalwGenLeafKindV1;
use kaspa_consensus_core::palw_gen_v1::{PALW_DRILL_GEN_V1_ENTRY, PalwGenProfileV1};
use kaspa_consensus_core::palw_held_close_v1::PALW_HELD_CLOSE_CHUNKS_ENTRY_V1;
use kaspa_consensus_core::palw_mode_v2::PalwConsensusMode;
use kaspa_consensus_core::palw_prompt_ids_v1::{PalwPromptIdsFormV1, prompt_token_ids_commitment_v1};
use kaspa_consensus_core::palw_state_v2::{PALW_OBJECT_CHUNK_MAX_BYTES, PalwCourtVerdictV2};
use kaspa_consensus_core::palw_tir_v1::PALW_T12_TIR_V1_ENTRY;
use kaspa_consensus_core::tx::{TransactionId, TransactionOutpoint};
use kaspa_hashes::Hash64;
use misaka_palw_base0::gen_tensor_worker::{GenPlantV1, GenTensorCaptureV1, GenTensorWorkV1, gen_tensor_court_candidates_v1};
use misaka_palw_base0::gen_worker::{GenCourtMoveV1, GenHeldClassV1};
use misaka_palw_gen::OutputSpecV1;
use misaka_palw_sdk::gen_class::*;
use misaka_palw_tir::demand::DemandLimits;
use misaka_palw_tir::interp::ParamSource;
use misaka_palw_tir::pipeline::PipelineParams;
use misaka_palw_tir_lower::diffusion::fixture::{COUNTS, L, build_sd3_tiny, fixture};
use std::collections::BTreeMap;
use std::path::PathBuf;

const FORM: PalwPromptIdsFormV1 = PalwPromptIdsFormV1::Flat;
const LIMITS: DemandLimits = DemandLimits { max_elements: 1 << 20, max_terms: 1 << 24 };
const IMAGE_HW: u32 = 16;
/// The layout's tile: step-leaf lanes and weight rows per tile (`SD3_TILE=<n>` overrides, for the sweep).
const TILE_LEN: u32 = 16;

struct Weights(Vec<Box<dyn ParamSource + Send + Sync>>);

impl PipelineParams for Weights {
    fn params(&self, program: u16) -> &dyn ParamSource {
        self.0[program as usize].as_ref()
    }
}

fn all_armed() -> Params {
    let mut p = palw_t12_shipped_params();
    (PALW_T12_TIR_V1_ENTRY.set)(&mut p, Some(ForkActivation::new(1)));
    (PALW_DRILL_GEN_V1_ENTRY.set)(&mut p, Some(ForkActivation::new(1)));
    (PALW_HELD_CLOSE_CHUNKS_ENTRY_V1.set)(&mut p, Some(ForkActivation::new(1)));
    p
}

fn court() -> kaspa_consensus_core::palw_mode_v2::PalwCourtParamsV2 {
    match &palw_t12_shipped_params().palw_consensus_mode {
        PalwConsensusMode::ConsensusV2(b) => b.court.clone(),
        _ => unreachable!("testnet-12 runs V2"),
    }
}

struct Sd3Class {
    weights: Weights,
    declared: GenDeclaredV1,
    row: PalwGenClassRecordV1,
    spec: GenClassSpecV1,
    job: PalwGenJobV1,
    ids: Vec<u32>,
}

fn sd3_class() -> Option<Sd3Class> {
    let dir = fixture()?;
    let fx = build_sd3_tiny(&dir).expect("the fixture lowers");
    let pipe = &fx.pipeline;
    let weights = Weights(pipe.params.iter().cloned().map(|p| Box::new(p) as Box<dyn ParamSource + Send + Sync>).collect());
    // The steps scalar is the step count's POSITION among the offered counts (the gate says so).
    let steps_scalar = PalwGenScalarOfferV1 { lo: 0, hi: COUNTS.len() as i64 - 1 };
    let sampler_id = Hash64::from_bytes([0x5D; 64]);
    let spec = GenClassSpecV1 {
        profile: PalwGenProfileV1::Image,
        pipeline: pipe.pipeline.clone(),
        programs: pipe.programs.clone(),
        tokenizer_id: Hash64::from_bytes([0x73; 64]),
        output: OutputSpecV1::image_rgb8(IMAGE_HW, IMAGE_HW),
        offers: PalwGenOffersV1 {
            steps: COUNTS.to_vec(),
            profile: PalwGenProfileOffersV1::Image(PalwGenImageOffersV1 { sampler_id, guidance: None, steps_scalar: Some(0) }),
            scalars: vec![steps_scalar],
            max_prompt_tokens: (L - 2) as u32,
            max_negative_tokens: 0,
            images: vec![],
            max_source_tokens: 0,
            forced_prompt_prefix: vec![],
            source_token_floor: 0,
        },
    };
    let params = all_armed();
    let PalwConsensusMode::ConsensusV2(bundle) = &params.palw_consensus_mode else { panic!("testnet-12 is ConsensusV2") };
    let declared = gen_declare_layout_v1(
        &params,
        bundle,
        &spec,
        &weights,
        // `tile_len` is the lanes of a step leaf AND the rows of a weight tile: every axis-0 row of a param is its own artifact leaf
        // with its own Merkle path (~1.1 KB), so a cone of a `T`-lane output tile opens `T` rows — 16, not 64 (64 rows is 70 KB).
        &GenLayoutChoiceV1 { tile_len: TILE_LEN, output_tile: None, h_chunk: 16, checkpoint_interval: 1 },
    )
    .unwrap_or_else(|e| panic!("declare: {e}"));
    let row = declared.row.clone().expect("the class derives a registry row");
    // `SD3_PROMPT=<ids, comma separated>` asks for another prompt (at most `L − 2` ids).
    let ids: Vec<u32> = std::env::var("SD3_PROMPT")
        .ok()
        .map(|v| v.split(',').filter_map(|x| x.trim().parse().ok()).collect())
        .filter(|v: &Vec<u32>| !v.is_empty() && v.len() <= L - 2)
        .unwrap_or_else(|| vec![5, 9, 13]);
    // The widest job's step count unless `SD3_STEPS=<an offered count>` asks for another job of the class (the price is the class's, and
    // bounds every job: the sweep may be run on a shorter one).
    let steps = std::env::var("SD3_STEPS").ok().and_then(|v| v.parse::<u16>().ok()).unwrap_or(COUNTS[COUNTS.len() - 1] as u16);
    assert!(COUNTS.contains(&(steps as u32)), "SD3_STEPS is one of {COUNTS:?}");
    let job = PalwGenJobV1 {
        version: PALW_GEN_JOB_VERSION_V1,
        envelope: PalwJobEnvelopeV1 {
            network_domain: Hash64::from_bytes([0xD0; 64]),
            class_id: row.class_id,
            executor_bond: TransactionOutpoint::new(TransactionId::from_bytes([7; 64]), 0),
            // The bond's key, as long as it is on chain: a close carries the whole job, the key in it.
            executor_pubkey: vec![1; kaspa_consensus_core::mldsa87_primitives::MLDSA87_PUBKEY_LEN],
            operator_id: Hash64::from_bytes([2; 64]),
            anchor_block: Hash64::from_bytes([3; 64]),
            anchor_daa: 100,
            job_nonce: [4; 32],
            privacy_mode: PALW_FP_PRIVACY_PUBLIC_DA,
            prompt_mode: PALW_FP_PROMPT_MODE_USER,
        },
        seed: [0x33; 32],
        body: PalwGenBodyV1::Image(PalwGenImageBodyV1 {
            prompt_token_ids_hash: prompt_token_ids_commitment_v1(FORM, &ids).unwrap(),
            prompt_tokens: ids.len() as u32,
            negative_token_ids_hash: Hash64::default(),
            negative_tokens: 0,
            guidance_q: 0,
            image_index: 0,
            sampler_id,
            steps,
            width: IMAGE_HW as u16,
            height: IMAGE_HW as u16,
            output: misaka_palw_gen::OutputKindV1::ImageRgb8.tag(),
        }),
    };
    Some(Sd3Class { weights, declared, row, spec, job, ids })
}

struct Guard(PathBuf);
impl Drop for Guard {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

fn held(c: &Sd3Class) -> (GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>, Guard) {
    // One file per call: the tests of this file run in threads of one process and each removes its own container on drop.
    static NEXT: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let n = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!("misaka-gen-sd3-{}-{n}.palwtir2", std::process::id()));
    let guard = Guard(path.clone());
    gen_write_declared_container_v1(&path, &c.declared, &c.weights, "{\"model_id\":\"palw-fixture/sd3-tiny\"}".to_string())
        .expect("the container");
    (GenHeldClassV1::hold_container(c.row.clone(), &path).expect("the worker holds the class"), guard)
}

fn cone_close(
    held: &GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>,
    accused: &GenTensorWorkV1,
    leaf: u64,
) -> Result<(PalwCourtVerdictProofV2, usize), String> {
    let moves = gen_tensor_court_candidates_v1(held, accused, leaf, true, &LIMITS);
    let (_, cone) = moves.iter().find(|(n, _)| *n == "cone").ok_or("no cone close at this leaf")?;
    match cone.clone()? {
        GenCourtMoveV1::Close(proof) => {
            let bytes = borsh::to_vec(&proof).map_err(|e| e.to_string())?.len();
            Ok((proof, bytes))
        }
        _ => Err("not a close".to_string()),
    }
}

fn verdict(
    c: &Sd3Class,
    who: &GenTensorWorkV1,
    proof: &PalwCourtVerdictProofV2,
    leaf: u64,
) -> Result<PalwCourtVerdictV2, PalwCourtV2Error> {
    palw_gen_close_verdict_for_row_v1(&c.row, &c.row.class_id, &who.execution_root(), proof, Some(leaf), &court(), FORM, false)
}

/// The leaves of the honest run, grouped by KIND: (stage name, block name, primitive) for a commit, the state's name for a
/// checkpoint — each with its first leaf (a leaf with lanes) and its count.
fn kinds(c: &Sd3Class, honest: &GenTensorWorkV1) -> BTreeMap<String, (u64, usize)> {
    let mut kinds: BTreeMap<String, (u64, usize)> = BTreeMap::new();
    for l in honest.leaf_listing() {
        if l.lanes == 0 {
            continue;
        }
        let st = &c.spec.pipeline.stages[l.stage as usize];
        let prog = &c.spec.programs[st.program as usize];
        let kind = match l.kind.split_once(' ') {
            Some(("commit", rest)) => {
                let (occ, node) = rest.split_once('.').expect("occurrence.node");
                let (occ, node): (usize, usize) = (occ.parse().unwrap(), node.parse().unwrap());
                let (block, _layer) = prog.occurrences()[occ];
                let b = &prog.blocks[block as usize];
                format!("{} / {} / {}", st.name, b.name, b.nodes[node].prim.name())
            }
            _ => format!("{} / {}", st.name, l.kind),
        };
        let e = kinds.entry(kind).or_insert((l.global, 0));
        e.1 += 1;
    }
    kinds
}

/// Is global leaf `index` a dissected commit point of the class (a fused attention site: a lie there is a held
/// dissection's, not a cone close's)?
fn is_dissected(held: &GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>, honest: &GenTensorWorkV1, index: u64) -> bool {
    let (stage, local) = honest.execution.space.locate(index).expect("a leaf of the run");
    let sp = &honest.execution.space.stages[stage as usize];
    match sp.leaves()[local as usize].coord.kind {
        PalwGenLeafKindV1::Commit { occurrence, node } => {
            sp.occurrence_block(occurrence).is_some_and(|b| held.row.dissected.contains(&(stage, b, node)))
        }
        PalwGenLeafKindV1::State { .. } => false,
    }
}

/// **The cone-close table**: every commit-point kind of the class, its first leaf's cone close, in bytes and against
/// the one-move carrier (PALW-GEN-21). One evidence of the honest run serves them all (the structure of a cone close does
/// not depend on a lie). A class must be convictable by the one-move path alone: every kind but the dissected ones fits.
#[test]
fn the_sd3_class_passes_the_gate_and_every_cone_close_fits_one_carrier() {
    let Some(c) = sd3_class() else { return };
    let admitted = c.declared.admission.as_ref().unwrap_or_else(|why| panic!("the registration gate refuses the SD3 class: {why}"));
    eprintln!(
        "sd3-tiny: class {} — {} canonical step leaves, {} at the widest job",
        c.row.class_id, admitted.entry.canonical_step_leaf_count, admitted.entry.max_step_leaf_count
    );
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).unwrap_or_else(|e| panic!("the worker refuses the job: {e}"));
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    assert!(one_move_max < PALW_OBJECT_CHUNK_MAX_BYTES);
    let ev = honest.evidence(&held);
    let table = kinds(&c, &honest);
    eprintln!("{} step leaves in {} commit-point kinds (one-move carrier {one_move_max} B)", honest.leaf_listing().len(), table.len());
    eprintln!("  {:<62} {:>6} {:>9} {:>9}", "kind (stage / block / primitive)", "leaves", "close B", "margin B");
    let (mut over, mut dissected, mut worst) = (Vec::new(), Vec::new(), (0usize, String::new()));
    for (kind, (leaf, count)) in &table {
        if is_dissected(&held, &honest, *leaf) {
            dissected.push(kind.clone());
            eprintln!("  {kind:<62} {count:>6} {:>9} {:>9}", "dissected", "-");
            continue;
        }
        let close = ev.cone_close(*leaf, &LIMITS).unwrap_or_else(|e| panic!("{kind} (leaf {leaf}): {e}"));
        let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close) }).unwrap().len();
        let margin = one_move_max as i64 - bytes as i64;
        eprintln!("  {kind:<62} {count:>6} {bytes:>9} {margin:>9}{}", if margin < 0 { "  <-- OVER" } else { "" });
        if margin < 0 {
            over.push((kind.clone(), bytes));
        }
        if bytes > worst.0 {
            worst = (bytes, kind.clone());
        }
    }
    eprintln!("largest cone close: {} B ({}); {} dissected kinds: {dissected:?}", worst.0, worst.1, dissected.len());
    assert!(over.is_empty(), "kinds whose cone close exceeds the one-move carrier: {over:?}");
}

/// **The class registers where a close can only ride ONE carrier** (PALW-GEN-21): the same registration under the same ruleset without
/// the held leaf challenge's chunks (`palw_held_close_chunks_v1`) is admitted — every close the gate prices, as the builder carries it
/// (PALW-GEN-20), fits the one-move accusation — and the catalog records the worst of them. Before the lowering used static maps and
/// two-piece tables the same pricing refused it (the HF activation tables of four 32 KiB pieces are a 140 KB close; a convolution that
/// gathers by an index table is a close of one input leaf per tap).
#[test]
fn the_sd3_class_registers_where_a_close_can_only_ride_one_carrier() {
    use kaspa_consensus_core::palw_gen_admission_v1::{PalwGenAdmissionRulesV1, palw_gen_post_genesis_registration_v1, palw_gen_registration_preflight_at_v1};
    use kaspa_consensus_core::palw_state_v2::PalwBondKeyV2;
    let Some(c) = sd3_class() else { return };
    let mut p = all_armed();
    (PALW_HELD_CLOSE_CHUNKS_ENTRY_V1.set)(&mut p, None);
    let rules = PalwGenAdmissionRulesV1::at(&p, 1).expect("the generative fence is in force");
    assert!(rules.held_armed && !rules.held_close_chunks, "the held regime without chunks: a close can only ride one carrier");
    let PalwConsensusMode::ConsensusV2(bundle) = &p.palw_consensus_mode else { panic!("testnet-12 is ConsensusV2") };
    let bond = PalwBondKeyV2(TransactionOutpoint::new(TransactionId::from_bytes([0; 64]), 0));
    let object =
        palw_gen_post_genesis_registration_v1(c.declared.class.clone(), c.declared.artifact_root, 0, 1 << 100, 1, 1, bond, Vec::new())
            .expect("the registration counts");
    let admitted = palw_gen_registration_preflight_at_v1(&p, bundle, &object, 1)
        .unwrap_or_else(|e| panic!("the class is refused where a close can only ride one carrier: {e}"));
    let one_move = palw_gen_one_move_max_proof_bytes_v1();
    eprintln!(
        "admitted with one-move closes only: the catalog's worst close {} B (one-move carrier {one_move} B), {} B of terminal MACs",
        admitted.entry.court_cost.max_close_bytes, admitted.entry.court_cost.max_terminal_macs
    );
    assert!(admitted.entry.court_cost.max_close_bytes <= one_move);
    // And the chunked ruleset records the same class and the same worst close.
    let chunked = c.declared.admission.as_ref().expect("admitted with chunks");
    assert_eq!(chunked.entry.court_cost.max_close_bytes, admitted.entry.court_cost.max_close_bytes);
}

/// What one cone close is made of, for the kinds the table flags: the frame, the operands (step leaves it opens, each with
/// its path) and the params (artifact openings). `SD3_KIND=<substring of a kind>` picks the kinds (default: none).
#[test]
#[ignore = "diagnostic: SD3_KIND=<substring> cargo test -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture breakdown"]
fn breakdown_of_the_close_at_a_kind() {
    let Some(c) = sd3_class() else { return };
    let want = std::env::var("SD3_KIND").unwrap_or_default();
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let ev = honest.evidence(&held);
    for (kind, (leaf, _)) in kinds(&c, &honest) {
        if want.is_empty() || !kind.contains(&want) || is_dissected(&held, &honest, leaf) {
            continue;
        }
        let close = ev.cone_close(leaf, &LIMITS).expect("a cone close");
        let operands: usize = close.operands.iter().map(|o| borsh::to_vec(o).unwrap().len()).sum();
        let params: Vec<usize> = close.params.iter().map(|p| borsh::to_vec(p).unwrap().len()).collect();
        let disputed = borsh::to_vec(&close.disputed).unwrap().len();
        let total = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close.clone()) }).unwrap().len();
        eprintln!(
            "{kind} (leaf {leaf}): total {total} B = disputed {disputed} + {} operands {operands} + {} param openings {} (largest {:?}) + frame/binding {}",
            close.operands.len(),
            params.len(),
            params.iter().sum::<usize>(),
            params.iter().max(),
            total - disputed - operands - params.iter().sum::<usize>()
        );
        for o in close.operands.iter().take(6) {
            eprintln!("    operand {:?}: {} lanes B, path {}", o.coord, o.lanes_le.len(), o.path.len());
        }
    }
}

/// **PALW-GEN-20: what the gate prices a close at**, per commit point `(stage, block, node)`, and the work the sizing did.
fn gate_prices(
    c: &Sd3Class,
) -> (BTreeMap<(u8, u8, u16), kaspa_consensus_core::palw_tir_close_size_v1::PalwTirCloseBoundV1>, u64) {
    use kaspa_consensus_core::palw_gen_close_price_v1::{PALW_GEN_CLOSE_SIZING_WORK_CAP_V1, palw_gen_worst_closes_of_class_v1};
    let leaves = kaspa_consensus_core::palw_gen_artifact_v1::PalwGenInventoryIndexV1::new(&c.spec.programs)
        .expect("the class's inventory")
        .leaf_count();
    let (bounds, work) = palw_gen_worst_closes_of_class_v1(
        &c.declared.class,
        &c.spec.pipeline,
        &c.spec.programs,
        leaves,
        true,
        u64::MAX,
        u64::MAX,
        PALW_GEN_CLOSE_SIZING_WORK_CAP_V1,
    )
    .unwrap_or_else(|e| panic!("the close sizing refuses the class: {e}"));
    let mut by_point = BTreeMap::new();
    for (s, stage) in bounds.into_iter().enumerate() {
        for b in stage {
            // A checkpoint leaf's bound is by `(stage, state)`: see `checkpoint_prices`.
            if b.checkpoint.is_none() {
                by_point.insert((s as u8, b.block, b.node), b);
            }
        }
    }
    (by_point, work)
}

/// The prices of the stages' checkpoint leaves, by `(stage, state)` — none for this class (no `Fixed` state outside `post`).
fn checkpoint_prices(c: &Sd3Class) -> BTreeMap<(u8, u16), u64> {
    use kaspa_consensus_core::palw_gen_close_price_v1::{PALW_GEN_CLOSE_SIZING_WORK_CAP_V1, palw_gen_worst_closes_of_class_v1};
    let leaves = kaspa_consensus_core::palw_gen_artifact_v1::PalwGenInventoryIndexV1::new(&c.spec.programs).expect("inventory").leaf_count();
    let (bounds, _) = palw_gen_worst_closes_of_class_v1(
        &c.declared.class,
        &c.spec.pipeline,
        &c.spec.programs,
        leaves,
        true,
        u64::MAX,
        u64::MAX,
        PALW_GEN_CLOSE_SIZING_WORK_CAP_V1,
    )
    .expect("the sizing");
    bounds
        .into_iter()
        .enumerate()
        .flat_map(|(s, st)| st.into_iter().filter_map(move |b| b.checkpoint.map(|state| ((s as u8, state), b.close_bytes))))
        .collect()
}

/// The commit point `(stage, block, node)` a listed leaf is a leaf of, and its kind's name — `None` for a checkpoint leaf.
fn point_of(c: &Sd3Class, l: &misaka_palw_base0::gen_tensor_worker::GenLeafListingV1) -> Option<(u8, u8, u16)> {
    let ("commit", rest) = l.kind.split_once(' ')? else { return None };
    let (occ, node) = rest.split_once('.')?;
    let st = &c.spec.pipeline.stages[l.stage as usize];
    let (block, _layer) = c.spec.programs[st.program as usize].occurrences()[occ.parse::<usize>().ok()?];
    Some((l.stage, block, node.parse().ok()?))
}

/// **PALW-GEN-20, what the gate prices**: the sizing of every close of this class, per commit point, and the work it does. Cheap (no
/// close is built): the table is the gate's, printed beside the measured one by the sweep below.
#[test]
fn the_gate_sizes_every_close_of_the_sd3_class_within_its_work_cap() {
    use kaspa_consensus_core::palw_gen_close_price_v1::PALW_GEN_CLOSE_SIZING_WORK_CAP_V1;
    let Some(c) = sd3_class() else { return };
    let started = std::time::Instant::now();
    let (prices, work) = gate_prices(&c);
    eprintln!(
        "the gate sizes {} commit points in {work} steps of work (cap {PALW_GEN_CLOSE_SIZING_WORK_CAP_V1}), {:.1}s",
        prices.len(),
        started.elapsed().as_secs_f64()
    );
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1();
    let mut worst = (0u64, (0u8, 0u8, 0u16));
    for (k, b) in &prices {
        if b.close_bytes > worst.0 {
            worst = (b.close_bytes, *k);
        }
        eprintln!("  stage {} block {} node {:>3}: close {:>7} B{}", k.0, k.1, k.2, b.close_bytes, if b.dissected { format!(", root claim {} B (dissected)", b.root_claim_bytes) } else { String::new() });
    }
    eprintln!("the largest priced close: {} B at {:?} (one-move carrier {one_move_max} B)", worst.0, worst.1);
    assert!(work <= PALW_GEN_CLOSE_SIZING_WORK_CAP_V1);
    // Where the work goes: per stage.
    {
        use kaspa_consensus_core::palw_gen_close_price_v1::PalwGenClassSizingV1;
        use kaspa_consensus_core::palw_tir_close_size_v1::{PalwTirCloseSizingV1, PalwTirParamFormV1, palw_gen_worst_closes_v1};
        let class = &c.declared.class;
        let tables = PalwGenClassSizingV1::new(class, &c.spec.pipeline, &c.spec.programs).expect("tables");
        let leaves =
            kaspa_consensus_core::palw_gen_artifact_v1::PalwGenInventoryIndexV1::new(&c.spec.programs).expect("inventory").leaf_count();
        let mut total = 0u64;
        for (s, st) in c.spec.pipeline.stages.iter().enumerate() {
            let z = tables.stage(class, &c.spec.pipeline, &c.spec.programs, s).expect("stage");
            let sizing = PalwTirCloseSizingV1 { form: PalwTirParamFormV1::PerLeaf, court: true, cap: 1 << 40, stop_above: None };
            let (_, w) = palw_gen_worst_closes_v1(&z.space, &z.inventory, &z.job, &sizing, s, leaves, &z.model, z.pricing).expect("sizes");
            total += w;
            eprintln!("  stage {s:>2} {:<12} {w:>10} steps", st.name);
        }
        eprintln!("  total {total} steps");
    }
}

/// **PALW-GEN-20: the gate's price is an upper bound of the measured close — at every commit point, at every sampled leaf** (a
/// strided sweep of the widest job's leaves, `SD3_SWEEP_STRIDE=<n>`, default 40, and the first, middle and last leaf of every
/// commit point), measured as the one-move accusation carries it (the proof's bytes). Prints the table (priced, measured, margin,
/// ratio, per commit point) and asserts priced ≥ measured everywhere. A dissected point is held to its root claim and its bottoms.
#[test]
#[ignore = "slow: a cone close per sampled leaf: PALW_SWEEP=1 cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture the_gate_prices"]
fn the_gate_prices_every_close_at_least_what_it_measures() {
    let Some(c) = sd3_class() else { return };
    let (prices, work) = gate_prices(&c);
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let ev = honest.evidence(&held);
    let stride: usize = std::env::var("SD3_SWEEP_STRIDE").ok().and_then(|v| v.parse().ok()).unwrap_or(40);
    let listing = honest.leaf_listing();
    // The leaves of every commit point, in order.
    let mut by_point: BTreeMap<(u8, u8, u16), Vec<u64>> = BTreeMap::new();
    for l in &listing {
        if l.lanes == 0 {
            continue;
        }
        if let Some(k) = point_of(&c, l) {
            by_point.entry(k).or_default().push(l.global);
        }
    }
    let mut sample: std::collections::BTreeSet<u64> = std::collections::BTreeSet::new();
    for (n, l) in listing.iter().enumerate() {
        if l.lanes > 0 && n % stride == 0 && point_of(&c, l).is_some() {
            sample.insert(l.global);
        }
    }
    // `SD3_SWEEP_STRIDE_ONLY=1`: the strided sample alone (the first sweep's 519 leaves at stride 40), for a run on another job.
    if std::env::var("SD3_SWEEP_STRIDE_ONLY").is_err() {
        for leaves in by_point.values() {
            sample.extend([leaves[0], leaves[leaves.len() / 2], leaves[leaves.len() - 1]]);
        }
        // The first leaf of every position of every commit point: the structure of a cone moves with the position (a state's replay, a
        // history's length, the first position's missing reads).
        let positions: BTreeMap<u64, u32> = listing.iter().map(|l| (l.global, l.pos)).collect();
        for leaves in by_point.values() {
            let mut seen = std::collections::BTreeSet::new();
            for leaf in leaves {
                if seen.insert(positions[leaf]) {
                    sample.insert(*leaf);
                }
            }
        }
    }
    let by_leaf: BTreeMap<u64, (u8, u8, u16)> = by_point.iter().flat_map(|(k, v)| v.iter().map(move |l| (*l, *k))).collect();
    let state_leaves = listing.iter().filter(|l| l.lanes > 0 && point_of(&c, l).is_none()).count();
    eprintln!("{state_leaves} checkpoint leaves; their prices by (stage, state): {:?}", checkpoint_prices(&c));
    assert_eq!(state_leaves == 0, checkpoint_prices(&c).is_empty(), "a class with checkpoint leaves is priced at them, and one without is not");
    eprintln!("the gate sizes {} commit points in {work} steps; measuring {} leaves (stride {stride})", prices.len(), sample.len());
    // Measured, per commit point: the largest, its leaf and the samples taken.
    let mut measured: BTreeMap<(u8, u8, u16), (u64, u64, usize)> = BTreeMap::new();
    let mut done = 0usize;
    for leaf in &sample {
        let point = by_leaf[leaf];
        if is_dissected(&held, &honest, *leaf) {
            continue;
        }
        let close = ev.cone_close(*leaf, &LIMITS).unwrap_or_else(|e| panic!("leaf {leaf} at {point:?}: {e}"));
        let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close) }).unwrap().len() as u64;
        let e = measured.entry(point).or_insert((0, *leaf, 0));
        e.2 += 1;
        if bytes > e.0 {
            e.0 = bytes;
            e.1 = *leaf;
        }
        done += 1;
        if done % 100 == 0 {
            eprintln!("  {done} closes measured");
        }
    }
    let name = |k: &(u8, u8, u16)| {
        let st = &c.spec.pipeline.stages[k.0 as usize];
        let b = &c.spec.programs[st.program as usize].blocks[k.1 as usize];
        format!("{} / {} / {}", st.name, b.name, b.nodes[k.2 as usize].prim.name())
    };
    eprintln!("  {:<58} {:>5} {:>9} {:>9} {:>8} {:>6}", "commit point (stage / block / primitive)", "n", "measured", "priced", "margin", "ratio");
    let (mut under, mut min_ratio, mut max_ratio, mut min_margin) = (Vec::new(), f64::MAX, 0f64, i64::MAX);
    for (k, (bytes, leaf, n)) in &measured {
        let price = prices[k].close_bytes;
        let (margin, ratio) = (price as i64 - *bytes as i64, price as f64 / *bytes as f64);
        eprintln!(
            "  {:<58} {n:>5} {bytes:>9} {price:>9} {margin:>8} {ratio:>6.2}{}",
            format!("{} [{},{}]", name(k), k.1, k.2),
            if margin < 0 { "  <-- UNDER" } else { "" }
        );
        min_ratio = min_ratio.min(ratio);
        max_ratio = max_ratio.max(ratio);
        min_margin = min_margin.min(margin);
        if margin < 0 {
            under.push((name(k), *k, *leaf, *bytes, price));
        }
    }
    eprintln!(
        "{} commit points, {done} closes measured: priced/measured in [{min_ratio:.3}, {max_ratio:.3}], the smallest margin {min_margin} B; priced below measured at {}: {under:?}",
        measured.len(),
        under.len()
    );
    // The dissected points: the root claim and the bottoms, as their moves carry them.
    for (k, b) in prices.iter().filter(|(_, b)| b.dissected) {
        let leaves = &by_point[k];
        let picks = [leaves[0], leaves[leaves.len() / 2], leaves[leaves.len() - 1]];
        let (mut root_worst, mut bottom_worst) = (0u64, 0u64);
        for leaf in picks {
            let (root, bottoms) = dissected_moves(&c, &held, &honest, &ev, leaf);
            root_worst = root_worst.max(root);
            bottom_worst = bottom_worst.max(bottoms);
        }
        eprintln!(
            "  dissected {}: root claim measured {root_worst} B priced {} B; bottom measured {bottom_worst} B priced {} B",
            name(k),
            b.root_claim_bytes,
            b.close_bytes
        );
        assert!(b.root_claim_bytes >= root_worst, "{}: the root claim is priced below what it measures", name(k));
        assert!(b.close_bytes >= bottom_worst, "{}: the bottom is priced below what it measures", name(k));
    }
    assert!(under.is_empty(), "the gate prices a close below its measurement at {} commit points: {under:?}", under.len());
}

/// **Diagnostic: what the gate's price of one commit point is made of** — the read set of its worst tile at the stage's last position
/// (`SD3_POINT=<stage>,<block>,<node>`): the step leaves, the param leaves (by param), the wild rows, the edges, each priced.
#[test]
#[ignore = "diagnostic: SD3_POINT=<stage>,<block>,<node> cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture breakdown_of_a_priced"]
fn breakdown_of_a_priced_close() {
    use kaspa_consensus_core::palw_gen_close_price_v1::PalwGenClassSizingV1;
    use kaspa_consensus_core::palw_tir_close_size_v1::{PalwTirCloseRequestV1, PalwTirClosePriceV1, palw_gen_close_reads_v1};
    use misaka_palw_tir::demand::{DemandContext, history_length_v1};
    let Some(c) = sd3_class() else { return };
    let want = std::env::var("SD3_POINT").expect("SD3_POINT=<stage>,<block>,<node>");
    let [s, bi, ni]: [usize; 3] = want.split(',').map(|v| v.trim().parse().unwrap()).collect::<Vec<_>>().try_into().expect("three numbers");
    let class = &c.declared.class;
    let tables = PalwGenClassSizingV1::new(class, &c.spec.pipeline, &c.spec.programs).expect("tables");
    let z = tables.stage(class, &c.spec.pipeline, &c.spec.programs, s).expect("the stage's sizing");
    let leaves = kaspa_consensus_core::palw_gen_artifact_v1::PalwGenInventoryIndexV1::new(&c.spec.programs).unwrap().leaf_count();
    let price = PalwTirClosePriceV1::generative(&z.space, &z.inventory, s, leaves, z.pricing.clone()).expect("a price");
    let occ = z.space.occurrences().iter().position(|(b, _)| *b as usize == bi).expect("an occurrence of the block");
    let p_max = z.space.job_shape(&z.job).unwrap().positions - 1;
    let tile_len = z.space.commit_tile_len(bi as u8, ni as u16).expect("a commit point") as usize;
    let h = history_length_v1(&z.space.info, bi as u8, p_max).unwrap_or(1);
    let count: usize = z.space.program.blocks[bi].nodes[ni].out.resolve(h).iter().product();
    eprintln!("stage {s} block {bi} node {ni}: {count} elements at position {p_max} in tiles of {tile_len}; frame {} B", price.frame(tile_len as u32));
    let mut worst: Option<(u64, usize, kaspa_consensus_core::palw_tir_close_size_v1::PalwTirCloseReadsV1)> = None;
    for first in (0..count).step_by(tile_len) {
        let elements: Vec<usize> = (first..(first + tile_len).min(count)).collect();
        let request = PalwTirCloseRequestV1 {
            ctx: DemandContext { pos: p_max, occurrence: occ as u16 },
            target: ni as u16,
            elements: &elements,
            supplied: &[],
            range: None,
            both: false,
        };
        let (reads, _) = palw_gen_close_reads_v1(&z.space, &z.job, &z.inventory, &request, 1 << 40, &z.model).expect("the reads");
        let bytes = price.close(&reads, elements.len() as u32);
        if worst.as_ref().is_none_or(|w| bytes > w.0) {
            worst = Some((bytes, first, reads));
        }
    }
    let (bytes, first, reads) = worst.expect("a tile");
    eprintln!("worst tile starts at element {first}: priced {bytes} B");
    eprintln!("  step leaves {} ({} B), loose {}", reads.steps.len(), price.steps(&reads, false), reads.loose_steps.len());
    eprintln!("  param leaves {} + wild rows {} ({} B)", reads.params.len(), reads.wild_rows.values().map(|p| p.len()).sum::<usize>(), price.params(&reads));
    let mut by_param: BTreeMap<String, usize> = BTreeMap::new();
    for leaf in &reads.params {
        let (p, _, _, _) = z.inventory.piece_of(*leaf).unwrap();
        *by_param.entry(z.space.program.params[p as usize].name.clone()).or_default() += 1;
    }
    eprintln!("    by param: {by_param:?}");
    eprintln!("  edges {} ({} B), image tiles {}", reads.edges.len(), price.edges(&reads), reads.images.len());
    let mut by_edge: BTreeMap<u8, usize> = BTreeMap::new();
    for ((st, _, _), _) in &reads.edges {
        *by_edge.entry(*st).or_default() += 1;
    }
    eprintln!("    by upstream stage: {by_edge:?}; token read: {}", reads.token);
    // The measured close at the same node's leaves (the first leaf of the stage's last position).
    let honest = {
        let (held, _file) = held(&c);
        let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
        let ev = honest.evidence(&held);
        let mut best: Option<(usize, u64, usize, usize, usize)> = None;
        for l in honest.leaf_listing() {
            if l.lanes == 0 {
                continue;
            }
            if point_of(&c, &l) == Some((s as u8, bi as u8, ni as u16)) {
                let close = ev.cone_close(l.global, &LIMITS).expect("a close");
                let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close.clone()) }).unwrap().len();
                if best.as_ref().is_none_or(|b| bytes > b.0) {
                    best = Some((bytes, l.global, close.operands.len(), close.params.len(), close.operands.iter().filter(|o| o.coord.stage as usize != s).count()));
                }
            }
        }
        best
    };
    if let Some((bytes, leaf, operands, params, edges)) = honest {
        eprintln!("measured at its worst leaf {leaf}: {bytes} B with {operands} operand leaves ({edges} of other stages), {params} param leaves");
    }
}

/// **A dissected leaf's moves, measured**: the responder's root claim (`CourtGenRootClaimed`, signed, as its carrier holds it) and
/// the bottom (`CourtClosed` over a `GenDissection`) of the dissection played to the end — to the first and to the last child at
/// every round — the largest of them.
fn dissected_moves(
    c: &Sd3Class,
    held: &GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>,
    honest: &GenTensorWorkV1,
    ev: &kaspa_consensus_core::palw_gen_close_v1::PalwGenEvidenceV1<'_>,
    leaf: u64,
) -> (u64, u64) {
    use kaspa_consensus_core::palw_bisect::PalwBisectTurnV1;
    use kaspa_consensus_core::palw_gen_close_v1::check_gen_root_claim_v1;
    use kaspa_consensus_core::palw_state_v2::PalwConsensusObjectV2;
    use kaspa_consensus_core::palw_tir_dissect_v1::{PALW_TIR_DISSECT_OBJECT_VERSION_V1, PalwTirDissectChoiceV1, PalwTirDissectPhaseV1};
    let zero = Hash64::from_bytes([0; 64]);
    let len = |o: &PalwConsensusObjectV2| borsh::to_vec(o).unwrap().len() as u64;
    let root = ev.root_claim(leaf, &LIMITS).unwrap_or_else(|e| panic!("the root claim at leaf {leaf}: {e}"));
    let root_bytes = len(&PalwConsensusObjectV2::CourtGenRootClaimed {
        session_id: zero,
        root: Box::new(root.clone()),
        arity: 2,
        signature: vec![0; 4_627],
    }) + 64;
    let site = check_gen_root_claim_v1(&root, &held.row, &c.row.class_id, &honest.execution_root(), leaf, FORM, &LIMITS)
        .unwrap_or_else(|e| panic!("the root claim at leaf {leaf} is not admitted: {e}"));
    let mut bottom_worst = 0u64;
    for child_last in [false, true] {
        let mut phase =
            PalwTirDissectPhaseV1::open_parts(Hash64::from_bytes([7; 64]), leaf, &site, root.version, &root.elements, &root.totals, 2, 1, 100)
                .expect("the phase opens");
        let mut daa = 2;
        while phase.turn() == PalwBisectTurnV1::AwaitDisclosure {
            let round = ev.round(&phase, &LIMITS).expect("a round");
            phase.apply_round(&round, daa, 100).expect("the honest children fold");
            let child = if child_last { (round.children.len() - 1) as u8 } else { 0 };
            let choice = PalwTirDissectChoiceV1 { version: PALW_TIR_DISSECT_OBJECT_VERSION_V1, session_id: phase.session_id(), round: phase.round(), child };
            phase.apply_choice(&choice, daa + 1, 100).expect("a legal choice");
            daa += 2;
        }
        let bottom = ev.bottom(&phase, &LIMITS).expect("the bottom");
        let bytes = len(&PalwConsensusObjectV2::CourtClosed {
            session_id: zero,
            verdict: PalwCourtVerdictV2::ChallengerDefeated,
            proof: PalwCourtVerdictProofV2::GenDissection { bottom: Box::new(bottom) },
        });
        bottom_worst = bottom_worst.max(bytes);
    }
    (root_bytes, bottom_worst)
}

/// **PALW-GEN-20 by exhaustion — the exact worst close of this class's widest job**: the cone close at EVERY non-dissected step leaf of
/// the honest run (the class's canonical job is its widest: every offered job is a prefix of it), serialized as the one-move
/// accusation carries it. For a class this size the exact worst is cheaper than any bound; for a real-size class the analytic twin
/// (the PALW-TIR-38 form generalised to stages) is the tool, and this is what it is validated against. Prints the worst of every
/// commit point and of every kind and asserts every close fits one carrier. `SD3_SWEEP_STRIDE=<n>` takes every `n`-th leaf.
#[test]
#[ignore = "a cone close per leaf: PALW_SWEEP=1 cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture exhaustive"]
fn every_leaf_of_the_widest_job_has_a_cone_close_that_fits_one_carrier() {
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    let ev = honest.evidence(&held);
    let stride: usize = std::env::var("SD3_SWEEP_STRIDE").ok().and_then(|v| v.parse().ok()).unwrap_or(1);
    let leaves = honest.leaf_listing();
    let mut per_node: BTreeMap<(String, String, usize), (usize, u64)> = BTreeMap::new();
    let (mut done, mut skipped, mut worst) = (0usize, 0usize, (0usize, 0u64));
    for (n, l) in leaves.iter().enumerate() {
        if l.lanes == 0 || n % stride != 0 {
            continue;
        }
        if is_dissected(&held, &honest, l.global) {
            skipped += 1;
            continue;
        }
        let close = ev.cone_close(l.global, &LIMITS).unwrap_or_else(|e| panic!("leaf {}: {e}", l.global));
        let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close) }).unwrap().len();
        let st = &c.spec.pipeline.stages[l.stage as usize];
        let prog = &c.spec.programs[st.program as usize];
        let key = match l.kind.split_once(' ') {
            Some(("commit", rest)) => {
                let (occ, node) = rest.split_once('.').expect("occurrence.node");
                let (occ, node): (usize, usize) = (occ.parse().unwrap(), node.parse().unwrap());
                let (block, _layer) = prog.occurrences()[occ];
                (st.name.clone(), format!("{}.{} {}", prog.blocks[block as usize].name, block, node), node)
            }
            _ => (st.name.clone(), l.kind.clone(), 0),
        };
        let e = per_node.entry(key).or_insert((0, l.global));
        if bytes > e.0 {
            *e = (bytes, l.global);
        }
        if bytes > worst.0 {
            worst = (bytes, l.global);
        }
        done += 1;
        if done % 500 == 0 {
            eprintln!("  {done} leaves swept, worst so far {} B (leaf {})", worst.0, worst.1);
        }
    }
    eprintln!("  {:<14} {:<40} {:>10} {:>10}", "stage", "block.id node", "worst B", "at leaf");
    for ((stage, block, _), (bytes, leaf)) in &per_node {
        eprintln!("  {stage:<14} {block:<40} {bytes:>10} {leaf:>10}{}", if *bytes > one_move_max { "  <-- OVER" } else { "" });
    }
    eprintln!(
        "swept {done} leaves ({skipped} dissected skipped): worst {} B at leaf {} (one-move carrier {one_move_max} B)",
        worst.0, worst.1
    );
    assert!(worst.0 <= one_move_max, "a cone close of {} B at leaf {} exceeds one carrier", worst.0, worst.1);
}

/// **The price counts the committed write of the previous position, for every element of the latent a cone reads** (lane A's
/// requirement on PALW-GEN-20). The latent is a state `post` writes (NF-29): the court reads its value at the start of `p` as the
/// committed write of `p − 1` (the `StateWrite`'s commit leaf at the stage's `post` occurrence), so a cone at a position ≥ 1 that reads
/// the latent carries that leaf. For every denoiser leaf at positions 1.. whose MEASURED close carries such a leaf (`SD3_WRITE_STRIDE=<n>`
/// takes every `n`-th, default 4, and always the first and last tile of each commit point at each position): (1) every committed-write
/// leaf of the measured close is in the twin's read set of the same cone — the leaf, by its coordinate, not by a count; (2) the price of
/// the commit point is at least the measured close. A cone that reads the latent is among the sampled leaves of the sweep too; this one
/// is held to the leaf.
#[test]
#[ignore = "slow: a cone close per sampled denoiser leaf at positions >= 1: cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture committed_write"]
fn the_price_counts_the_committed_write_of_the_previous_position_for_every_element_a_cone_reads() {
    use kaspa_consensus_core::palw_gen_close_price_v1::PalwGenClassSizingV1;
    use kaspa_consensus_core::palw_step::PalwStepCoordinateV1;
    use kaspa_consensus_core::palw_tir_close_size_v1::{PalwTirClosePriceV1, PalwTirCloseRequestV1, palw_gen_close_reads_v1};
    use misaka_palw_tir::demand::DemandContext;
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let ev = honest.evidence(&held);
    let denoise = c.spec.pipeline.stages.iter().position(|st| st.name == "denoise").expect("a denoise stage");
    let space = &honest.execution.space;
    let sp = &space.stages[denoise];
    let post_occ = (sp.program.occurrences().len() - 1) as u16;
    let (write_node, _state) = *sp.info.post_writes.first().expect("the latent is written in post");
    let class = &c.declared.class;
    let tables = PalwGenClassSizingV1::new(class, &c.spec.pipeline, &c.spec.programs).expect("tables");
    let z = tables.stage(class, &c.spec.pipeline, &c.spec.programs, denoise).expect("the denoiser's sizing");
    let leaves = kaspa_consensus_core::palw_gen_artifact_v1::PalwGenInventoryIndexV1::new(&c.spec.programs).unwrap().leaf_count();
    let price = PalwTirClosePriceV1::generative(&z.space, &z.inventory, denoise, leaves, z.pricing.clone()).expect("a price");
    let (prices, _) = gate_prices(&c);
    let shape = z.space.job_shape(&z.job).expect("the job shape");
    let stride: usize = std::env::var("SD3_WRITE_STRIDE").ok().and_then(|v| v.parse().ok()).unwrap_or(4);
    // The leaves at positions >= 1, by (position, occurrence, node): their tiles in order.
    let mut by_site: BTreeMap<(u32, u16, u16), Vec<usize>> = BTreeMap::new();
    for (local, leaf) in sp.leaves().iter().enumerate() {
        if leaf.coord.pos == 0 {
            continue;
        }
        if let PalwGenLeafKindV1::Commit { occurrence, node } = leaf.coord.kind {
            by_site.entry((leaf.coord.pos, occurrence, node)).or_default().push(local);
        }
    }
    let (mut measured, mut with_write, mut leaves_checked, mut worst_margin) = (0usize, 0usize, 0usize, i64::MAX);
    let mut positions = std::collections::BTreeSet::new();
    for ((pos, occurrence, node), locals) in &by_site {
        let block = sp.occurrence_block(*occurrence).expect("an occurrence");
        let point = (denoise as u8, block, *node);
        let Some(bound) = prices.get(&point) else { continue };
        for (n, local) in locals.iter().enumerate() {
            if n % stride != 0 && n != 0 && n + 1 != locals.len() {
                continue;
            }
            let leaf = sp.leaves()[*local];
            let global = space.global_index(&leaf.coord).expect("a leaf");
            if is_dissected(&held, &honest, global) {
                continue;
            }
            let close = ev.cone_close(global, &LIMITS).unwrap_or_else(|e| panic!("denoise pos {pos} node {node} tile {n}: {e}"));
            let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close.clone()) }).unwrap().len() as u64;
            measured += 1;
            assert!(bound.close_bytes >= bytes, "denoise pos {pos} block {block} node {node}: priced {} B, measured {bytes} B", bound.close_bytes);
            worst_margin = worst_margin.min(bound.close_bytes as i64 - bytes as i64);
            // The committed writes of the previous position the close carries.
            let writes: Vec<_> = close
                .operands
                .iter()
                .filter(|o| {
                    o.coord.stage as usize == denoise
                        && o.coord.pos + 1 == *pos
                        && o.coord.kind == (PalwGenLeafKindV1::Commit { occurrence: post_occ, node: write_node })
                })
                .collect();
            if writes.is_empty() {
                continue;
            }
            with_write += 1;
            positions.insert(*pos);
            let elements: Vec<usize> = (leaf.first_element..leaf.first_element + leaf.value_count as u64).map(|e| e as usize).collect();
            let request = PalwTirCloseRequestV1 {
                ctx: DemandContext { pos: *pos, occurrence: *occurrence },
                target: *node,
                elements: &elements,
                supplied: &[],
                range: None,
                both: false,
            };
            let (reads, _) = palw_gen_close_reads_v1(&z.space, &z.job, &z.inventory, &request, 1 << 40, &z.model).expect("the reads");
            for w in &writes {
                let (call_index, position) = shape.call_position(w.coord.pos);
                let slot = z.space.node_slot(post_occ as usize, write_node).expect("the write's slot");
                let coord = PalwStepCoordinateV1 { call_index, node_slot: slot, position, tile_index: w.coord.tile };
                let index = z.space.leaf_index(&z.job, &coord).expect("the committed write is a leaf of the job");
                assert!(
                    reads.steps.contains_key(&index),
                    "denoise pos {pos} block {block} node {node} tile {n}: the close carries the committed write of position {} (tile {}), the twin's read set does not hold it",
                    w.coord.pos,
                    w.coord.tile
                );
                leaves_checked += 1;
            }
            // And the price of its leaf is in the point's price: the cone's units cost at least that leaf's opening.
            assert!(price.close(&reads, elements.len() as u32) <= bound.close_bytes, "the point's price is the worst of its tiles'");
        }
    }
    eprintln!(
        "{measured} cone closes measured at positions >= 1 ({} positions carry the latent): {with_write} carry the committed write of the previous position, {leaves_checked} such leaves each held to the twin's read set; priced >= measured everywhere (smallest margin {worst_margin} B)",
        positions.len()
    );
    assert!(with_write > 0, "no sampled cone read the latent");
    assert!(positions.len() >= 2, "the latent is read at more than one later position");
}

/// **The latent is a `post`-written state, and a cone that reads it at a later position must still close and convict** (NF-29: the
/// court reads the latent at `p` as the committed write at `p − 1`). A lie at the first leaf of position 1, 2 and 3 of the
/// denoiser's patch-embed commit points — whose cones read the latent — is convicted at its own leaf, and so is a lie at the
/// latent's own write at position 2 (the write of position 1 is what its cone reads). Before the court source knew post-written
/// states these closes were refused ("Missing: State") and nobody could be convicted there.
#[test]
fn a_lie_at_a_later_denoise_position_that_reads_the_latent_is_convicted() {
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let denoise = c.spec.pipeline.stages.iter().position(|st| st.name == "denoise").expect("a denoise stage") as u8;
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    // First leaf of each position of the denoise stage for two commit kinds: the patch embed (pre) and the latent write (post).
    let mut sites: Vec<(String, u64)> = Vec::new();
    for want in ["pre", "post"] {
        for pos in 1..=3u32 {
            let leaf = honest
                .leaf_listing()
                .into_iter()
                .find(|l| {
                    l.stage == denoise && l.pos == pos && l.lanes > 0 && l.kind.starts_with("commit") && {
                        let (occ, node) = l.kind["commit ".len()..].split_once('.').unwrap();
                        let prog = &c.spec.programs[c.spec.pipeline.stages[denoise as usize].program as usize];
                        let (block, _) = prog.occurrences()[occ.parse::<usize>().unwrap()];
                        let b = &prog.blocks[block as usize];
                        // `pre`'s patch embed reads the latent through the select; `post`'s own write is the StateWrite.
                        b.name == want && (want == "pre" || b.nodes[node.parse::<usize>().unwrap()].prim.name() == "StateWrite")
                    }
                })
                .unwrap_or_else(|| panic!("no {want} leaf at position {pos}"));
            sites.push((format!("{want} @ pos {pos}"), leaf.global));
        }
    }
    for (what, leaf) in &sites {
        let lying = honest.planted(&GenPlantV1::StepLane { leaf: *leaf, lane: 0, delta: 5 }).expect("the lie plants");
        let (proof, bytes) = cone_close(&held, &lying, *leaf).unwrap_or_else(|e| panic!("{what} (leaf {leaf}): {e}"));
        assert_eq!(verdict(&c, &lying, &proof, *leaf), Ok(PalwCourtVerdictV2::ExecutorGuilty), "{what}: convicted at its own leaf");
        assert!(bytes <= one_move_max, "{what}: {bytes} B");
        let (hp, _) = cone_close(&held, &honest, *leaf).unwrap();
        assert_eq!(verdict(&c, &honest, &hp, *leaf), Ok(PalwCourtVerdictV2::ChallengerDefeated), "{what}: honest acquitted");
        eprintln!("  convicted: {what} (leaf {leaf}), close {bytes} B");
    }
}

/// **The court battery**: a lie planted at the FIRST leaf of every commit-point kind is convicted by the cone close at that
/// leaf and an honest claim is acquitted there, the close riding the one-move accusation.
///
/// Two runs. (a) ONE lying execution carries a lie at the first leaf of every kind (the leaf values are lied about, not
/// recomputed downstream), one evidence of it and one of the honest run serve every kind. (b) Independent single lies at one
/// kind per stage block — so the conviction at a leaf is the lie's own, not a lie upstream propagating into the cone. Plus the
/// forged output digest. Slow in debug; fast optimised:
/// `cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture every_commit_point`.
#[test]
#[ignore = "slow in debug: a cone close per kind and per run"]
fn every_commit_point_kind_convicts_a_planted_lie() {
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).unwrap_or_else(|e| panic!("the worker refuses the job: {e}"));
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    let sites: Vec<(String, u64)> = kinds(&c, &honest)
        .into_iter()
        .filter(|(_, (leaf, _))| !is_dissected(&held, &honest, *leaf))
        .map(|(kind, (leaf, _))| (kind, leaf))
        .collect();
    let close_at = |ev: &kaspa_consensus_core::palw_gen_close_v1::PalwGenEvidenceV1<'_>, leaf: u64| {
        let close = ev.cone_close(leaf, &LIMITS).unwrap_or_else(|e| panic!("leaf {leaf}: {e}"));
        let proof = PalwCourtVerdictProofV2::GenCone { close: Box::new(close) };
        let bytes = borsh::to_vec(&proof).unwrap().len();
        (proof, bytes)
    };

    // (a) one lying execution, a lie at every kind's first leaf.
    // Each lie has its own size: two lies of one size on a pass-through chain (a carry copied from the leaf before it) would
    // agree with each other and convict nobody.
    let mut lying = honest.planted(&GenPlantV1::StepLane { leaf: sites[0].1, lane: 0, delta: 3 }).expect("the first lie plants");
    for (k, (_, leaf)) in sites.iter().enumerate().skip(1) {
        lying = lying.planted(&GenPlantV1::StepLane { leaf: *leaf, lane: 0, delta: 3 + k as i64 }).expect("the lie plants");
    }
    assert_ne!(lying.execution_root(), honest.execution_root());
    let (ev_lie, ev_honest) = (lying.evidence(&held), honest.evidence(&held));
    for (kind, leaf) in &sites {
        let (proof, bytes) = close_at(&ev_lie, *leaf);
        assert_eq!(
            verdict(&c, &lying, &proof, *leaf),
            Ok(PalwCourtVerdictV2::ExecutorGuilty),
            "{kind}: the cone close convicts the planted lane"
        );
        assert!(
            bytes <= one_move_max && palw_gen_one_move_proof_is_admissible_v1(&proof),
            "{kind}: the close rides the one-move accusation"
        );
        let (hp, _) = close_at(&ev_honest, *leaf);
        assert_eq!(
            verdict(&c, &honest, &hp, *leaf),
            Ok(PalwCourtVerdictV2::ChallengerDefeated),
            "{kind}: an honest claim is acquitted"
        );
        eprintln!("  (a) convicted at {kind} (leaf {leaf}), close {bytes} B");
    }

    // (b) independent single lies: one kind per stage block.
    let mut seen = std::collections::BTreeSet::new();
    let mut single = 0;
    for (kind, leaf) in &sites {
        let block = kind.rsplit_once(" / ").map(|(b, _)| b.to_string()).unwrap_or_else(|| kind.clone());
        if !seen.insert(block) {
            continue;
        }
        let one = honest.planted(&GenPlantV1::StepLane { leaf: *leaf, lane: 0, delta: 3 }).expect("the lie plants");
        let (proof, bytes) = close_at(&one.evidence(&held), *leaf);
        assert_eq!(
            verdict(&c, &one, &proof, *leaf),
            Ok(PalwCourtVerdictV2::ExecutorGuilty),
            "{kind}: a single lie is convicted at its own leaf"
        );
        single += 1;
        eprintln!("  (b) single lie convicted at {kind} (leaf {leaf}), close {bytes} B");
    }
    eprintln!("{} kinds convicted in one lying run, {single} independent single lies convicted", sites.len());

    // The forged output digest: the step tree honest, the claimed canonical output not its own.
    let lying_output = honest.planted(&GenPlantV1::OutputLane { lane: 0, delta: 1 }).expect("the output lie plants");
    assert_ne!(lying_output.execution_root(), honest.execution_root());
}

/// `PALW_GEN_DRILL_OUT=<dir> cargo test -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture`: the class as a
/// `PALWTIR2` container beside the drill's other classes, with the manifest entry the harness reads (Plan A's input).
#[test]
#[ignore = "writes the SD3 class's artifact: PALW_GEN_DRILL_OUT=<dir>"]
fn write_the_sd3_class() {
    let Some(c) = sd3_class() else { return };
    let dir = PathBuf::from(std::env::var_os("PALW_GEN_DRILL_OUT").expect("set PALW_GEN_DRILL_OUT to a directory"));
    std::fs::create_dir_all(&dir).expect("the output directory");
    let admitted = c.declared.admission.as_ref().unwrap_or_else(|why| panic!("the registration gate refuses the class: {why}"));
    let file = dir.join("sd3-tiny.class.palwtir2");
    let digest =
        gen_write_declared_container_v1(&file, &c.declared, &c.weights, "{\"model_id\":\"palw-fixture/sd3-tiny\"}".to_string())
            .expect("the container");
    let bytes = std::fs::metadata(&file).expect("written").len();
    let (held, _guard) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let capture = GenTensorCaptureV1::of(&honest).expect("a capture");
    let material = misaka_palw_base0::gen_tensor_worker::gen_tensor_material_encode_v1(&capture);
    let entry = serde_json::json!({
        "name": "sd3-tiny",
        "model_id": "palw-fixture/sd3-tiny",
        "file": file.file_name().unwrap().to_string_lossy(),
        "bytes": bytes,
        "file_digest": digest.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "class_id": c.row.class_id.to_string(),
        "artifact_root": c.row.artifact_root.to_string(),
        "profile": format!("{:?}", c.declared.class.profile),
        "canonical_step_leaves": admitted.entry.canonical_step_leaf_count,
        "max_step_leaves": admitted.entry.max_step_leaf_count,
        "sample_job_step_leaves": honest.execution.space.leaf_count(),
        "sample_material_bytes": material.len(),
        "gen_claim_request_template": {
            "profile": "image",
            "anchor_block": "<128 hex: a recent block of the chain>",
            "anchor_daa": "<its DAA score>",
            "job_nonce": "<64 hex: unique per claim>",
            "seed": "<64 hex>",
            "privacy": "public",
            "prompt_token_ids": c.ids,
            "steps": COUNTS[COUNTS.len() - 1],
            "guidance_q": 0,
            "image_index": 0,
            "width": IMAGE_HW,
            "height": IMAGE_HW,
        },
    });
    std::fs::write(dir.join("sd3-tiny.json"), serde_json::to_string_pretty(&entry).unwrap()).expect("the manifest entry");
    eprintln!("wrote {} ({bytes} bytes), class {}", file.display(), c.row.class_id);
}
