//! **The reduced SD3 / MMDiT pipeline as a registered generative class** (RFC-0003 activation step 6): the gate, the
//! container, a job, and the court battery over the lowered programs.
//!
//! The fixture is the lowerer's (`misaka_palw_tir_lower::diffusion::fixture::build_sd3_tiny`, generated by
//! `tools/gen_diffusers_sd3_fixture.py`); a checkout without it skips with a line saying so. The battery plants a lie
//! (`GenPlantV1`, what `misaka palw gen-claim --plant` commits) at the FIRST leaf of every commit-point KIND of the
//! class — (stage, block, primitive), and the `Fixed` state checkpoints — and requires the cone close at that leaf to
//! convict it, the honest run to be acquitted at the same leaf, and the close to fit the one-move carrier
//! (PALW-GEN-21). It also plants the cases the RFC names: a lie at the latent's first position (the leaf whose cone reads
//! the noise: forged noise), at the denoiser's first carry (the leaf whose cone reads the stage edge: forged edge), a
//! forged output digest (the output close), and a lane outside its node's proven interval (PALW-TIR-33, G21).

use kaspa_consensus_core::config::params::{ForkActivation, Params, palw_t12_shipped_params};
use kaspa_consensus_core::palw_court_v2::{PalwCourtV2Error, PalwCourtVerdictProofV2, palw_gen_close_verdict_for_row_v1};
use kaspa_consensus_core::palw_freeprompt_v3::{PALW_FP_PRIVACY_PUBLIC_DA, PALW_FP_PROMPT_MODE_USER};
use kaspa_consensus_core::palw_gen_class_v1::*;
use kaspa_consensus_core::palw_gen_job_v1::*;
use kaspa_consensus_core::palw_gen_one_move_v1::{palw_gen_one_move_max_proof_bytes_v1, palw_gen_one_move_proof_is_admissible_v1};
use kaspa_consensus_core::palw_gen_step_v1::PalwGenLeafKindV1;
use kaspa_consensus_core::palw_gen_v1::{PALW_DRILL_GEN_V1_ENTRY, PalwGenProfileV1};
use kaspa_consensus_core::palw_held_close_v1::PALW_HELD_CLOSE_CHUNKS_ENTRY_V1;
use kaspa_consensus_core::palw_mode_v2::PalwConsensusMode;
use kaspa_consensus_core::palw_prompt_ids_v1::{PalwPromptIdsFormV1, prompt_token_ids_commitment_v1};
use kaspa_consensus_core::palw_state_v2::{PALW_OBJECT_CHUNK_MAX_BYTES, PalwCourtVerdictV2};
use kaspa_consensus_core::palw_tir_v1::PALW_T12_TIR_V1_ENTRY;
use kaspa_consensus_core::tx::{TransactionId, TransactionOutpoint};
use kaspa_hashes::Hash64;
use misaka_palw_base0::gen_tensor_worker::{GenPlantV1, GenTensorCaptureV1, GenTensorWorkV1, gen_tensor_court_candidates_v1};
use misaka_palw_base0::gen_worker::{GenCourtMoveV1, GenHeldClassV1};
use misaka_palw_gen::OutputSpecV1;
use misaka_palw_sdk::gen_class::*;
use misaka_palw_tir::demand::DemandLimits;
use misaka_palw_tir::interp::ParamSource;
use misaka_palw_tir::pipeline::PipelineParams;
use misaka_palw_tir_lower::diffusion::fixture::{COUNTS, L, build_sd3_tiny, fixture};
use std::collections::BTreeMap;
use std::path::PathBuf;

const FORM: PalwPromptIdsFormV1 = PalwPromptIdsFormV1::Flat;
const LIMITS: DemandLimits = DemandLimits { max_elements: 1 << 20, max_terms: 1 << 24 };
const IMAGE_HW: u32 = 16;
/// The layout's tile: step-leaf lanes and weight rows per tile (`SD3_TILE=<n>` overrides, for the sweep).
const TILE_LEN: u32 = 16;

struct Weights(Vec<Box<dyn ParamSource + Send + Sync>>);

impl PipelineParams for Weights {
    fn params(&self, program: u16) -> &dyn ParamSource {
        self.0[program as usize].as_ref()
    }
}

fn all_armed() -> Params {
    let mut p = palw_t12_shipped_params();
    (PALW_T12_TIR_V1_ENTRY.set)(&mut p, Some(ForkActivation::new(1)));
    (PALW_DRILL_GEN_V1_ENTRY.set)(&mut p, Some(ForkActivation::new(1)));
    (PALW_HELD_CLOSE_CHUNKS_ENTRY_V1.set)(&mut p, Some(ForkActivation::new(1)));
    p
}

fn court() -> kaspa_consensus_core::palw_mode_v2::PalwCourtParamsV2 {
    match &palw_t12_shipped_params().palw_consensus_mode {
        PalwConsensusMode::ConsensusV2(b) => b.court.clone(),
        _ => unreachable!("testnet-12 runs V2"),
    }
}

struct Sd3Class {
    weights: Weights,
    declared: GenDeclaredV1,
    row: PalwGenClassRecordV1,
    spec: GenClassSpecV1,
    job: PalwGenJobV1,
    ids: Vec<u32>,
}

fn sd3_class() -> Option<Sd3Class> {
    let dir = fixture()?;
    let fx = build_sd3_tiny(&dir).expect("the fixture lowers");
    let pipe = &fx.pipeline;
    let weights = Weights(pipe.params.iter().cloned().map(|p| Box::new(p) as Box<dyn ParamSource + Send + Sync>).collect());
    // The steps scalar is the step count's POSITION among the offered counts (the gate says so).
    let steps_scalar = PalwGenScalarOfferV1 { lo: 0, hi: COUNTS.len() as i64 - 1 };
    let sampler_id = Hash64::from_bytes([0x5D; 64]);
    let spec = GenClassSpecV1 {
        profile: PalwGenProfileV1::Image,
        pipeline: pipe.pipeline.clone(),
        programs: pipe.programs.clone(),
        tokenizer_id: Hash64::from_bytes([0x73; 64]),
        output: OutputSpecV1::image_rgb8(IMAGE_HW, IMAGE_HW),
        offers: PalwGenOffersV1 {
            steps: COUNTS.to_vec(),
            profile: PalwGenProfileOffersV1::Image(PalwGenImageOffersV1 { sampler_id, guidance: None, steps_scalar: Some(0) }),
            scalars: vec![steps_scalar],
            max_prompt_tokens: (L - 2) as u32,
            max_negative_tokens: 0,
            images: vec![],
            max_source_tokens: 0,
            forced_prompt_prefix: vec![],
            source_token_floor: 0,
        },
    };
    let params = all_armed();
    let PalwConsensusMode::ConsensusV2(bundle) = &params.palw_consensus_mode else { panic!("testnet-12 is ConsensusV2") };
    let declared = gen_declare_layout_v1(
        &params,
        bundle,
        &spec,
        &weights,
        // `tile_len` is the lanes of a step leaf AND the rows of a weight tile: every axis-0 row of a param is its own artifact leaf
        // with its own Merkle path (~1.1 KB), so a cone of a `T`-lane output tile opens `T` rows — 16, not 64 (64 rows is 70 KB).
        &GenLayoutChoiceV1 { tile_len: TILE_LEN, output_tile: None, h_chunk: 16, checkpoint_interval: 1 },
    )
    .unwrap_or_else(|e| panic!("declare: {e}"));
    let row = declared.row.clone().expect("the class derives a registry row");
    let ids = vec![5, 9, 13];
    let steps = COUNTS[COUNTS.len() - 1] as u16;
    let job = PalwGenJobV1 {
        version: PALW_GEN_JOB_VERSION_V1,
        envelope: PalwJobEnvelopeV1 {
            network_domain: Hash64::from_bytes([0xD0; 64]),
            class_id: row.class_id,
            executor_bond: TransactionOutpoint::new(TransactionId::from_bytes([7; 64]), 0),
            executor_pubkey: vec![1; 8],
            operator_id: Hash64::from_bytes([2; 64]),
            anchor_block: Hash64::from_bytes([3; 64]),
            anchor_daa: 100,
            job_nonce: [4; 32],
            privacy_mode: PALW_FP_PRIVACY_PUBLIC_DA,
            prompt_mode: PALW_FP_PROMPT_MODE_USER,
        },
        seed: [0x33; 32],
        body: PalwGenBodyV1::Image(PalwGenImageBodyV1 {
            prompt_token_ids_hash: prompt_token_ids_commitment_v1(FORM, &ids).unwrap(),
            prompt_tokens: ids.len() as u32,
            negative_token_ids_hash: Hash64::default(),
            negative_tokens: 0,
            guidance_q: 0,
            image_index: 0,
            sampler_id,
            steps,
            width: IMAGE_HW as u16,
            height: IMAGE_HW as u16,
            output: misaka_palw_gen::OutputKindV1::ImageRgb8.tag(),
        }),
    };
    Some(Sd3Class { weights, declared, row, spec, job, ids })
}

struct Guard(PathBuf);
impl Drop for Guard {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

fn held(c: &Sd3Class) -> (GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>, Guard) {
    // A path of its own per call: the container is read from disk for as long as the class is held, and two tests of this file
    // run at once (and the one that ends first deletes its file) — a shared name made the longer one read a vanished container
    // ("no tensor supplied").
    static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let path = std::env::temp_dir()
        .join(format!("misaka-gen-sd3-{}-{}.palwtir2", std::process::id(), NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed)));
    let guard = Guard(path.clone());
    gen_write_declared_container_v1(&path, &c.declared, &c.weights, "{\"model_id\":\"palw-fixture/sd3-tiny\"}".to_string())
        .expect("the container");
    (GenHeldClassV1::hold_container(c.row.clone(), &path).expect("the worker holds the class"), guard)
}

fn cone_close(
    held: &GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>,
    accused: &GenTensorWorkV1,
    leaf: u64,
) -> Result<(PalwCourtVerdictProofV2, usize), String> {
    let moves = gen_tensor_court_candidates_v1(held, accused, leaf, true, &LIMITS);
    let (_, cone) = moves.iter().find(|(n, _)| *n == "cone").ok_or("no cone close at this leaf")?;
    match cone.clone()? {
        GenCourtMoveV1::Close(proof) => {
            let bytes = borsh::to_vec(&proof).map_err(|e| e.to_string())?.len();
            Ok((proof, bytes))
        }
        _ => Err("not a close".to_string()),
    }
}

fn verdict(
    c: &Sd3Class,
    who: &GenTensorWorkV1,
    proof: &PalwCourtVerdictProofV2,
    leaf: u64,
) -> Result<PalwCourtVerdictV2, PalwCourtV2Error> {
    palw_gen_close_verdict_for_row_v1(&c.row, &c.row.class_id, &who.execution_root(), proof, Some(leaf), &court(), FORM, false)
}

/// The leaves of the honest run, grouped by KIND: (stage name, block name, primitive) for a commit, the state's name for a
/// checkpoint — each with its first leaf (a leaf with lanes) and its count.
fn kinds(c: &Sd3Class, honest: &GenTensorWorkV1) -> BTreeMap<String, (u64, usize)> {
    let mut kinds: BTreeMap<String, (u64, usize)> = BTreeMap::new();
    for l in honest.leaf_listing() {
        if l.lanes == 0 {
            continue;
        }
        let st = &c.spec.pipeline.stages[l.stage as usize];
        let prog = &c.spec.programs[st.program as usize];
        let kind = match l.kind.split_once(' ') {
            Some(("commit", rest)) => {
                let (occ, node) = rest.split_once('.').expect("occurrence.node");
                let (occ, node): (usize, usize) = (occ.parse().unwrap(), node.parse().unwrap());
                let (block, _layer) = prog.occurrences()[occ];
                let b = &prog.blocks[block as usize];
                format!("{} / {} / {}", st.name, b.name, b.nodes[node].prim.name())
            }
            _ => format!("{} / {}", st.name, l.kind),
        };
        let e = kinds.entry(kind).or_insert((l.global, 0));
        e.1 += 1;
    }
    kinds
}

/// Is global leaf `index` a dissected commit point of the class (a fused attention site: a lie there is a held
/// dissection's, not a cone close's)?
fn is_dissected(held: &GenHeldClassV1<misaka_palw_tir_artifact::PalwTirContainerV2>, honest: &GenTensorWorkV1, index: u64) -> bool {
    let (stage, local) = honest.execution.space.locate(index).expect("a leaf of the run");
    let sp = &honest.execution.space.stages[stage as usize];
    match sp.leaves()[local as usize].coord.kind {
        PalwGenLeafKindV1::Commit { occurrence, node } => {
            sp.occurrence_block(occurrence).is_some_and(|b| held.row.dissected.contains(&(stage, b, node)))
        }
        PalwGenLeafKindV1::State { .. } => false,
    }
}

/// **The cone-close table**: every commit-point kind of the class, its first leaf's cone close, in bytes and against
/// the one-move carrier (PALW-GEN-21). One evidence of the honest run serves them all (the structure of a cone close does
/// not depend on a lie). A class must be convictable by the one-move path alone: every kind but the dissected ones fits.
#[test]
fn the_sd3_class_passes_the_gate_and_every_cone_close_fits_one_carrier() {
    let Some(c) = sd3_class() else { return };
    let admitted = c.declared.admission.as_ref().unwrap_or_else(|why| panic!("the registration gate refuses the SD3 class: {why}"));
    eprintln!(
        "sd3-tiny: class {} — {} canonical step leaves, {} at the widest job",
        c.row.class_id, admitted.entry.canonical_step_leaf_count, admitted.entry.max_step_leaf_count
    );
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).unwrap_or_else(|e| panic!("the worker refuses the job: {e}"));
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    assert!(one_move_max < PALW_OBJECT_CHUNK_MAX_BYTES);
    let ev = honest.evidence(&held);
    let table = kinds(&c, &honest);
    eprintln!("{} step leaves in {} commit-point kinds (one-move carrier {one_move_max} B)", honest.leaf_listing().len(), table.len());
    eprintln!("  {:<62} {:>6} {:>9} {:>9}", "kind (stage / block / primitive)", "leaves", "close B", "margin B");
    let (mut over, mut dissected, mut worst) = (Vec::new(), Vec::new(), (0usize, String::new()));
    for (kind, (leaf, count)) in &table {
        if is_dissected(&held, &honest, *leaf) {
            dissected.push(kind.clone());
            eprintln!("  {kind:<62} {count:>6} {:>9} {:>9}", "dissected", "-");
            continue;
        }
        let close = ev.cone_close(*leaf, &LIMITS).unwrap_or_else(|e| panic!("{kind} (leaf {leaf}): {e}"));
        let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close) }).unwrap().len();
        let margin = one_move_max as i64 - bytes as i64;
        eprintln!("  {kind:<62} {count:>6} {bytes:>9} {margin:>9}{}", if margin < 0 { "  <-- OVER" } else { "" });
        if margin < 0 {
            over.push((kind.clone(), bytes));
        }
        if bytes > worst.0 {
            worst = (bytes, kind.clone());
        }
    }
    eprintln!("largest cone close: {} B ({}); {} dissected kinds: {dissected:?}", worst.0, worst.1, dissected.len());
    assert!(over.is_empty(), "kinds whose cone close exceeds the one-move carrier: {over:?}");
}

/// What one cone close is made of, for the kinds the table flags: the frame, the operands (step leaves it opens, each with
/// its path) and the params (artifact openings). `SD3_KIND=<substring of a kind>` picks the kinds (default: none).
#[test]
#[ignore = "diagnostic: SD3_KIND=<substring> cargo test -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture breakdown"]
fn breakdown_of_the_close_at_a_kind() {
    let Some(c) = sd3_class() else { return };
    let want = std::env::var("SD3_KIND").unwrap_or_default();
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let ev = honest.evidence(&held);
    for (kind, (leaf, _)) in kinds(&c, &honest) {
        if want.is_empty() || !kind.contains(&want) || is_dissected(&held, &honest, leaf) {
            continue;
        }
        let close = ev.cone_close(leaf, &LIMITS).expect("a cone close");
        let operands: usize = close.operands.iter().map(|o| borsh::to_vec(o).unwrap().len()).sum();
        let params: Vec<usize> = close.params.iter().map(|p| borsh::to_vec(p).unwrap().len()).collect();
        let disputed = borsh::to_vec(&close.disputed).unwrap().len();
        let total = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close.clone()) }).unwrap().len();
        eprintln!(
            "{kind} (leaf {leaf}): total {total} B = disputed {disputed} + {} operands {operands} + {} param openings {} (largest {:?}) + frame/binding {}",
            close.operands.len(),
            params.len(),
            params.iter().sum::<usize>(),
            params.iter().max(),
            total - disputed - operands - params.iter().sum::<usize>()
        );
        for o in close.operands.iter().take(6) {
            eprintln!("    operand {:?}: {} lanes B, path {}", o.coord, o.lanes_le.len(), o.path.len());
        }
    }
}

/// **PALW-GEN-20**: the PALW-TIR-38 twin over every stage's version-1 view with the param openings priced as the generative close
/// carries them (`PerLeaf`: one opening, one full path per axis-0 row) at the CLASS's inventory depth, beside the worker's MEASURED
/// close — the largest of the first, middle and last leaf of every commit POINT (stage, block, node). The twin is a sound bound only
/// where it is at least the measurement: this prints both per point, the ratio, and the points where it is not.
#[test]
#[ignore = "slow: three worker cone closes per commit point; prints the twin beside the measurement"]
fn the_close_twin_bounds_the_measured_closes_per_commit_point() {
    use kaspa_consensus_core::palw_tir_close_size_v1::{
        PalwTirCloseSizingV1, PalwTirParamFormV1, palw_tir_worst_closes_work_at_depth_v1,
    };
    use kaspa_consensus_core::palw_tir_court_v1::PalwTirInventoryIndexV1;
    use kaspa_consensus_core::palw_tir_step_v1::PalwTirStepSpaceV1;
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let ev = honest.evidence(&held);
    let class_leaves = kaspa_consensus_core::palw_gen_artifact_v1::palw_gen_inventory_operands_v1(&c.spec.programs, &c.weights)
        .expect("the class's inventory")
        .len() as u32;
    // The leaves of every (stage, block, node), in order.
    let mut by_node: BTreeMap<(u8, u8, u16), Vec<u64>> = BTreeMap::new();
    for l in honest.leaf_listing() {
        if l.lanes == 0 {
            continue;
        }
        if let Some(("commit", rest)) = l.kind.split_once(' ') {
            let (occ, node) = rest.split_once('.').expect("occurrence.node");
            let (occ, node): (usize, u16) = (occ.parse().unwrap(), node.parse().unwrap());
            let st = &c.spec.pipeline.stages[l.stage as usize];
            let (block, _layer) = c.spec.programs[st.program as usize].occurrences()[occ];
            by_node.entry((l.stage, block, node)).or_default().push(l.global);
        }
    }
    let (mut unsound, mut points, mut worst_twin, mut worst_measured) = (Vec::new(), 0usize, 0u64, 0u64);
    eprintln!(
        "class inventory: {class_leaves} leaves; {:<14} {:>5} {:>5} {:>10} {:>10} {:>7}",
        "stage", "block", "node", "measured B", "twin B", "ratio"
    );
    for (s, st) in c.spec.pipeline.stages.iter().enumerate() {
        let view = c.spec.programs[st.program as usize].v1_view();
        let info = misaka_palw_tir::validate::validate(&view).expect("the view validates");
        let space = PalwTirStepSpaceV1::from_program(view.clone(), info, c.declared.class.layouts[s].clone()).expect("the step space");
        let inventory = PalwTirInventoryIndexV1::new(&view).expect("an inventory");
        let ctx = twin_ctx(st.max_trip);
        let sizing = PalwTirCloseSizingV1 { form: PalwTirParamFormV1::PerLeaf, court: true, cap: 1 << 40, stop_above: None };
        let (bounds, _) = palw_tir_worst_closes_work_at_depth_v1(&space, &inventory, &ctx, &sizing, Some(class_leaves))
            .unwrap_or_else(|e| panic!("stage {s}: the twin refuses: {e}"));
        for b in &bounds {
            worst_twin = worst_twin.max(b.close_bytes);
            let Some(leaves) = by_node.get(&(s as u8, b.block, b.node)) else { continue };
            if is_dissected(&held, &honest, leaves[0]) {
                eprintln!("  {:<14} {:>5} {:>5} {:>10} {:>10} {:>7}", st.name, b.block, b.node, "dissected", b.close_bytes, "-");
                continue;
            }
            let sample = [leaves[0], leaves[leaves.len() / 2], leaves[leaves.len() - 1]];
            let measured = sample
                .iter()
                .map(|leaf| {
                    let close = ev
                        .cone_close(*leaf, &LIMITS)
                        .unwrap_or_else(|e| panic!("stage {s} block {} node {} leaf {leaf}: {e}", b.block, b.node));
                    borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close) }).unwrap().len() as u64
                })
                .max()
                .unwrap();
            worst_measured = worst_measured.max(measured);
            points += 1;
            let ratio = b.close_bytes as f64 / measured as f64;
            eprintln!(
                "  {:<14} {:>5} {:>5} {:>10} {:>10} {:>7.2}{}",
                st.name,
                b.block,
                b.node,
                measured,
                b.close_bytes,
                ratio,
                if ratio < 1.0 { "  <-- UNDER" } else { "" }
            );
            if b.close_bytes < measured {
                unsound.push((st.name.clone(), b.block, b.node, measured, b.close_bytes));
            }
        }
    }
    eprintln!(
        "{points} commit points measured; largest measured {worst_measured} B, twin's largest bound {worst_twin} B; the twin is below the measurement at {}: {unsound:?}",
        unsound.len()
    );
}

/// **PALW-GEN-20 by exhaustion — the exact worst close of this class's widest job**: the cone close at EVERY non-dissected step leaf of
/// the honest run (the class's canonical job is its widest: every offered job is a prefix of it), serialized as the one-move
/// accusation carries it. For a class this size the exact worst is cheaper than any bound; for a real-size class the analytic twin
/// (the PALW-TIR-38 form generalised to stages) is the tool, and this is what it is validated against. Prints the worst of every
/// commit point and of every kind and asserts every close fits one carrier. `SD3_SWEEP_STRIDE=<n>` takes every `n`-th leaf.
#[test]
#[ignore = "a cone close per leaf: PALW_SWEEP=1 cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture exhaustive"]
fn every_leaf_of_the_widest_job_has_a_cone_close_that_fits_one_carrier() {
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    let ev = honest.evidence(&held);
    let stride: usize = std::env::var("SD3_SWEEP_STRIDE").ok().and_then(|v| v.parse().ok()).unwrap_or(1);
    let leaves = honest.leaf_listing();
    let mut per_node: BTreeMap<(String, String, usize), (usize, u64)> = BTreeMap::new();
    let (mut done, mut skipped, mut worst) = (0usize, 0usize, (0usize, 0u64));
    for (n, l) in leaves.iter().enumerate() {
        if l.lanes == 0 || n % stride != 0 {
            continue;
        }
        if is_dissected(&held, &honest, l.global) {
            skipped += 1;
            continue;
        }
        let close = ev.cone_close(l.global, &LIMITS).unwrap_or_else(|e| panic!("leaf {}: {e}", l.global));
        let bytes = borsh::to_vec(&PalwCourtVerdictProofV2::GenCone { close: Box::new(close) }).unwrap().len();
        let st = &c.spec.pipeline.stages[l.stage as usize];
        let prog = &c.spec.programs[st.program as usize];
        let key = match l.kind.split_once(' ') {
            Some(("commit", rest)) => {
                let (occ, node) = rest.split_once('.').expect("occurrence.node");
                let (occ, node): (usize, usize) = (occ.parse().unwrap(), node.parse().unwrap());
                let (block, _layer) = prog.occurrences()[occ];
                (st.name.clone(), format!("{}.{} {}", prog.blocks[block as usize].name, block, node), node)
            }
            _ => (st.name.clone(), l.kind.clone(), 0),
        };
        let e = per_node.entry(key).or_insert((0, l.global));
        if bytes > e.0 {
            *e = (bytes, l.global);
        }
        if bytes > worst.0 {
            worst = (bytes, l.global);
        }
        done += 1;
        if done % 500 == 0 {
            eprintln!("  {done} leaves swept, worst so far {} B (leaf {})", worst.0, worst.1);
        }
    }
    eprintln!("  {:<14} {:<40} {:>10} {:>10}", "stage", "block.id node", "worst B", "at leaf");
    for ((stage, block, _), (bytes, leaf)) in &per_node {
        eprintln!("  {stage:<14} {block:<40} {bytes:>10} {leaf:>10}{}", if *bytes > one_move_max { "  <-- OVER" } else { "" });
    }
    eprintln!(
        "swept {done} leaves ({skipped} dissected skipped): worst {} B at leaf {} (one-move carrier {one_move_max} B)",
        worst.0, worst.1
    );
    assert!(worst.0 <= one_move_max, "a cone close of {} B at leaf {} exceeds one carrier", worst.0, worst.1);
}

fn twin_ctx(positions: u32) -> kaspa_consensus_core::palw_v2::PalwJobContextV2 {
    kaspa_consensus_core::palw_v2::PalwJobContextV2 {
        version: 2,
        network_id: vec![0; 8],
        job_id: Hash64::default(),
        job_nullifier: Hash64::default(),
        assignment_id: Hash64::default(),
        execution_seed: [0; 32],
        model_profile_id: Hash64::default(),
        runtime_manifest_hash: Hash64::default(),
        runtime_class_id: Hash64::default(),
        shape_profile_id: Hash64::default(),
        trace_scheme_id: Hash64::default(),
        cu_ruleset_id: Hash64::default(),
        tokenizer_id: Hash64::default(),
        prompt_token_ids_hash: Hash64::default(),
        declared_prefill_tokens: positions,
        exact_decode_tokens: 1,
        max_context_tokens: positions,
    }
}

/// **The latent is a `post`-written state, and a cone that reads it at a later position must still close and convict** (NF-29: the
/// court reads the latent at `p` as the committed write at `p − 1`). A lie at the first leaf of position 1, 2 and 3 of the
/// denoiser's patch-embed commit points — whose cones read the latent — is convicted at its own leaf, and so is a lie at the
/// latent's own write at position 2 (the write of position 1 is what its cone reads). Before the court source knew post-written
/// states these closes were refused ("Missing: State") and nobody could be convicted there.
#[test]
fn a_lie_at_a_later_denoise_position_that_reads_the_latent_is_convicted() {
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let denoise = c.spec.pipeline.stages.iter().position(|st| st.name == "denoise").expect("a denoise stage") as u8;
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    // First leaf of each position of the denoise stage for two commit kinds: the patch embed (pre) and the latent write (post).
    let mut sites: Vec<(String, u64)> = Vec::new();
    for want in ["pre", "post"] {
        for pos in 1..=3u32 {
            let leaf = honest
                .leaf_listing()
                .into_iter()
                .find(|l| {
                    l.stage == denoise && l.pos == pos && l.lanes > 0 && l.kind.starts_with("commit") && {
                        let (occ, node) = l.kind["commit ".len()..].split_once('.').unwrap();
                        let prog = &c.spec.programs[c.spec.pipeline.stages[denoise as usize].program as usize];
                        let (block, _) = prog.occurrences()[occ.parse::<usize>().unwrap()];
                        let b = &prog.blocks[block as usize];
                        // `pre`'s patch embed reads the latent through the select; `post`'s own write is the StateWrite.
                        b.name == want && (want == "pre" || b.nodes[node.parse::<usize>().unwrap()].prim.name() == "StateWrite")
                    }
                })
                .unwrap_or_else(|| panic!("no {want} leaf at position {pos}"));
            sites.push((format!("{want} @ pos {pos}"), leaf.global));
        }
    }
    for (what, leaf) in &sites {
        let lying = honest.planted(&GenPlantV1::StepLane { leaf: *leaf, lane: 0, delta: 5 }).expect("the lie plants");
        let (proof, bytes) = cone_close(&held, &lying, *leaf).unwrap_or_else(|e| panic!("{what} (leaf {leaf}): {e}"));
        assert_eq!(verdict(&c, &lying, &proof, *leaf), Ok(PalwCourtVerdictV2::ExecutorGuilty), "{what}: convicted at its own leaf");
        assert!(bytes <= one_move_max, "{what}: {bytes} B");
        let (hp, _) = cone_close(&held, &honest, *leaf).unwrap();
        assert_eq!(verdict(&c, &honest, &hp, *leaf), Ok(PalwCourtVerdictV2::ChallengerDefeated), "{what}: honest acquitted");
        eprintln!("  convicted: {what} (leaf {leaf}), close {bytes} B");
    }
}

/// **The court battery**: a lie planted at the FIRST leaf of every commit-point kind is convicted by the cone close at that
/// leaf and an honest claim is acquitted there, the close riding the one-move accusation.
///
/// Two runs. (a) ONE lying execution carries a lie at the first leaf of every kind (the leaf values are lied about, not
/// recomputed downstream), one evidence of it and one of the honest run serve every kind. (b) Independent single lies at one
/// kind per stage block — so the conviction at a leaf is the lie's own, not a lie upstream propagating into the cone. Plus the
/// forged output digest. Slow in debug; fast optimised:
/// `cargo test --config profile.dev.opt-level=2 -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture every_commit_point`.
#[test]
#[ignore = "slow in debug: a cone close per kind and per run"]
fn every_commit_point_kind_convicts_a_planted_lie() {
    let Some(c) = sd3_class() else { return };
    let (held, _file) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).unwrap_or_else(|e| panic!("the worker refuses the job: {e}"));
    let one_move_max = palw_gen_one_move_max_proof_bytes_v1() as usize;
    let sites: Vec<(String, u64)> = kinds(&c, &honest)
        .into_iter()
        .filter(|(_, (leaf, _))| !is_dissected(&held, &honest, *leaf))
        .map(|(kind, (leaf, _))| (kind, leaf))
        .collect();
    let close_at = |ev: &kaspa_consensus_core::palw_gen_close_v1::PalwGenEvidenceV1<'_>, leaf: u64| {
        let close = ev.cone_close(leaf, &LIMITS).unwrap_or_else(|e| panic!("leaf {leaf}: {e}"));
        let proof = PalwCourtVerdictProofV2::GenCone { close: Box::new(close) };
        let bytes = borsh::to_vec(&proof).unwrap().len();
        (proof, bytes)
    };

    // (a) one lying execution, a lie at every kind's first leaf.
    // Each lie has its own size: two lies of one size on a pass-through chain (a carry copied from the leaf before it) would
    // agree with each other and convict nobody.
    let mut lying = honest.planted(&GenPlantV1::StepLane { leaf: sites[0].1, lane: 0, delta: 3 }).expect("the first lie plants");
    for (k, (_, leaf)) in sites.iter().enumerate().skip(1) {
        lying = lying.planted(&GenPlantV1::StepLane { leaf: *leaf, lane: 0, delta: 3 + k as i64 }).expect("the lie plants");
    }
    assert_ne!(lying.execution_root(), honest.execution_root());
    let (ev_lie, ev_honest) = (lying.evidence(&held), honest.evidence(&held));
    for (kind, leaf) in &sites {
        let (proof, bytes) = close_at(&ev_lie, *leaf);
        assert_eq!(
            verdict(&c, &lying, &proof, *leaf),
            Ok(PalwCourtVerdictV2::ExecutorGuilty),
            "{kind}: the cone close convicts the planted lane"
        );
        assert!(
            bytes <= one_move_max && palw_gen_one_move_proof_is_admissible_v1(&proof),
            "{kind}: the close rides the one-move accusation"
        );
        let (hp, _) = close_at(&ev_honest, *leaf);
        assert_eq!(
            verdict(&c, &honest, &hp, *leaf),
            Ok(PalwCourtVerdictV2::ChallengerDefeated),
            "{kind}: an honest claim is acquitted"
        );
        eprintln!("  (a) convicted at {kind} (leaf {leaf}), close {bytes} B");
    }

    // (b) independent single lies: one kind per stage block.
    let mut seen = std::collections::BTreeSet::new();
    let mut single = 0;
    for (kind, leaf) in &sites {
        let block = kind.rsplit_once(" / ").map(|(b, _)| b.to_string()).unwrap_or_else(|| kind.clone());
        if !seen.insert(block) {
            continue;
        }
        let one = honest.planted(&GenPlantV1::StepLane { leaf: *leaf, lane: 0, delta: 3 }).expect("the lie plants");
        let (proof, bytes) = close_at(&one.evidence(&held), *leaf);
        assert_eq!(
            verdict(&c, &one, &proof, *leaf),
            Ok(PalwCourtVerdictV2::ExecutorGuilty),
            "{kind}: a single lie is convicted at its own leaf"
        );
        single += 1;
        eprintln!("  (b) single lie convicted at {kind} (leaf {leaf}), close {bytes} B");
    }
    eprintln!("{} kinds convicted in one lying run, {single} independent single lies convicted", sites.len());

    // The forged output digest: the step tree honest, the claimed canonical output not its own.
    let lying_output = honest.planted(&GenPlantV1::OutputLane { lane: 0, delta: 1 }).expect("the output lie plants");
    assert_ne!(lying_output.execution_root(), honest.execution_root());
}

/// `PALW_GEN_DRILL_OUT=<dir> cargo test -p misaka-palw-sdk --test gen_sd3_class -- --ignored --nocapture`: the class as a
/// `PALWTIR2` container beside the drill's other classes, with the manifest entry the harness reads (Plan A's input).
#[test]
#[ignore = "writes the SD3 class's artifact: PALW_GEN_DRILL_OUT=<dir>"]
fn write_the_sd3_class() {
    let Some(c) = sd3_class() else { return };
    let dir = PathBuf::from(std::env::var_os("PALW_GEN_DRILL_OUT").expect("set PALW_GEN_DRILL_OUT to a directory"));
    std::fs::create_dir_all(&dir).expect("the output directory");
    let admitted = c.declared.admission.as_ref().unwrap_or_else(|why| panic!("the registration gate refuses the class: {why}"));
    let file = dir.join("sd3-tiny.class.palwtir2");
    let digest =
        gen_write_declared_container_v1(&file, &c.declared, &c.weights, "{\"model_id\":\"palw-fixture/sd3-tiny\"}".to_string())
            .expect("the container");
    let bytes = std::fs::metadata(&file).expect("written").len();
    let (held, _guard) = held(&c);
    let honest = held.run_tensor(&c.job, &c.ids, &[], &[], FORM).expect("the job runs");
    let capture = GenTensorCaptureV1::of(&honest).expect("a capture");
    let material = misaka_palw_base0::gen_tensor_worker::gen_tensor_material_encode_v1(&capture);
    let entry = serde_json::json!({
        "name": "sd3-tiny",
        "model_id": "palw-fixture/sd3-tiny",
        "file": file.file_name().unwrap().to_string_lossy(),
        "bytes": bytes,
        "file_digest": digest.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        "class_id": c.row.class_id.to_string(),
        "artifact_root": c.row.artifact_root.to_string(),
        "profile": format!("{:?}", c.declared.class.profile),
        "canonical_step_leaves": admitted.entry.canonical_step_leaf_count,
        "max_step_leaves": admitted.entry.max_step_leaf_count,
        "sample_job_step_leaves": honest.execution.space.leaf_count(),
        "sample_material_bytes": material.len(),
        "gen_claim_request_template": {
            "profile": "image",
            "anchor_block": "<128 hex: a recent block of the chain>",
            "anchor_daa": "<its DAA score>",
            "job_nonce": "<64 hex: unique per claim>",
            "seed": "<64 hex>",
            "privacy": "public",
            "prompt_token_ids": c.ids,
            "steps": COUNTS[COUNTS.len() - 1],
            "guidance_q": 0,
            "image_index": 0,
            "width": IMAGE_HW,
            "height": IMAGE_HW,
        },
    });
    std::fs::write(dir.join("sd3-tiny.json"), serde_json::to_string_pretty(&entry).unwrap()).expect("the manifest entry");
    eprintln!("wrote {} ({bytes} bytes), class {}", file.display(), c.row.class_id);
}
