//! **RFC-0003 §II.2.1: the class id's and the step tree's golden vectors** (findings G16 and G18 of the
//! independent second implementation) — `consensus-vectors/tir-v2/class-id.json` and `step-tree.json`,
//! generated by `misaka-palw-gen-ref2` (lane E, `misaka-palw-gen-ref2/scripts/gen_proposed_vectors.sh`, branch
//! `rfc3/ref2`) and held here against the consensus layer alone, through its public functions:
//!
//! * **the class id**: eight classes (the five toy pipelines and the three lowered tiny VLMs) — each is
//!   rebuilt from the vector's fields and the source vector's program bytes, passes the class preflight under
//!   the drill fence, and has the pipeline root, the terms digest, the borsh bytes of its layouts, output and
//!   offers (the profile offers included), and the class id the file says; the first class's fifteen
//!   single-field changes each change the id as the file says;
//! * **the step tree's hashes**: a leaf, a Merkle tree with its authentication paths and stage roots, a step
//!   root — the pure functions; and the eight pipelines' step spaces and trees (the leaf counts, every leaf
//!   the file lists with its values and hash, every stage root and the step root) over the honest run of
//!   the source pipeline vector at the stated layouts.
//!
//! * **the tensor claim and the output close** (spec 04b §15.13, added with `tensor-claim.json` and
//!   `output-close.json`): nine classes, eighteen honest claims — every root re-derived by the consensus
//!   layer's tensor worker — and forty-two output closes with the outcome the file says, and the alignment of
//!   output tiles and step tiles.
//!
//! The Python-independent half is lane E's: its generator is a second implementation, and these tests are the
//! day the first one reads the second's numbers back.

use kaspa_consensus_core::Hash64;
use kaspa_consensus_core::config::params::ForkActivation;
use kaspa_consensus_core::palw_gen_class_v1::{
    PalwGenClassV1, PalwGenEmbeddingOffersV1, PalwGenGuidanceOfferV1, PalwGenImageOfferV1, PalwGenImageOffersV1, PalwGenOffersV1,
    PalwGenProfileOffersV1, PalwGenScalarOfferV1, palw_gen_class_preflight_v1, palw_gen_class_record_v1,
};
use kaspa_consensus_core::palw_gen_close_v1::{
    PalwGenCloseErrorV1, PalwGenLeafOpeningV1, PalwGenOutputCloseV1, PalwGenTensorBindingV1, check_gen_output_close_v1,
    palw_gen_output_step_coord_v1, palw_gen_output_tile_at_v1, palw_gen_tensor_execution_root_v1,
};
use kaspa_consensus_core::palw_gen_court_v1::PalwGenCloseRefusalV1;
use kaspa_consensus_core::palw_gen_job_v1::PalwGenJobV1;
use kaspa_consensus_core::palw_step_leg::PalwStepFaultV1;
use kaspa_consensus_core::palw_gen_step_v1::{
    PalwGenLeafCoordV1, PalwGenLeafKindV1, PalwGenLeafV1, PalwGenStepSpaceV1, palw_gen_leaf_path_v1, palw_gen_stage_root_v1,
    palw_gen_step_leaf_hash_v1, palw_gen_step_root_v1,
};
use kaspa_consensus_core::palw_gen_v1::PalwGenFenceV1;
use kaspa_consensus_core::palw_gen_worker_v1::{PalwGenRandomV1, palw_gen_execute_tensor_v1};
use kaspa_consensus_core::palw_tir_class_v1::PalwTirLayoutV1;
use misaka_palw_gen::OutputSpecV1;
use misaka_palw_tir::interp::{MapParams, ParamSource};
use misaka_palw_tir::pipeline::{JobImageV1, PipelineJob, PipelineParams, TirPipelineV1, stage_job_facts};
use misaka_palw_tir::program_v2::TirProgramV2;
use misaka_palw_tir::tensor::Tensor;
use misaka_palw_tir::types::DType;
use serde_json::Value;

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex")).collect()
}

fn load(rel: &str) -> Value {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../consensus-vectors").join(rel);
    serde_json::from_slice(&std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))).expect("json")
}

fn hexv(v: &Value) -> Vec<u8> {
    unhex(v.as_str().expect("a hex string"))
}

fn h64v(v: &Value) -> [u8; 64] {
    hexv(v).try_into().expect("64 bytes")
}

fn u32s(v: &Value) -> Vec<u32> {
    v.as_array().map(|a| a.iter().map(|x| x.as_u64().unwrap() as u32).collect()).unwrap_or_default()
}

/// A vector's number: a JSON number or a decimal string.
fn num(v: &Value) -> i128 {
    match v {
        Value::String(s) => s.parse::<i128>().expect("a decimal"),
        Value::Number(n) => n.as_i64().map(i128::from).or_else(|| n.as_u64().map(i128::from)).expect("an integer"),
        _ => panic!("not a number: {v}"),
    }
}

fn layout_of(l: &Value) -> PalwTirLayoutV1 {
    PalwTirLayoutV1 {
        version: l["version"].as_u64().unwrap() as u16,
        max_context: l["max_context"].as_u64().unwrap() as u32,
        checkpoint_interval: l["checkpoint_interval"].as_u64().unwrap() as u32,
        h_tile: l["h_tile"].as_u64().unwrap() as u32,
        commit_tiles: u32s(&l["commit_tiles"]),
        state_tiles: u32s(&l["state_tiles"]),
    }
}

// ---------------------------------------------------------------------------------------------
// The class id (G16)
// ---------------------------------------------------------------------------------------------

fn profile_offers_of(v: &Value) -> PalwGenProfileOffersV1 {
    match v["kind"].as_str().unwrap() {
        "none" => PalwGenProfileOffersV1::None,
        "image" => PalwGenProfileOffersV1::Image(PalwGenImageOffersV1 {
            sampler_id: Hash64::from_bytes(h64v(&v["sampler_id_hex"])),
            guidance: v["guidance"].as_object().map(|_| PalwGenGuidanceOfferV1 {
                scalar: v["guidance"]["scalar"].as_u64().unwrap() as u8,
                lo: v["guidance"]["lo"].as_u64().unwrap() as u16,
                hi: v["guidance"]["hi"].as_u64().unwrap() as u16,
            }),
            steps_scalar: v["steps_scalar"].as_u64().map(|x| x as u8),
        }),
        "embedding" => PalwGenProfileOffersV1::Embedding(PalwGenEmbeddingOffersV1 {
            pooling: v["pooling"].as_u64().unwrap() as u8,
            dims: u32s(&v["dims"]),
        }),
        k => panic!("profile offers kind {k}"),
    }
}

/// The class a vector entry states, rebuilt from its fields and the source vector's program bytes, with its
/// artifact root.
fn class_of(entry: &Value) -> (PalwGenClassV1, Hash64) {
    let source = load(entry["source"].as_str().unwrap());
    let programs: Vec<Vec<u8>> = source["programs"].as_array().unwrap().iter().map(|p| hexv(&p["program_borsh_hex"])).collect();
    let of = &entry["offers"];
    let offers = PalwGenOffersV1 {
        steps: u32s(&of["steps"]),
        scalars: of["scalars"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| PalwGenScalarOfferV1 { lo: num(&x["lo"]) as i64, hi: num(&x["hi"]) as i64 })
            .collect(),
        max_prompt_tokens: of["max_prompt_tokens"].as_u64().unwrap() as u32,
        max_negative_tokens: of["max_negative_tokens"].as_u64().unwrap() as u32,
        images: of["images"]
            .as_array()
            .unwrap()
            .iter()
            .map(|i| PalwGenImageOfferV1 {
                h: i["h"].as_u64().unwrap() as u32,
                w: i["w"].as_u64().unwrap() as u32,
                tile_len: i["tile_len"].as_u64().unwrap() as u32,
                token_equivalents: i["token_equivalents"].as_u64().unwrap() as u32,
            })
            .collect(),
        max_source_tokens: of["max_source_tokens"].as_u64().unwrap() as u32,
        source_token_floor: of["source_token_floor"].as_u64().unwrap() as u32,
        forced_prompt_prefix: u32s(&of["forced_prompt_prefix"]),
        profile: profile_offers_of(&of["profile"]),
    };
    let out = &entry["output"];
    let class = PalwGenClassV1 {
        version: entry["version"].as_u64().unwrap() as u16,
        profile: entry["profile"].as_u64().unwrap() as u8,
        pipeline: hexv(&entry["pipeline_hex"]),
        programs,
        layouts: entry["layouts"].as_array().unwrap().iter().map(layout_of).collect(),
        output: OutputSpecV1 { kind: out["kind"].as_u64().unwrap() as u8, shape: u32s(&out["shape"]), meta: hexv(&out["meta_hex"]) },
        offers,
        tokenizer_id: Hash64::from_bytes(h64v(&entry["tokenizer_id_hex"])),
    };
    (class, Hash64::from_bytes(h64v(&entry["artifact_root_hex"])))
}

fn flip_last(h: &Hash64) -> Hash64 {
    let mut b: [u8; 64] = *h.as_byte_slice();
    b[63] ^= 1;
    Hash64::from_bytes(b)
}

/// The fifteen single-field changes of the file, by their stated words.
fn change(what: &str, class: &mut PalwGenClassV1, artifact_root: &mut Hash64) {
    match what {
        "artifact_root: the last byte ^ 1" => *artifact_root = flip_last(artifact_root),
        "tokenizer_id: the last byte ^ 1" => class.tokenizer_id = flip_last(&class.tokenizer_id),
        "version: 2" => class.version = 2,
        "profile: 2" => class.profile = 2,
        "pipeline: the byte at len / 2 ^ 1" => {
            let at = class.pipeline.len() / 2;
            class.pipeline[at] ^= 1;
        }
        "program 0's canonical bytes: the last byte ^ 1 (its graph_ir_root over those bytes)" => {
            let last = class.programs[0].len() - 1;
            class.programs[0][last] ^= 1;
        }
        "programs 0 and 1 swapped" => class.programs.swap(0, 1),
        "layouts[0].checkpoint_interval + 1" => class.layouts[0].checkpoint_interval += 1,
        "layouts[0].h_tile + 1" => class.layouts[0].h_tile += 1,
        "layouts 0 and 1 swapped" => class.layouts.swap(0, 1),
        "output.shape[0] + 1" => class.output.shape[0] += 1,
        "output.meta: one 0 byte appended" => class.output.meta.push(0),
        "offers.steps: one more step count appended" => {
            let next = class.offers.steps.last().copied().unwrap_or(0) + 1;
            class.offers.steps.push(next);
        }
        "offers.scalars[0].hi + 1" => class.offers.scalars[0].hi += 1,
        "offers.max_prompt_tokens + 1" => class.offers.max_prompt_tokens += 1,
        other => panic!("a single-field change this test does not know: {other}"),
    }
}

#[test]
fn the_class_id_vectors_hold_against_the_consensus_layer() {
    let v = load("tir-v2/class-id.json");
    let keys = &v["keys"];
    assert_eq!(
        keys["pipeline_root"].as_str().unwrap().as_bytes(),
        kaspa_consensus_core::palw_gen_class_v1::PALW_GEN_PIPELINE_ROOT_DOMAIN_V1
    );
    assert_eq!(
        keys["terms_digest"].as_str().unwrap().as_bytes(),
        kaspa_consensus_core::palw_gen_class_v1::PALW_GEN_CLASS_TERMS_DOMAIN_V1
    );
    assert_eq!(keys["class_id"].as_str().unwrap().as_bytes(), kaspa_consensus_core::palw_gen_class_v1::PALW_GEN_CLASS_ID_DOMAIN_V1);
    let classes = v["classes"].as_array().unwrap();
    assert_eq!(classes.len(), 8);
    let fence = PalwGenFenceV1::drill_v1(ForkActivation::always());
    let mut changes = 0;
    for entry in classes {
        let name = entry["name"].as_str().unwrap();
        let (class, root) = class_of(entry);
        // Every class is one the preflight admits.
        palw_gen_class_preflight_v1(&class, &fence).unwrap_or_else(|e| panic!("{name}: the class does not pass the preflight: {e}"));
        assert_eq!(class.pipeline_root().as_byte_slice(), &h64v(&entry["pipeline_root_hex"])[..], "{name}: pipeline_root");
        assert_eq!(class.terms_digest().as_byte_slice(), &h64v(&entry["terms_digest_hex"])[..], "{name}: terms_digest");
        assert_eq!(class.class_id(&root).as_byte_slice(), &h64v(&entry["class_id_hex"])[..], "{name}: class_id");
        // The borsh bytes the vector states are the consensus layer's.
        assert_eq!(borsh::to_vec(&class.layouts).unwrap(), hexv(&entry["layouts_borsh_hex"]), "{name}: layouts borsh");
        assert_eq!(borsh::to_vec(&class.output).unwrap(), hexv(&entry["output_borsh_hex"]), "{name}: output borsh");
        assert_eq!(borsh::to_vec(&class.offers).unwrap(), hexv(&entry["offers_borsh_hex"]), "{name}: offers borsh");
        // The programs' graph_ir_roots the pipeline root binds.
        for (k, program) in class.programs.iter().enumerate() {
            assert_eq!(
                kaspa_consensus_core::palw_tir_artifact_v1::palw_tir_graph_ir_root_v1(program).as_byte_slice(),
                &h64v(&entry["program_graph_ir_root_hex"][k])[..],
                "{name}: program {k}'s graph_ir_root"
            );
        }
        if let Some(rows) = entry["single_field_changes"].as_array() {
            assert_eq!(rows.len(), 15, "{name}: fifteen single-field changes");
            for row in rows {
                let what = row["change"].as_str().unwrap();
                let (mut c, mut r) = (class.clone(), root);
                change(what, &mut c, &mut r);
                assert_ne!(c.class_id(&r), class.class_id(&root), "{name}: {what} changes the id");
                assert_eq!(c.class_id(&r).as_byte_slice(), &h64v(&row["class_id_hex"])[..], "{name}: {what}");
                changes += 1;
            }
        }
    }
    assert_eq!(changes, 15);
}

// ---------------------------------------------------------------------------------------------
// The step tree's hashes (G18)
// ---------------------------------------------------------------------------------------------

#[test]
fn the_step_tree_keys_and_pure_cases_hold_against_the_consensus_layer() {
    use kaspa_consensus_core::palw_gen_step_v1::{
        PALW_GEN_STAGE_ROOT_DOMAIN_V1, PALW_GEN_STEP_LEAF_DOMAIN_V1, PALW_GEN_STEP_NODE_DOMAIN_V1, PALW_GEN_STEP_ROOT_DOMAIN_V1,
    };
    let v = load("tir-v2/step-tree.json");
    let keys = &v["keys"];
    assert_eq!(keys["leaf"].as_str().unwrap().as_bytes(), PALW_GEN_STEP_LEAF_DOMAIN_V1);
    assert_eq!(keys["node"].as_str().unwrap().as_bytes(), PALW_GEN_STEP_NODE_DOMAIN_V1);
    assert_eq!(keys["stage_root"].as_str().unwrap().as_bytes(), PALW_GEN_STAGE_ROOT_DOMAIN_V1);
    assert_eq!(keys["step_root"].as_str().unwrap().as_bytes(), PALW_GEN_STEP_ROOT_DOMAIN_V1);
    // Leaves.
    let leaf_cases = v["leaf_cases"].as_array().unwrap();
    assert_eq!(leaf_cases.len(), 7);
    for case in leaf_cases {
        let name = case["name"].as_str().unwrap();
        let c = &case["coord"];
        let kind = match c["kind"].as_str().unwrap() {
            "commit" => PalwGenLeafKindV1::Commit {
                occurrence: c["occurrence"].as_u64().unwrap() as u16,
                node: c["node"].as_u64().unwrap() as u16,
            },
            _ => PalwGenLeafKindV1::State { state: c["state"].as_u64().unwrap() as u16, layer: c["layer"].as_u64().map(|l| l as u16) },
        };
        let values: Vec<i128> = case["values"].as_array().unwrap().iter().map(num).collect();
        let leaf = PalwGenLeafV1 {
            coord: PalwGenLeafCoordV1 {
                stage: c["stage"].as_u64().unwrap() as u8,
                pos: c["pos"].as_u64().unwrap() as u32,
                kind,
                tile: c["tile"].as_u64().unwrap() as u32,
            },
            dtype: DType::from_name(case["dtype"].as_str().unwrap()).unwrap(),
            first_element: 0,
            value_count: values.len() as u32,
        };
        let hash = palw_gen_step_leaf_hash_v1(&leaf, &values).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(hash.as_byte_slice(), &h64v(&case["hash_hex"])[..], "{name}: leaf hash");
    }
    // Merkle trees: the stage roots bind the Merkle root; the paths are the shipped paths.
    let merkle_cases = v["merkle_cases"].as_array().unwrap();
    assert_eq!(merkle_cases.len(), 11);
    for case in merkle_cases {
        let leaves: Vec<Hash64> = case["leaf_hashes_hex"].as_array().unwrap().iter().map(|h| Hash64::from_bytes(h64v(h))).collect();
        assert_eq!(leaves.len() as u64, case["leaf_count"].as_u64().unwrap());
        for sr in case["stage_roots"].as_array().unwrap() {
            let stage = sr["stage"].as_u64().unwrap() as u8;
            assert_eq!(
                palw_gen_stage_root_v1(stage, &leaves).as_byte_slice(),
                &h64v(&sr["root_hex"])[..],
                "{} leaves, stage {stage}",
                leaves.len()
            );
        }
        for p in case["paths"].as_array().unwrap() {
            let i = p["index"].as_u64().unwrap() as usize;
            let shipped: Vec<[u8; 64]> = palw_gen_leaf_path_v1(&leaves, i).unwrap().iter().map(|h| *h.as_byte_slice()).collect();
            let theirs: Vec<[u8; 64]> = p["path_hex"].as_array().unwrap().iter().map(h64v).collect();
            assert_eq!(shipped, theirs, "{} leaves, path {i}", leaves.len());
        }
    }
    // Step roots.
    let step_cases = v["step_root_cases"].as_array().unwrap();
    assert_eq!(step_cases.len(), 4);
    for case in step_cases {
        let roots: Vec<Hash64> = case["stage_roots_hex"].as_array().unwrap().iter().map(|h| Hash64::from_bytes(h64v(h))).collect();
        assert_eq!(palw_gen_step_root_v1(&roots).as_byte_slice(), &h64v(&case["step_root_hex"])[..], "{} stage roots", roots.len());
    }
}

struct Weights(Vec<MapParams>);
impl PipelineParams for Weights {
    fn params(&self, program: u16) -> &dyn ParamSource {
        &self.0[program as usize]
    }
}

fn ids(v: &Value) -> Vec<u32> {
    u32s(v)
}

/// A pipeline vector's job: the toy vectors state every field, the lowered tiny VLMs a prompt, the generated
/// ids and an image.
fn job_of(j: &Value) -> PipelineJob {
    PipelineJob {
        prompt: ids(&j["prompt"]),
        negative: ids(&j["negative"]),
        source: ids(&j["source"]),
        steps: j["steps"].as_u64().unwrap_or(0) as u32,
        scalars: j["scalars"].as_array().map(|a| a.iter().map(|x| num(x) as i64).collect()).unwrap_or_default(),
        images: j["images"]
            .as_array()
            .map(|a| {
                a.iter()
                    .map(|i| JobImageV1 {
                        h: i["h"].as_u64().unwrap() as u32,
                        w: i["w"].as_u64().unwrap() as u32,
                        rgb: hexv(&i["rgb_hex"]),
                    })
                    .collect()
            })
            .unwrap_or_default(),
        generated: ids(&j["generated"]),
        // The vectors state no item key and no finalized claim's output (RFC-0004 §7.3 fields).
        ..PipelineJob::default()
    }
}

#[test]
fn the_pipeline_step_trees_hold_against_the_consensus_layer() {
    let v = load("tir-v2/step-tree.json");
    let pipelines = v["pipelines"].as_array().unwrap();
    assert_eq!(pipelines.len(), 8);
    let (mut leaf_hashes, mut roots, mut structures) = (0usize, 0usize, 0usize);
    for pv in pipelines {
        let name = pv["name"].as_str().unwrap();
        let src = load(pv["source"].as_str().unwrap());
        let programs: Vec<TirProgramV2> = src["programs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| TirProgramV2::decode_canonical(&hexv(&p["program_borsh_hex"])).unwrap())
            .collect();
        let pipeline = TirPipelineV1::decode_canonical(&hexv(&src["pipeline_borsh_hex"]), &programs).unwrap();
        let job = job_of(&src["job"]);
        assert_eq!(job.prompt.len() as u64, pv["job_prompt_len"].as_u64().unwrap(), "{name}: the job's prompt length");
        let (seed, item): ([u8; 32], u32) = match src["seed_hex"].as_str() {
            Some(s) => (unhex(s).try_into().unwrap(), src["item_index"].as_u64().unwrap() as u32),
            None => ([0; 32], 0),
        };
        // The weights, where the vector ships them.
        let params = Weights(
            src["programs"]
                .as_array()
                .unwrap()
                .iter()
                .zip(&programs)
                .map(|(pj, prog)| {
                    let mut m = MapParams::default();
                    for e in pj["params"].as_array().unwrap() {
                        let j = e["param"].as_u64().unwrap() as u16;
                        let decl = &prog.params[j as usize];
                        let shape: Vec<usize> = decl.shape.iter().map(|d| *d as usize).collect();
                        let layer = e["layer"].as_u64().map(|l| l as u16);
                        m.tensors.insert((j, layer), Tensor::from_le_bytes(decl.dtype, &shape, &hexv(&e["le_hex"])).unwrap());
                    }
                    m
                })
                .collect(),
        );
        let has_weights = params.0.iter().any(|m| !m.tensors.is_empty());
        let run = has_weights.then(|| {
            misaka_palw_tir::pipeline::run_pipeline(&pipeline, &programs, &params, &PalwGenRandomV1 { seed, item }, &job)
                .unwrap_or_else(|e| panic!("{name}: the run: {e}"))
        });
        let facts = stage_job_facts(&pipeline, &programs, &job).unwrap();
        let trips: Vec<u32> = facts.iter().map(|f| f.trip).collect();
        for tree in pv["trees"].as_array().unwrap() {
            let layouts: Vec<PalwTirLayoutV1> = tree["layouts"].as_array().unwrap().iter().map(layout_of).collect();
            let space = PalwGenStepSpaceV1::new(&pipeline, &programs, &layouts, &trips, job.prompt.len() as u32)
                .unwrap_or_else(|e| panic!("{name}: the step space: {e}"));
            assert_eq!(space.leaf_count(), tree["leaf_count"].as_u64().unwrap(), "{name}: total leaf count");
            let mut stage_roots: Vec<Hash64> = Vec::new();
            for (si, sv) in tree["stages"].as_array().unwrap().iter().enumerate() {
                let stage_space = &space.stages[si];
                assert_eq!(stage_space.leaves().len() as u64, sv["leaf_count"].as_u64().unwrap(), "{name} stage {si}: leaf count");
                assert_eq!(trips[si] as u64, sv["trip"].as_u64().unwrap(), "{name} stage {si}: trip");
                let Some(run) = &run else {
                    structures += 1;
                    continue;
                };
                let values = stage_space.leaf_values(&run.stages[si]).unwrap_or_else(|e| panic!("{name} stage {si}: {e}"));
                let hashes: Vec<Hash64> =
                    stage_space.leaves().iter().zip(&values).map(|(leaf, v)| palw_gen_step_leaf_hash_v1(leaf, v).unwrap()).collect();
                leaf_hashes += hashes.len();
                // Every leaf the file lists, by its index.
                for e in sv["leaves"].as_array().unwrap() {
                    let i = e["i"].as_u64().unwrap() as usize;
                    let want: Vec<i128> = e["values"].as_array().unwrap().iter().map(num).collect();
                    assert_eq!(values[i], want, "{name} stage {si} leaf {i}: values");
                    assert_eq!(hashes[i].as_byte_slice(), &h64v(&e["hash_hex"])[..], "{name} stage {si} leaf {i}: hash");
                }
                let root = palw_gen_stage_root_v1(si as u8, &hashes);
                assert_eq!(root.as_byte_slice(), &h64v(&sv["stage_root_hex"])[..], "{name} stage {si}: stage root");
                roots += 1;
                stage_roots.push(root);
            }
            if run.is_some() {
                assert_eq!(
                    palw_gen_step_root_v1(&stage_roots).as_byte_slice(),
                    &h64v(&tree["step_root_hex"])[..],
                    "{name}: step root"
                );
                roots += 1;
            }
        }
    }
    eprintln!(
        "step-tree vectors: {leaf_hashes} leaf hashes, {roots} stage and step roots, {structures} weight-free stage structures agree"
    );
    assert!(leaf_hashes > 1000 && roots > 20 && structures > 0);
}

// ---------------------------------------------------------------------------------------------
// The tensor claim and the output close (spec 04b §15.13; findings of lane E's second implementation)
// ---------------------------------------------------------------------------------------------
//
// `consensus-vectors/tir-v2/tensor-claim.json` and `output-close.json` — nine registered tensor classes, two
// honest claims of each (every root), and forty-two output closes (six acquitted, eleven convicted, twenty-five
// refused, the G21 out-of-dtype lane among the convictions) — generated by `misaka-palw-gen-ref2`
// (`scripts/gen_proposed_vectors.sh`, branch `rfc3/ref2`, proposed at b6a01bfc6) and held here against the
// consensus layer alone, through its public functions, reading every number back from the files. Copied, not
// merged: the generator is lane E's, this is the day the first implementation reads the second's numbers.

fn u64_of(v: &Value) -> u64 {
    v.as_str().map(|x| x.parse().unwrap()).or_else(|| v.as_u64()).expect("a u64 or a decimal string")
}

fn hashes(v: &Value) -> Vec<Hash64> {
    v.as_array().unwrap().iter().map(|x| Hash64::from_bytes(h64v(x))).collect()
}

fn coord_of(v: &Value) -> PalwGenLeafCoordV1 {
    let kind = match v["kind"].as_str().unwrap() {
        "commit" => {
            PalwGenLeafKindV1::Commit { occurrence: v["occurrence"].as_u64().unwrap() as u16, node: v["node"].as_u64().unwrap() as u16 }
        }
        "state" => PalwGenLeafKindV1::State {
            state: v["state"].as_u64().unwrap() as u16,
            layer: v["layer"].as_u64().map(|x| x as u16),
        },
        k => panic!("a coordinate kind {k}"),
    };
    PalwGenLeafCoordV1 { stage: v["stage"].as_u64().unwrap() as u8, pos: v["pos"].as_u64().unwrap() as u32, kind, tile: v["tile"].as_u64().unwrap() as u32 }
}

/// A source vector's weights, per program (the toy pipelines state them).
fn weights_of(src: &Value, programs: &[TirProgramV2]) -> Weights {
    Weights(
        src["programs"]
            .as_array()
            .unwrap()
            .iter()
            .zip(programs)
            .map(|(pj, prog)| {
                let mut m = MapParams::default();
                for e in pj["params"].as_array().unwrap() {
                    let j = e["param"].as_u64().unwrap() as u16;
                    let decl = &prog.params[j as usize];
                    let shape: Vec<usize> = decl.shape.iter().map(|d| *d as usize).collect();
                    let layer = e["layer"].as_u64().map(|l| l as u16);
                    m.tensors.insert((j, layer), Tensor::from_le_bytes(decl.dtype, &shape, &hexv(&e["le_hex"])).unwrap());
                }
                m
            })
            .collect(),
    )
}

/// The pipeline job a claim of the file runs: the accepted steps and scalars, the ids and the images as given.
fn claim_job_of(c: &Value) -> PipelineJob {
    let inputs = &c["inputs"];
    assert_eq!(c["accepted"]["negative_tokens"].as_u64().unwrap(), 0, "{}: the corpus tensor classes take no negative prompt", c["name"]);
    PipelineJob {
        prompt: u32s(&inputs["prompt_token_ids"]),
        negative: vec![],
        source: vec![],
        steps: c["accepted"]["steps"].as_u64().unwrap() as u32,
        scalars: c["accepted"]["scalars"].as_array().unwrap().iter().map(|x| num(x) as i64).collect(),
        images: inputs["images"]
            .as_array()
            .unwrap()
            .iter()
            .map(|i| JobImageV1 { h: i["h"].as_u64().unwrap() as u32, w: i["w"].as_u64().unwrap() as u32, rgb: hexv(&i["rgb_hex"]) })
            .collect(),
        generated: vec![],
    }
}

/// A class entry's programs and pipeline, decoded from its own bytes.
fn pipeline_of(class: &PalwGenClassV1) -> (TirPipelineV1, Vec<TirProgramV2>) {
    let programs: Vec<TirProgramV2> = class.programs.iter().map(|b| TirProgramV2::decode_canonical(b).unwrap()).collect();
    let pipeline = TirPipelineV1::decode_canonical(&class.pipeline, &programs).unwrap();
    (pipeline, programs)
}

#[test]
fn the_tensor_claim_vectors_hold_against_the_consensus_layer() {
    let file = load("tir-v2/tensor-claim.json");
    assert_eq!(file["format"].as_str().unwrap(), "palw-gen/tensor-claim-vectors/1");
    assert_eq!(
        file["keys"]["tensor_execution_root"].as_str().unwrap().as_bytes(),
        kaspa_consensus_core::palw_gen_close_v1::PALW_GEN_TENSOR_EXECUTION_ROOT_DOMAIN_V1
    );
    assert_eq!(file["keys"]["job_id"].as_str().unwrap().as_bytes(), kaspa_consensus_core::palw_gen_job_v1::PALW_GEN_JOB_ID_DOMAIN_V1);
    // The execution root as a pure function, with its extremes.
    let cases = file["execution_root_cases"].as_array().unwrap();
    assert_eq!(cases.len(), 9);
    for c in cases {
        let theirs = palw_gen_tensor_execution_root_v1(
            &Hash64::from_bytes(h64v(&c["job_id_hex"])),
            &Hash64::from_bytes(h64v(&c["class_id_hex"])),
            u64_of(&c["step_leaf_count"]),
            &Hash64::from_bytes(h64v(&c["step_root_hex"])),
            &Hash64::from_bytes(h64v(&c["output_root_hex"])),
        );
        assert_eq!(theirs.as_byte_slice(), &h64v(&c["execution_root_hex"])[..], "{c}");
    }
    // The classes: each is rebuilt from the entry and the source vector's program bytes, passes the preflight
    // under the drill fence, and has the id, the programs' graph roots and the Borsh bytes the file says; the
    // `4-2-2` ones are `class-id.json`'s.
    let class_ids = load("tir-v2/class-id.json");
    let fence = PalwGenFenceV1::drill_v1(ForkActivation::always());
    let entries = file["classes"].as_array().unwrap();
    assert_eq!(entries.len(), 9);
    for e in entries {
        let name = e["name"].as_str().unwrap();
        let (class, root) = class_of(e);
        palw_gen_class_preflight_v1(&class, &fence).unwrap_or_else(|err| panic!("{name}: the class does not pass the preflight: {err}"));
        assert_eq!(class.class_id(&root).as_byte_slice(), &h64v(&e["class_id_hex"])[..], "{name}: the class id");
        assert_eq!(borsh::to_vec(&class.layouts).unwrap(), hexv(&e["layouts_borsh_hex"]), "{name}: layouts borsh");
        assert_eq!(borsh::to_vec(&class.output).unwrap(), hexv(&e["output_borsh_hex"]), "{name}: output borsh");
        assert_eq!(borsh::to_vec(&class.offers).unwrap(), hexv(&e["offers_borsh_hex"]), "{name}: offers borsh");
        for (k, program) in class.programs.iter().enumerate() {
            assert_eq!(
                kaspa_consensus_core::palw_tir_artifact_v1::palw_tir_graph_ir_root_v1(program).as_byte_slice(),
                &h64v(&e["program_graph_ir_root_hex"][k])[..],
                "{name}: program {k}'s graph_ir_root"
            );
        }
        let lp = &e["layout_params"];
        if lp["tile_len"] == 4 && lp["checkpoint_interval"] == 2 && lp["h_tile"] == 2 {
            let theirs = class_ids["classes"]
                .as_array()
                .unwrap()
                .iter()
                .find(|c| name.starts_with(c["name"].as_str().unwrap()))
                .unwrap_or_else(|| panic!("{name}: class-id.json has no such class"));
            assert_eq!(theirs["class_id_hex"], e["class_id_hex"], "{name} is class-id.json's class");
        }
    }
    // The claims: the consensus layer's worker over the file's inputs, every number of the claim.
    let claims = file["claims"].as_array().unwrap();
    assert_eq!(claims.len(), 18);
    let mut leaves = 0u64;
    for c in claims {
        let name = c["name"].as_str().unwrap();
        let entry = entries.iter().find(|e| e["name"] == c["class"]).unwrap_or_else(|| panic!("{name}: its class"));
        let (class, root) = class_of(entry);
        let row = palw_gen_class_record_v1(&class, &root).expect("a registered class");
        let (pipeline, programs) = pipeline_of(&class);
        let src = load(entry["source"].as_str().unwrap());
        let params = weights_of(&src, &programs);
        // The job: canonical bytes, the id the file says, acceptance's mapping against the class's row.
        let job = PalwGenJobV1::decode_canonical(&hexv(&c["job_borsh_hex"])).expect("a canonical job");
        assert_eq!(job.encode(), hexv(&c["job_borsh_hex"]), "{name}: the job's bytes");
        assert_eq!(job.id().as_byte_slice(), &h64v(&c["job_id_hex"])[..], "{name}: the job id");
        assert_eq!(c["class_id_hex"], entry["class_id_hex"], "{name}: the claim names its class");
        let accepted = kaspa_consensus_core::palw_gen_job_v1::palw_gen_job_resolve_class_v1(&job, &row)
            .unwrap_or_else(|e| panic!("{name}: the class refuses the honest job: {e}"));
        assert_eq!(accepted.item_index as u64, c["accepted"]["item_index"].as_u64().unwrap(), "{name}: the item index");
        assert_eq!(accepted.steps as u64, c["accepted"]["steps"].as_u64().unwrap(), "{name}: the steps");
        assert_eq!(accepted.prompt_tokens as u64, c["accepted"]["prompt_tokens"].as_u64().unwrap(), "{name}: the prompt tokens");
        let pj = claim_job_of(c);
        let seed: [u8; 32] = hexv(&c["job"]["seed_hex"]).try_into().expect("a 32-byte seed");
        let item = c["accepted"]["item_index"].as_u64().unwrap() as u32;
        let t = palw_gen_execute_tensor_v1(&pipeline, &programs, &class.layouts, &params, &pj, seed, item, &class.output)
            .unwrap_or_else(|e| panic!("{name}: the worker refuses the honest job: {e}"));
        let cl = &c["claim"];
        let stage_roots = hashes(&cl["stage_roots_hex"]);
        assert_eq!(t.claim.stage_roots, stage_roots, "{name}: the stage roots");
        let counts: Vec<u64> = cl["stage_leaf_counts"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap()).collect();
        for (s, k) in counts.iter().enumerate() {
            assert_eq!(t.leaf_hashes[s].len() as u64, *k, "{name}: stage {s}'s leaves");
        }
        assert_eq!(t.space.leaf_count(), u64_of(&cl["step_leaf_count"]), "{name}: the step leaf count");
        assert_eq!(t.claim.step_root.as_byte_slice(), &h64v(&cl["step_root_hex"])[..], "{name}: the step root");
        let out = t.output.as_ref().expect("a tensor claim has an output");
        assert_eq!(out.root.as_byte_slice(), &h64v(&cl["output"]["output_root_hex"])[..], "{name}: the output root");
        assert_eq!(out.tile_len as u64, cl["output"]["tile_len"].as_u64().unwrap(), "{name}: the output tile length");
        let execution = palw_gen_tensor_execution_root_v1(&job.id(), &class.class_id(&root), t.space.leaf_count(), &t.claim.step_root, &out.root);
        assert_eq!(execution.as_byte_slice(), &h64v(&cl["execution_root_hex"])[..], "{name}: the execution root");
        leaves += t.space.leaf_count();
    }
    eprintln!("tensor claims: {} claims over {} classes, {leaves} step leaves hashed by the consensus layer's worker, every root equal", claims.len(), entries.len());
}

/// The consensus layer's close, rebuilt from a case of the file alone.
fn shipped_close(c: &Value) -> PalwGenOutputCloseV1 {
    let b = &c["binding"];
    PalwGenOutputCloseV1 {
        version: c["version"].as_u64().unwrap() as u16,
        binding: PalwGenTensorBindingV1 {
            version: b["version"].as_u64().unwrap() as u16,
            job: PalwGenJobV1::decode_canonical(&hexv(&b["job_borsh_hex"])).expect("a decodable job"),
            stage_roots: hashes(&b["stage_roots_hex"]),
            step_leaf_count: u64_of(&b["step_leaf_count"]),
            output_root: Hash64::from_bytes(h64v(&b["output_root_hex"])),
            committed_execution_root: Hash64::from_bytes(h64v(&b["committed_execution_root_hex"])),
        },
        tile: u64_of(&c["tile"]),
        output_tile: hexv(&c["output_tile_hex"]),
        output_proof: c["output_proof_hex"].as_array().unwrap().iter().map(h64v).collect(),
        step_tile: PalwGenLeafOpeningV1 {
            coord: coord_of(&c["step_tile"]["coord"]),
            lanes_le: hexv(&c["step_tile"]["lanes_le_hex"]),
            path: hashes(&c["step_tile"]["path_hex"]),
        },
    }
}

/// How the consensus layer names an outcome, as one word (the file's `expect`, in the same words).
fn their_word(r: &Result<Option<PalwStepFaultV1>, PalwGenCloseErrorV1>) -> String {
    match r {
        Ok(None) => "Acquitted".into(),
        Ok(Some(PalwStepFaultV1::TirOutputDigestMismatch { value_index })) => format!("Convicted:Digest@{value_index}"),
        Ok(Some(PalwStepFaultV1::TirValueOutsideProvenInterval { value_index })) => format!("Convicted:Outside@{value_index}"),
        Ok(Some(PalwStepFaultV1::StepLeafCountNotCanonical)) => "Convicted:LeafCount".into(),
        Ok(Some(f)) => format!("Convicted:other {f:?}"),
        Err(PalwGenCloseErrorV1::Version(_)) => "Refused:Version".into(),
        Err(PalwGenCloseErrorV1::NotTheClaims(_)) => "Refused:NotTheClaims".into(),
        Err(PalwGenCloseErrorV1::Binding(_)) => "Refused:Binding".into(),
        Err(PalwGenCloseErrorV1::NotTheOutputStepTile { .. }) => "Refused:NotTheOutputStepTile".into(),
        Err(PalwGenCloseErrorV1::NotTheNarrowedLeaf { .. }) => "Refused:NotTheNarrowedLeaf".into(),
        Err(PalwGenCloseErrorV1::Refused(PalwGenCloseRefusalV1::LeafNotProven(_))) => "Refused:LeafNotProven".into(),
        Err(PalwGenCloseErrorV1::OutputRefused(e)) => {
            let d = format!("{e:?}");
            format!(
                "Refused:{}",
                if d.starts_with("TileNotProven") {
                    "TileNotProven"
                } else if d.starts_with("LaneCount") {
                    "LaneCount"
                } else {
                    "OutputRefused"
                }
            )
        }
        Err(e) => format!("Refused:other {e:?}"),
    }
}

/// The expectation of a case, as the file writes it, in the same words.
fn word_of_expect(e: &Value) -> String {
    match e["outcome"].as_str().unwrap() {
        "Acquitted" => "Acquitted".into(),
        "Refused" => format!("Refused:{}", e["refusal"].as_str().unwrap()),
        "Convicted" => {
            let name = match e["fault"].as_str().unwrap() {
                "TirOutputDigestMismatch" => "Digest",
                "TirValueOutsideProvenInterval" => "Outside",
                "StepLeafCountNotCanonical" => "LeafCount",
                other => panic!("a fault {other}"),
            };
            match e.get("value_index") {
                Some(i) => format!("Convicted:{name}@{}", i.as_u64().unwrap()),
                None => format!("Convicted:{name}"),
            }
        }
        other => panic!("an outcome {other}"),
    }
}

#[test]
fn the_output_close_vectors_hold_against_the_consensus_layer() {
    let file = load("tir-v2/output-close.json");
    assert_eq!(file["format"].as_str().unwrap(), "palw-gen/output-close-vectors/1");
    let claims = load("tir-v2/tensor-claim.json");
    let entries = claims["classes"].as_array().unwrap();
    let cases = file["closes"].as_array().unwrap();
    assert_eq!(cases.len(), 42);
    let mut words: std::collections::BTreeMap<String, usize> = Default::default();
    for c in cases {
        let id = c["id"].as_str().unwrap();
        let entry = entries.iter().find(|e| e["name"] == c["class"]).unwrap_or_else(|| panic!("{id}: its class"));
        let (class, root) = class_of(entry);
        let row = palw_gen_class_record_v1(&class, &root).expect("a registered class");
        let close = shipped_close(&c["close"]);
        let narrowed = if c["narrowed"].is_null() { None } else { Some(u64_of(&c["narrowed"])) };
        let theirs = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            check_gen_output_close_v1(
                &close,
                &row,
                &Hash64::from_bytes(h64v(&c["claim"]["class_id_hex"])),
                &Hash64::from_bytes(h64v(&c["claim"]["execution_root_hex"])),
                narrowed,
            )
        }))
        .unwrap_or_else(|_| panic!("{id}: the consensus layer panics"));
        let want = word_of_expect(&c["expect"]);
        assert_eq!(their_word(&theirs), want, "{id}");
        *words.entry(want.split('@').next().unwrap().to_string()).or_default() += 1;
    }
    eprintln!("output close: every case's expectation is the consensus layer's answer, read back from the file: {words:?}");
    // The file's claim about itself: what it covers (6 acquitted, 11 convicted, 25 refused; G21's out-of-dtype
    // lane is among the convictions, outside the proven interval).
    let n = |prefix: &str| words.iter().filter(|(w, _)| w.starts_with(prefix)).map(|(_, k)| *k).sum::<usize>();
    assert_eq!((n("Acquitted"), n("Convicted"), n("Refused")), (6, 11, 25));
    for must in ["Convicted:Digest", "Convicted:Outside", "Convicted:LeafCount"] {
        assert!(words.contains_key(must), "no case for {must}");
    }
    for must in ["Version", "NotTheClaims", "Binding", "NotTheOutputStepTile", "NotTheNarrowedLeaf", "LeafNotProven", "TileNotProven"] {
        assert!(words.contains_key(&format!("Refused:{must}")), "no case for Refused:{must}");
    }
}

#[test]
fn the_output_tile_alignment_vectors_hold_against_the_consensus_layer() {
    let file = load("tir-v2/output-close.json");
    let claims = load("tir-v2/tensor-claim.json");
    let entries = claims["classes"].as_array().unwrap();
    // `Final`: the corpus classes — the output node's last step tile of the output stage is the output's last
    // tile, and the tiles before it map one to one (PALW-OUT-3).
    let finals = file["alignment_final"].as_array().unwrap();
    assert_eq!(finals.len(), 9);
    for a in finals {
        let name = a["class"].as_str().unwrap();
        let entry = entries.iter().find(|e| e["name"] == a["class"]).unwrap_or_else(|| panic!("{name}: its class"));
        let (class, _) = class_of(entry);
        let (pipeline, programs) = pipeline_of(&class);
        // The trips come from a claim's job of this class (the corpus classes' two claims share their shape).
        let claim = claims["claims"].as_array().unwrap().iter().find(|c| c["class"] == a["class"]).expect("a claim of the class");
        let job = claim_job_of(claim);
        let trips: Vec<u32> = stage_job_facts(&pipeline, &programs, &job).unwrap().iter().map(|f| f.trip).collect();
        let stage = a["output_stage"].as_u64().unwrap() as usize;
        assert_eq!(trips[stage] as u64, a["trip"].as_u64().unwrap(), "{name}: the output stage's trip");
        let space = PalwGenStepSpaceV1::new(&pipeline, &programs, &class.layouts, &trips, job.prompt.len() as u32).expect("a step space");
        let st = &space.stages[stage];
        let tile_len = a["tile_len"].as_u64().unwrap() as u32;
        for t in a["output_tiles"].as_array().unwrap() {
            let tile = t["tile"].as_u64().unwrap();
            let theirs = palw_gen_output_step_coord_v1(st, tile, tile_len);
            match &t["step_tile"] {
                Value::Null => assert!(theirs.is_none(), "{name} tile {tile}"),
                c => {
                    assert_eq!(theirs, Some(coord_of(c)), "{name} tile {tile}");
                    assert_eq!(palw_gen_output_tile_at_v1(st, &coord_of(c), tile_len), Some(tile), "{name} tile {tile}: the inverse");
                }
            }
        }
    }
    // `Rows`: the one-stage pipeline whose output node is a per-position row.
    let rows = &file["alignment_rows"];
    let program = TirProgramV2::decode_canonical(&hexv(&rows["program_borsh_hex"])).expect("the rows program");
    let pipeline = TirPipelineV1::decode_canonical(&hexv(&rows["pipeline_hex"]), std::slice::from_ref(&program)).expect("the rows pipeline");
    let configs = rows["configs"].as_array().unwrap();
    assert!(!configs.is_empty());
    for cfg in configs {
        let layout = layout_of(&cfg["layout"]);
        let trip = cfg["trip"].as_u64().unwrap() as u32;
        let space = PalwGenStepSpaceV1::new(&pipeline, std::slice::from_ref(&program), &[layout], &[trip], trip).expect("a step space");
        let tile_len = cfg["tile_len"].as_u64().unwrap() as u32;
        let st = &space.stages[0];
        for t in cfg["output_tiles"].as_array().unwrap() {
            let theirs = palw_gen_output_step_coord_v1(st, t["tile"].as_u64().unwrap(), tile_len);
            match &t["step_tile"] {
                Value::Null => assert!(theirs.is_none(), "Rows tile {}", t["tile"]),
                c => assert_eq!(theirs, Some(coord_of(c)), "Rows tile {}", t["tile"]),
            }
        }
        for t in cfg["step_tiles_that_are_output_tiles_and_the_first_that_are_not"].as_array().unwrap() {
            let coord = coord_of(&t["coord"]);
            let theirs = palw_gen_output_tile_at_v1(st, &coord, tile_len);
            assert_eq!(theirs, if t["output_tile"].is_null() { None } else { Some(u64_of(&t["output_tile"])) }, "Rows {coord:?}");
        }
    }
}
