//! Decode throughput of the integer engine at a real Qwen geometry.
//!
//! The number this prints did not exist. `base0-class-sizing` prices a class in *court* terms
//! (ladder depth, leaf counts) and nothing measured what the engine costs to RUN, so "the CPU
//! class is not practical" was a belief rather than a measurement. Anything that follows — a GPU
//! backend, a wider tile, a different quantisation — has to be argued against this baseline.
//!
//! The weights are `derive_deterministic`, not a trained model: throughput is a function of the
//! SHAPE, and an int8 multiply-accumulate costs the same whatever the operand means. What this
//! cannot measure is quality, and it does not claim to.
//!
//! ```text
//! cargo run --release -p misaka-palw-base0 --example base0-throughput -- [layers] [tokens] [w8a8|w8a16]
//! ```
//!
//! Both tiers run the same geometry, so the second number is what the wider activation costs.

use misaka_palw_base0::artifact::{Base0ArtifactV1, Base0ShapeV1};
use misaka_palw_base0::engine::{Base0Engine, KvCache};
use misaka_palw_base0::engine_a16::{A16Cache, A16Engine, derived_a16_store};

fn main() {
    let mut args = std::env::args().skip(1);
    let layers: usize = args.next().and_then(|v| v.parse().ok()).unwrap_or(28);
    let tokens: usize = args.next().and_then(|v| v.parse().ok()).unwrap_or(16);
    let tier = args.next().unwrap_or_else(|| "w8a8".to_string());

    // Qwen2.5-1.5B, from `palw_qwen25_profile::QWEN25_1_5B`. `max_position` is cut to what this
    // run needs: the rotary table is generated by CORDIC and 4,096 positions is setup cost the
    // measurement is not about.
    let shape = Base0ShapeV1 {
        n_layers: layers,
        n_heads: 12,
        n_kv_heads: 2,
        d_head: 128,
        d_ff: 8960,
        vocab: 151_936,
        max_position: (tokens + 8).max(64),
        // The class's own rotary base and RMS epsilon, from `palw_qwen25_profile`.
        ln_theta_gen_q: misaka_palw_base0::artifact::LN_THETA_10000_GEN_Q,
        eps_q: 1,
    };
    let d_model = shape.n_heads * shape.d_head;

    // Multiply-accumulates per decoded token, counted from the shape rather than timed, so the
    // rate below is a rate of arithmetic and not of wall-clock guessing. Attention against the
    // cache is excluded: it grows with position and would make the per-token figure depend on
    // where in the run it was taken.
    let per_layer = 2 * d_model * d_model                              // q, o
        + 2 * d_model * (shape.n_kv_heads * shape.d_head)              // k, v
        + 3 * d_model * shape.d_ff; // gate, up, down
    let macs_per_token = layers * per_layer + shape.vocab * d_model; // + unembedding

    let built = std::time::Instant::now();
    let artifact = Base0ArtifactV1::derive_deterministic(shape, 0x9E37_79B9_7F4A_7C15).expect("a Qwen2.5-1.5B shape is valid");
    let weights_bytes = (layers * per_layer + 2 * shape.vocab * d_model) as f64;
    eprintln!(
        "built {layers}-layer artifact in {:.1} s ({:.2} GiB of int8 weights)",
        built.elapsed().as_secs_f64(),
        weights_bytes / (1024.0 * 1024.0 * 1024.0)
    );

    // One token outside the measurement in either tier: the first touch of a 1.7 GiB weight set
    // is page-fault time, and reporting it as decode cost would understate the engine by a factor
    // nobody could reproduce on a warm machine.
    let mut worst = std::time::Duration::ZERO;
    let elapsed = match tier.as_str() {
        "w8a8" => {
            let engine = Base0Engine::new(&artifact);
            let mut cache = KvCache::new(&artifact);
            engine.forward_token(&mut cache, 1, 0).expect("the warm-up token decodes");
            let started = std::time::Instant::now();
            for position in 1..=tokens {
                let one = std::time::Instant::now();
                engine.forward_token(&mut cache, position % 1000, position).expect("the token decodes");
                worst = worst.max(one.elapsed());
            }
            started.elapsed()
        }
        "w8a16" => {
            let artifact =
                artifact.clone().with_a16_params(derived_a16_store(&shape)).expect("the derived store is sorted and unique");
            let engine = A16Engine::new(&artifact).expect("the derived store resolves every row");
            let mut cache = A16Cache::new(shape.n_layers);
            engine.forward_token(&mut cache, 1, 0).expect("the warm-up token decodes");
            let started = std::time::Instant::now();
            for position in 1..=tokens {
                let one = std::time::Instant::now();
                engine.forward_token(&mut cache, position % 1000, position).expect("the token decodes");
                worst = worst.max(one.elapsed());
            }
            started.elapsed()
        }
        other => panic!("unknown tier {other}: expected w8a8 or w8a16"),
    };

    let per_token = elapsed.as_secs_f64() / tokens as f64;
    println!("tier              {tier}");
    println!("layers            {layers}");
    println!("tokens            {tokens}");
    println!("per token         {:.1} ms   (worst {:.1} ms)", per_token * 1e3, worst.as_secs_f64() * 1e3);
    println!("throughput        {:.2} tok/s", 1.0 / per_token);
    println!(
        "arithmetic        {:.2} GMAC/token → {:.2} GMAC/s",
        macs_per_token as f64 / 1e9,
        macs_per_token as f64 / 1e9 / per_token
    );
    if layers != 28 {
        let full = (28 * per_layer + shape.vocab * d_model) as f64 / macs_per_token as f64 * per_token;
        println!("extrapolated 28L  {:.1} ms/token → {:.2} tok/s", full * 1e3, 1.0 / full);
    }
}
