# deploy-t12/pinner-lib.sh — the host pinner unit (int-10.2 D1). Sourced by lib.sh, never executed.
#
# On a host whose install-<host>.sh sets HOST_PINNER=1 (the multi-seat hosts: 5.104, ibm), one more unit,
# misaka-palw-pinner.service, runs `kaspad --palw-host-pinner`: it locks the class artifacts the seats replay in
# place — the 8k .palwart and, with Phase H, the IR container — in RAM ONCE for the host, in its OWN memory cgroup,
# before the seats start (Type=notify: systemd hears READY once every file is locked, and every seat's unit Wants= it
# and is ordered After= it). A page-cache page is charged to the cgroup that first faults it in, so the artifacts'
# 1.7-3.4 GiB are then the pinner's, not whichever seat loaded first: the seats keep their MemoryMax and share as
# they are, and their ledgers' cgroup terms carry no artifact (docs/design/palw/t12-replay-memory-1001.md §5).
#
# The pinner is never a dependency. Each seat still locks the same files itself (its own pin; free — the pages are
# resident), a seat starts without a pinner (Wants=, not Requires=), and stopping the pinner changes nothing for a
# running seat. A pinner that does not come up is a warning everywhere below, never a stop: the charge then lands on
# the first seat to load the files, as in int-10.2 without the unit.
#
# Its lifecycle follows the seats': `stage` writes $REL/launch/pinner.sh and $REL/units/misaka-palw-pinner.service;
# `upgrade` installs and (re)starts it BEFORE the first seat restarts (a seat that restarts behind a running pinner
# faults none of the pages: its old cgroup's charge passes to the parent slice, and the pinner's lock keeps them
# resident) and saves what was there for `upgrade-rollback`; `switch` / `rollback` (regenesis) install / remove it;
# `check` prints it and the host ledger.

PINNER_UNIT=misaka-palw-pinner

pinner_on() { [ "${HOST_PINNER:-0}" = 1 ]; }
pinner_rid() { echo "${RID:-$REV}"; }
pinner_launch_path() { echo "$REL/launch/pinner.sh"; }
pinner_staged_unit() { echo "$REL/units/$PINNER_UNIT.service"; }
pinner_unit_path() { echo "/etc/systemd/system/$PINNER_UNIT.service"; }
pinner_saved_path() { echo "$STATE_DIR/upgrade-$(pinner_rid)/$PINNER_UNIT.unit.before"; }

# pinner_unit_deps — the [Unit] lines every seat's unit / drop-in carries on a pinner host, each after a newline, so
# the unit writers append it to their StartLimitBurst= line and a plain host's unit is byte for byte what it was
pinner_unit_deps() {
    pinner_on || return 0
    printf '\nWants=%s.service\nAfter=%s.service' "$PINNER_UNIT" "$PINNER_UNIT"
}

pinner_args() { # fills PARGS
    PARGS=(--palw-host-pinner "--palw-class-artifact=$ART_8K")
    if [ -n "${ART_PH:-}" ]; then PARGS+=("--palw-class-artifact=$ART_PH"); fi
    if [ -n "${HOST_LEDGER_DIR:-}" ]; then PARGS+=("--palw-host-ledger-dir=$HOST_LEDGER_DIR"); fi
}

write_pinner_launch() {
    pinner_args
    local q a
    q=""
    for a in "${PARGS[@]}"; do q+="  $(printf '%q' "$a") \\"$'\n'; done
    mkdir -p "$REL/launch"
    atomic_write "$(pinner_launch_path)" 0755 <<EOF
#!/bin/bash
# testnet-12 PALW host pinner (int-10.2 D1), release $(pinner_rid). GENERATED by deploy-t12/pinner-lib.sh on $TS.
# Locks the class artifacts this host's seats replay in place, ONCE for the host, in this unit's own memory cgroup.
# Do not edit in place: regenerate with \`install-<host>.sh stage\`. \`$(pinner_launch_path) --check\` validates the
# binary, every flag and every file without starting anything.
set -u
BIN=$REL/bin/kaspad
EXPECT_SHA=$KASPAD_SHA256
got=\$(sha256sum "\$BIN" 2>/dev/null | cut -d' ' -f1)
if [ "\$got" != "\$EXPECT_SHA" ]; then echo "[launch pinner] binary \$BIN sha256 \${got:-missing} != \$EXPECT_SHA — refusing (exit 78)"; exit 78; fi
ARGS=(
$q)
envbad=\$(env | grep -oE '^(KASPAD|MISAKA_PALW|PALW)_[A-Z0-9_]*' | tr '\\n' ' ')
if [ -n "\$envbad" ]; then echo "[launch pinner] environment carries \$envbad— the command line above is the pinner's whole configuration — refusing (exit 78)"; exit 78; fi
HELP=\$("\$BIN" --help 2>&1)
for a in "\${ARGS[@]}"; do
  f=\${a%%=*}
  case "\$f" in --*) grep -qE -- "(^|[[:space:],])\${f}([[:space:]=,<\\[]|\$)" <<<"\$HELP" || { echo "[launch pinner] \$BIN does not know \$f (a release before int-10.2) — refusing (exit 78)"; exit 78; } ;; esac
  case "\$a" in --palw-class-artifact=*) [ -f "\${a#*=}" ] || { echo "[launch pinner] \${a#*=} is missing — refusing (exit 78)"; exit 78; } ;; esac
done
if [ "\${1:-}" = "--check" ]; then echo "[launch pinner] OK: sha \${got:0:16}…, \${#ARGS[@]} args, every flag known, every artifact present"; exit 0; fi
exec "\$BIN" "\${ARGS[@]}"
EOF
}

write_pinner_unit() {
    mkdir -p "$REL/units"
    atomic_write "$(pinner_staged_unit)" 0644 <<EOF
# deploy-t12 pinner unit, release $(pinner_rid). Roll back = stop + disable + delete this file + daemon-reload (the seats keep their own pins).
[Unit]
Description=MISAKA testnet-12 PALW host pinner (int-10.2 D1, release $(pinner_rid)): the class artifacts locked in RAM once for this host's seats
After=local-fs.target
StartLimitIntervalSec=900
StartLimitBurst=4
[Service]
Type=notify
NotifyAccess=main
Environment=
EnvironmentFile=
WorkingDirectory=$REL
ExecStart=$(pinner_launch_path)
Restart=on-failure
RestartSec=20
RestartPreventExitStatus=78
TimeoutStartSec=900
TimeoutStopSec=30
StandardOutput=journal
StandardError=journal
MemoryHigh=infinity
MemoryMax=infinity
LimitMEMLOCK=infinity
[Install]
WantedBy=multi-user.target
EOF
}

# stage_pinner — after stage_nodes: the pinner's launch script and unit under $REL (nothing under /etc changes)
stage_pinner() {
    pinner_on || return 0
    [ -n "${ART_8K:-}" ] || die "HOST_PINNER=1 needs ART_8K (fleet.env)"
    write_pinner_launch; write_pinner_unit
    "$(pinner_launch_path)" --check || die "the pinner's launch check failed — nothing was switched"
    say "  pinner: $(pinner_launch_path), unit $(pinner_staged_unit)  (nothing under /etc changed)"
}

# pinner_status_line — its state, its last 'holding' line, and what is charged to its cgroup
pinner_status_line() {
    local cg cur hold
    cg=$(systemctl show -p ControlGroup --value "$PINNER_UNIT" 2>/dev/null || true)
    if [ -n "$cg" ] && [ -r "/sys/fs/cgroup$cg/memory.current" ]; then cur="$(( $(cat "/sys/fs/cgroup$cg/memory.current") / 1048576 )) MiB charged to its cgroup"; else cur="no cgroup"; fi
    hold=$(journalctl -u "$PINNER_UNIT" -n 400 --no-pager -o cat 2>/dev/null | grep -oE 'holding [0-9]+ of [0-9]+ file\(s\), [0-9.]+ GiB' | tail -1 || true)
    echo "$(systemctl show -p ActiveState,SubState --value "$PINNER_UNIT" 2>/dev/null | tr '\n' ' ')· ${hold:-no 'holding' line yet} · $cur"
}

# check_pinner — read-only: the pinner and, where the host names one, the host ledger as its file says it now
check_pinner() {
    pinner_on || [ -n "${HOST_LEDGER_DIR:-}" ] || return 0
    if pinner_on; then say "== pinner $PINNER_UNIT: $(pinner_status_line)"; fi
    if [ -n "${HOST_LEDGER_DIR:-}" ]; then
        if [ -r "$HOST_LEDGER_DIR/host-ledger-v1" ]; then
            say "   host ledger $HOST_LEDGER_DIR: $(awk '$1=="n"{k[$5]++} $1=="r"{r++; b+=$6} $1=="p"{f[$5" "$6" "$7]=$7} END{n=0; s=0; for(x in f){n++; s+=f[x]} printf "nodes %d, pinner %d, %d reservation(s) of %d MiB, %d distinct pinned file(s) of %d MiB", k["node"], k["pinner"], r, b/1048576, n, s/1048576}' "$HOST_LEDGER_DIR/host-ledger-v1") (as written; a gone process's lines leave at the next grant)"
        else
            warn "HOST_LEDGER_DIR=$HOST_LEDGER_DIR holds no host-ledger-v1 yet — no node on this host has registered (an older release, or the flag is not on their command lines)"
        fi
    fi
}

# upgrade_pinner_preflight — read-only, before anything stops
upgrade_pinner_preflight() {
    pinner_on || return 0
    "$(pinner_launch_path)" --check || die "the pinner's launch check failed (this release) — nothing was upgraded"
    [ -f "$(pinner_staged_unit)" ] || die "staged $(pinner_staged_unit) missing — run \`stage\` first"
    if [ -f "$(pinner_unit_path)" ] && ! grep -q '^# deploy-t12 pinner unit' "$(pinner_unit_path)"; then
        die "$(pinner_unit_path) exists and is not the kit's — nothing was upgraded"
    fi
    say "  pinner $PINNER_UNIT: $(systemctl is-active "$PINNER_UNIT" 2>/dev/null || true) now; this release's unit is staged"
}

# upgrade_pinner — this release's pinner installed and (re)started BEFORE the first seat restarts; what was there is
# saved for upgrade-rollback (the unit, or a marker that there was none).
upgrade_pinner() {
    pinner_on || return 0
    local cur saved; cur=$(pinner_unit_path); saved=$(pinner_saved_path)
    if cmp -s "$(pinner_staged_unit)" "$cur" && systemctl is-active --quiet "$PINNER_UNIT"; then
        say "pinner: already runs this release's unit — not restarted"; return 0
    fi
    if [ ! -e "$saved" ] && [ ! -e "$saved.absent" ]; then
        if [ -f "$cur" ]; then run cp -p "$cur" "$saved"; else run touch "$saved.absent"; fi
    fi
    run install -m 0644 "$(pinner_staged_unit)" "$cur"
    upgrade_log "INSTALLED $PINNER_UNIT $cur from $(pinner_staged_unit)"
    run systemctl daemon-reload
    run systemctl enable "$PINNER_UNIT"
    run systemctl reset-failed "$PINNER_UNIT" 2>/dev/null || true
    say "pinner: (re)starting $PINNER_UNIT — systemctl returns once every artifact is locked (Type=notify)"
    if run systemctl restart "$PINNER_UNIT"; then
        if [ "$DRY_RUN" != 1 ]; then say "  pinner: $(pinner_status_line)"; fi
        upgrade_log "STARTED $PINNER_UNIT"
    else
        warn "the pinner did not come up — the seats pin the files themselves, and the charge lands on the first seat to load them (journal below)"
        journalctl -u "$PINNER_UNIT" -n 20 --no-pager -o cat >&2 || true
    fi
}

# upgrade_rollback_pinner — after the seats are back: the pinner unit that was there before `upgrade`, or none
upgrade_rollback_pinner() {
    local cur saved; cur=$(pinner_unit_path); saved=$(pinner_saved_path)
    if [ -f "$saved" ]; then
        say "pinner: back to its pre-upgrade unit"
        run install -m 0644 "$saved" "$cur"
        run systemctl daemon-reload
        run systemctl restart "$PINNER_UNIT" || warn "the pre-upgrade pinner did not come up (journalctl -u $PINNER_UNIT)"
        upgrade_log "ROLLEDBACK $PINNER_UNIT"
    elif [ -e "$saved.absent" ]; then
        say "pinner: there was none before the upgrade — stopped, disabled and removed (the seats keep their own pins)"
        run systemctl stop "$PINNER_UNIT" || true
        run systemctl disable "$PINNER_UNIT" || true
        run rm -f "$cur"
        run systemctl daemon-reload
        upgrade_log "REMOVED $PINNER_UNIT"
    fi
}

# switch_pinner — a regenesis switch: installed and started before the first node (recorded for `rollback`)
switch_pinner() {
    pinner_on || return 0
    if [ -f "$(pinner_unit_path)" ] && ! grep -q '^# deploy-t12 pinner unit' "$(pinner_unit_path)"; then die "$(pinner_unit_path) exists and is not ours"; fi
    [ -f "$(pinner_staged_unit)" ] || die "staged $(pinner_staged_unit) missing — run \`stage\` first"
    install -m 0644 "$(pinner_staged_unit)" "$(pinner_unit_path)"
    record_state "PINNER $(pinner_unit_path)"
    systemctl daemon-reload
    systemctl enable "$PINNER_UNIT" >/dev/null 2>&1 || true
    if systemctl restart "$PINNER_UNIT"; then say "  pinner: $(pinner_status_line)"; else warn "the pinner did not come up — the seats pin the files themselves"; fi
}

# rollback_pinner — undo switch_pinner
rollback_pinner() {
    grep -q '^PINNER ' "$STATE_DIR/switch-$REV.log" 2>/dev/null || return 0
    systemctl stop "$PINNER_UNIT" 2>/dev/null || true
    systemctl disable "$PINNER_UNIT" >/dev/null 2>&1 || true
    if grep -q '^# deploy-t12 pinner unit' "$(pinner_unit_path)" 2>/dev/null; then rm -f "$(pinner_unit_path)"; say "  removed $(pinner_unit_path)"; fi
    systemctl daemon-reload
}
