[package]
name = "palw-real-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "palw-real-provider"
path = "src/main.rs"

[dependencies]
hex.workspace = true
kaspa-consensus-core.workspace = true
kaspa-hashes.workspace = true
kaspa-pq-validator-core.workspace = true
misaka-palw.workspace = true
serde.workspace = true
serde_json.workspace = true
