//! **Lane H's storage-format axis**: quant-format descriptors written by a THIRD PARTY (`tools/corpus/formats/*.json`, generated by
//! `tools/corpus/formats/gen_formats.py`) and loaded through the public registry with no code added.
//!
//! What each test says:
//!
//! 1. every descriptor parses, compiles and passes its own test vectors (`QuantFormat::from_json` refuses one that does not);
//! 2. the registry extended with them reads the `quant_method` they announce, and a configuration the descriptor does not describe
//!    (bitsandbytes 4-bit) is refused by name;
//! 3. the finding FR-33: MLX's own `quantization` configuration carries no `quant_method`, so the registry cannot select the
//!    descriptor from it and the refusal ("quant_method=unknown has no descriptor ... supply one") is misleading — supplying the
//!    descriptor does not help. **Closed (HFX, 2026-10-10, `MLX_QUANT_V1`)**: the reader names an MLX block `mlx`
//!    (`prequant::quant_block`), and `MLX_AFFINE` is now a BUILT-IN descriptor made from MLX's own quantiser (a virtual format:
//!    the codes are served as the float `.weight`, 2–8 bits including the word-straddling 3 / 5 / 6). The third-party
//!    transcription here is no longer added beside it (it has the built-in's name); its vectors are decoded by the built-in and
//!    must agree, bit for bit — two independent readings of MLX's layout.
//!
//! The vectors are a numpy transcription of each library's documented layout (the libraries are not available offline): see
//! `gen_formats.py` for what that does and does not prove.

use misaka_palw_tir_lower::prequant::parse_quant_config_with;
use misaka_palw_tir_lower::quantfmt::{QuantFormat, QuantRegistry};
use serde_json::json;
use std::path::PathBuf;

fn dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tools/corpus/formats")
}

fn third_party() -> Vec<(String, QuantFormat)> {
    let mut v = Vec::new();
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir()).expect("tools/corpus/formats").filter_map(|e| e.ok().map(|e| e.path())).filter(|p| p.extension().is_some_and(|x| x == "json")).collect();
    files.sort();
    for p in files {
        let text = std::fs::read_to_string(&p).expect("read");
        let f = QuantFormat::from_json(&text).unwrap_or_else(|e| panic!("{}: {e}", p.display()));
        v.push((p.file_stem().unwrap().to_string_lossy().to_string(), f));
    }
    v
}

fn registry() -> QuantRegistry {
    // A third-party descriptor the built-in pack has since promoted (MLX_AFFINE) is not added a second time under its name.
    let builtin = QuantRegistry::builtin();
    let extra = third_party().into_iter().map(|(_, f)| f).filter(|f| builtin.named(f.name()).is_none()).collect();
    builtin.with(extra).expect("no clash with the built-in pack")
}

#[test]
fn every_third_party_descriptor_passes_its_own_vectors() {
    let fs = third_party();
    assert!(!fs.is_empty(), "no descriptors found");
    for (name, f) in &fs {
        assert!(!f.desc.tests.is_empty(), "{name}: no test vector");
        eprintln!("{name}: {} ({} vectors, digest {})", f.name(), f.desc.tests.len(), &f.digest_hex()[..16]);
    }
}

#[test]
fn the_registry_with_them_reads_their_methods_and_refuses_what_they_do_not_describe() {
    let reg = registry();
    assert_eq!(reg.config("mlx", None).map(|f| f.name()), Some("MLX_AFFINE"));
    // MLX, announced the way a converter would be told to: with a quant_method.
    let ok = parse_quant_config_with(&json!({"quant_method": "mlx", "bits": 4, "group_size": 64}), "X", "llama", &reg);
    assert!(ok.is_ok(), "{ok:?}");
    // an MLX mode this descriptor does not describe
    let e = parse_quant_config_with(&json!({"quant_method": "mlx", "bits": 4, "group_size": 32, "mode": "mxfp4"}), "X", "llama", &reg).expect_err("mxfp4 mode");
    assert!(e.to_string().contains("affine"), "{e}");
    // bitsandbytes 8-bit is read (the built-in descriptor: it was promoted from this directory); so is 4-bit nf4
    let int8 = json!({"quant_method": "bitsandbytes", "load_in_8bit": true, "load_in_4bit": false, "llm_int8_threshold": 6.0, "llm_int8_has_fp16_weight": false});
    assert!(parse_quant_config_with(&int8, "X", "llama", &reg).is_ok());
    let nf4 = json!({"quant_method": "bitsandbytes", "load_in_8bit": false, "load_in_4bit": true, "bnb_4bit_quant_type": "nf4", "bnb_4bit_use_double_quant": true});
    assert!(parse_quant_config_with(&nf4, "X", "llama", &reg).is_ok(), "nf4 is a built-in descriptor now");
}

#[test]
fn fr33_mlx_announces_itself_without_a_quant_method_and_the_reader_names_it() {
    let reg = registry();
    // What an mlx-community config.json carries: {"quantization": {"group_size": 64, "bits": 4}} (and the same under quantization_config).
    // The descriptor lookup alone still cannot select it — a block with no quant_method is `unknown` there …
    let e = parse_quant_config_with(&json!({"group_size": 64, "bits": 4}), "X", "llama", &reg).expect_err("no quant_method");
    let m = e.to_string();
    assert!(m.contains("unknown"), "the refusal names quant_method=unknown: {m}");
    // … and the reader names it (MLX_QUANT_V1): the configuration's block, under either key, is read as MLX's.
    let root = json!({"quantization": {"group_size": 64, "bits": 4}});
    let q = misaka_palw_tir_lower::prequant::quant_block(root.as_object().expect("object")).expect("reads").expect("a block");
    let c = parse_quant_config_with(&q, "X", "llama", &reg).expect("MLX's block reads");
    assert!(c.fmt.label().starts_with("MLX_AFFINE"), "{}", c.fmt.label());
}

/// The third-party transcription of MLX's layout (`mlx_affine.json`, numpy, from MLX's documentation as recalled) and the built-in
/// descriptor (from MLX's own quantiser) are two independent readings of the same format: every transcribed vector decodes through
/// the built-in to the transcription's values, bit for bit.
#[test]
fn the_promoted_mlx_descriptor_decodes_the_transcribed_vectors_alike() {
    use misaka_palw_tir_lower::quantfmt::tensors::RoleTensor;
    let unhex = |h: &str| -> Result<Vec<u8>, std::num::ParseIntError> { (0..h.len()).step_by(2).map(|i| u8::from_str_radix(&h[i..i + 2], 16)).collect() };
    let (_, transcribed) = third_party().into_iter().find(|(n, _)| n == "mlx_affine").expect("the transcription");
    let builtin = QuantRegistry::builtin().named("MLX_AFFINE").expect("built-in").clone();
    assert_ne!(builtin.digest(), transcribed.digest(), "two descriptors, one name");
    let v = builtin.as_virtual().expect("a virtual format");
    for (n, t) in transcribed.desc.tests.iter().enumerate() {
        let roles: Vec<Option<RoleTensor>> = v
            .roles()
            .map(|(r, _, _)| {
                let tr = t.roles.get(r).expect("every role of the vector");
                Some(RoleTensor { shape: tr.shape.clone(), dtype: tr.dtype.clone(), data: unhex(&tr.hex).expect("hex") })
            })
            .collect();
        let params = v.read_config(t.config.as_ref().expect("a config")).expect("reads").params;
        let shape = v.shape(&roles, &params).expect("shape");
        let got = v.decode_range(&roles, &params, 0..shape.iter().product()).expect("decodes");
        let want: Vec<f32> = unhex(&t.values_f32_hex).expect("hex").chunks_exact(4).map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]])).collect();
        assert_eq!(got.len(), want.len(), "vector {n}");
        for (k, (g, w)) in got.iter().zip(&want).enumerate() {
            assert!(g.to_bits() == w.to_bits() || (*g == 0.0 && *w == 0.0), "vector {n} [{k}]: built-in {g}, transcription {w}");
        }
    }
}
