//! **The golden vectors of RFC-0003 Part I, regenerated and byte-compared.**
//!
//! * `consensus-vectors/rand-v1/domains.json` — the domain table, the rand-set descriptor and id,
//!   and both tables' pins (with samples of the Gaussian table);
//! * `consensus-vectors/rand-v1/words.json` — R's words for every domain: seeds, steps, positions and
//!   lane ranges crossing block edges, with each touched block's digest, and the refusals;
//! * `consensus-vectors/rand-v1/normal.json` — `Normal` draws of every noise domain;
//! * `consensus-vectors/output-v1/digests.json` — canonical bytes, tile leaves, `output_root` and
//!   tile proofs for every output kind, including a ragged last tile and a promoted odd leaf, and the
//!   refusals.
//!
//! The test regenerates every file in memory and requires the bytes on disk to be identical.
//! `PALW_GEN_BLESS=1 cargo test -p misaka-palw-gen --test vectors` rewrites them — which is a change
//! of the vectors and is reviewed as a change of the semantics.

use std::path::PathBuf;

use misaka_palw_gen::output::{
    OutputKindV1, OutputSpecV1, output_leaves_v1, output_root_v1, output_tile_proof_v1, output_tiles_v1, verify_output_tile_v1,
};
use misaka_palw_gen::rand::*;
use serde::Serialize;

const SPEC: &str = "docs/rfc/0003-palw-generative-model-classes.md §I.1, §I.3; docs/spec/palw/04b-tensor-ir.md §15";

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..").join("consensus-vectors")
}

fn check_or_bless(rel: &str, json: String) {
    let path = vectors_dir().join(rel);
    let json = json + "\n";
    if std::env::var("PALW_GEN_BLESS").as_deref() == Ok("1") {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &json).unwrap();
        return;
    }
    let on_disk = std::fs::read_to_string(&path).unwrap_or_else(|_| panic!("{} is missing; run with PALW_GEN_BLESS=1", path.display()));
    assert!(on_disk == json, "{} differs from the regenerated vectors", path.display());
}

fn seed_of(byte: u8) -> Seed {
    [byte; 32]
}

/// A seed with every byte different: bytes `i·37 + 11`.
fn seed_ramp() -> Seed {
    let mut s = [0u8; 32];
    for (i, b) in s.iter_mut().enumerate() {
        *b = (i as u8).wrapping_mul(37).wrapping_add(11);
    }
    s
}

// ---- rand-v1/domains.json --------------------------------------------------------------------------

#[derive(Serialize)]
struct DomainJson {
    id: u16,
    name: String,
    key: String,
    word_bits: u32,
    words_per_digest: u32,
    layout: String,
    step: String,
}

#[derive(Serialize)]
struct GaussJson {
    len: usize,
    key: String,
    digest_hex: String,
    file: String,
    min: i32,
    max: i32,
    /// `[index, value]` pairs: both ends, the centre, the quartiles and a spread of others.
    samples: Vec<(u32, i32)>,
}

#[derive(Serialize)]
struct DomainsFileJson {
    format: String,
    spec: String,
    rand_set_descriptor: String,
    rand_set_id_hex: String,
    gumbel_q24_v1_digest_hex: String,
    gauss_q24_v1: GaussJson,
    domains: Vec<DomainJson>,
}

#[test]
fn domains() {
    let domains = RAND_DOMAINS_V1
        .iter()
        .map(|d| DomainJson {
            id: d.id,
            name: d.name.into(),
            key: String::from_utf8(d.key.to_vec()).unwrap(),
            word_bits: d.word_bits,
            words_per_digest: d.words_per_digest(),
            layout: format!("{:?}", d.layout),
            step: format!("{:?}", d.step),
        })
        .collect();
    let mut idx: Vec<u32> = vec![0, 1, 2, 16_383, 16_384, 32_766, 32_767, 32_768, 32_769, 49_151, 49_152, 65_533, 65_534, 65_535];
    let mut x = 12_345u32;
    for _ in 0..18 {
        x = x.wrapping_mul(1_103_515_245).wrapping_add(12_345) & 0xffff;
        idx.push(x);
    }
    idx.sort();
    idx.dedup();
    let file = DomainsFileJson {
        format: "palw-rand-v1/domain-vectors/1".into(),
        spec: SPEC.into(),
        rand_set_descriptor: rand_set_descriptor_v1(),
        rand_set_id_hex: hex(&rand_set_id_v1()),
        gumbel_q24_v1_digest_hex: GUMBEL_Q24_V1_DIGEST_HEX.into(),
        gauss_q24_v1: GaussJson {
            len: GAUSS_Q24_V1_LEN,
            key: String::from_utf8(GAUSS_Q24_V1_KEY.to_vec()).unwrap(),
            digest_hex: hex(&gauss_q24_v1_digest()),
            file: "misaka-palw-gen/data/gauss-q24-v1.bin (generated by scripts/palw-gauss-table.py)".into(),
            min: GAUSS_Q24_V1_MIN,
            max: GAUSS_Q24_V1_MAX,
            samples: idx.iter().map(|i| (*i, gauss_q24_v1(*i as u16))).collect(),
        },
        domains,
    };
    check_or_bless("rand-v1/domains.json", serde_json::to_string_pretty(&file).unwrap());
}

// ---- rand-v1/words.json ----------------------------------------------------------------------------

#[derive(Serialize)]
struct WordsCaseJson {
    name: String,
    domain: u16,
    seed_hex: String,
    step: u32,
    position: u32,
    first_lane: u64,
    /// Every digest the lanes touch, in block order: `[counter, digest]` (the counter is the block,
    /// or the lane for domain 0).
    digests: Vec<(u64, String)>,
    words: Vec<u32>,
}

#[derive(Serialize)]
struct RefusalJson {
    name: String,
    domain: u16,
    step: u32,
    lanes: u64,
    expect_error: String,
}

#[derive(Serialize)]
struct WordsFileJson {
    format: String,
    spec: String,
    cases: Vec<WordsCaseJson>,
    refusals: Vec<RefusalJson>,
}

fn words_case(name: &str, domain: u16, seed: Seed, step: u32, position: u32, first_lane: u64, count: u64) -> WordsCaseJson {
    let d = &RAND_DOMAINS_V1[domain as usize];
    let w = d.words_per_digest() as u64;
    let words: Vec<u32> = (first_lane..first_lane + count).map(|l| rand_word_v1(domain, &seed, step, position, l).unwrap()).collect();
    let (b0, b1) = (first_lane / w, (first_lane + count - 1) / w);
    let digests = (b0..=b1).map(|b| (b, hex(&rand_digest_v1(d, &seed, step, position, b)))).collect();
    WordsCaseJson { name: name.into(), domain, seed_hex: hex(&seed), step, position, first_lane, digests, words }
}

#[test]
fn words() {
    let mut cases = Vec::new();
    // Domain 0 is D11: one digest per lane.
    cases.push(words_case("text-gumbel/zero-seed", TEXT_GUMBEL_V1, seed_of(0), 0, 0, 0, 6));
    cases.push(words_case("text-gumbel/ramp-seed/row-3", TEXT_GUMBEL_V1, seed_ramp(), 0, 3, 151_930, 6));
    for d in RAND_DOMAINS_V1.iter().skip(1) {
        let w = d.words_per_digest() as u64;
        let step = if matches!(d.step, RandStepRuleV1::PerStep | RandStepRuleV1::Declared) { 5 } else { 0 };
        // Two whole blocks and a word of the third: the block edges are where an off-by-one would live.
        cases.push(words_case(&format!("{}/zero-seed", d.name), d.id, seed_of(0), 0, 0, 0, 2 * w + 1));
        cases.push(words_case(&format!("{}/ramp-seed/position-2", d.name), d.id, seed_ramp(), step, 2, w - 3, 6));
    }
    let refusals = vec![
        RefusalJson { name: "unknown-domain".into(), domain: 8, step: 0, lanes: 1, expect_error: "UnknownDomain".into() },
        RefusalJson { name: "step-on-a-zero-rule".into(), domain: 1, step: 1, lanes: 1, expect_error: "StepNotAllowed".into() },
        RefusalJson { name: "step-on-domain-0".into(), domain: 0, step: 1, lanes: 1, expect_error: "StepNotAllowed".into() },
        RefusalJson { name: "more-lanes-than-a-tensor".into(), domain: 1, step: 0, lanes: (1 << 28) + 1, expect_error: "TooManyLanes".into() },
    ];
    for r in &refusals {
        let e = rand_words_v1(r.domain, &seed_of(0), r.step, 0, r.lanes).unwrap_err();
        assert!(format!("{e:?}").starts_with(&r.expect_error), "{}: {e:?}", r.name);
    }
    let file = WordsFileJson { format: "palw-rand-v1/word-vectors/1".into(), spec: SPEC.into(), cases, refusals };
    check_or_bless("rand-v1/words.json", serde_json::to_string_pretty(&file).unwrap());
}

// ---- rand-v1/normal.json ---------------------------------------------------------------------------

#[derive(Serialize)]
struct NormalCaseJson {
    name: String,
    domain: u16,
    seed_hex: String,
    step: u32,
    position: u32,
    /// The declared input shape; the values are its lanes `0..Π shape`, row-major.
    shape: Vec<u32>,
    values: Vec<i64>,
}

#[derive(Serialize)]
struct NormalFileJson {
    format: String,
    spec: String,
    cases: Vec<NormalCaseJson>,
}

#[test]
fn normal() {
    let mut cases = Vec::new();
    let mut add = |name: &str, domain: u16, seed: Seed, step: u32, position: u32, shape: Vec<u32>| {
        let n = shape.iter().map(|d| *d as u64).product();
        let values = rand_values_v1(domain, RandDistV1::Normal, &seed, step, position, n).unwrap();
        cases.push(NormalCaseJson { name: name.into(), domain, seed_hex: hex(&seed), step, position, shape, values });
    };
    add("image-init/[4,4,4]/seed-0x07", IMAGE_INIT_NOISE_V1, seed_of(7), 0, 0, vec![4, 4, 4]);
    add("image-init/[4,4,4]/seed-0x07/image-1", IMAGE_INIT_NOISE_V1, seed_of(7), 0, 1, vec![4, 4, 4]);
    add("image-step/[2,3,5]/step-9", IMAGE_STEP_NOISE_V1, seed_ramp(), 9, 0, vec![2, 3, 5]);
    add("audio-init/[2,40]", AUDIO_INIT_NOISE_V1, seed_ramp(), 0, 0, vec![2, 40]);
    add("audio-step/[2,8]/step-1", AUDIO_STEP_NOISE_V1, seed_ramp(), 1, 0, vec![2, 8]);
    add("video-init/[2,2,3,3]", VIDEO_INIT_NOISE_V1, seed_of(0xff), 0, 0, vec![2, 2, 3, 3]);
    add("video-step/[2,2,2,2]/step-4", VIDEO_STEP_NOISE_V1, seed_of(0xff), 4, 3, vec![2, 2, 2, 2]);
    let file = NormalFileJson { format: "palw-rand-v1/normal-vectors/1".into(), spec: SPEC.into(), cases };
    check_or_bless("rand-v1/normal.json", serde_json::to_string_pretty(&file).unwrap());
}

// ---- output-v1/digests.json ------------------------------------------------------------------------

#[derive(Serialize)]
struct SpecJson {
    kind: u8,
    kind_name: String,
    shape: Vec<u32>,
    meta_hex: String,
    borsh_hex: String,
}

#[derive(Serialize)]
struct ProofJson {
    tile: u64,
    tile_hex: String,
    path_hex: Vec<String>,
}

#[derive(Serialize)]
struct OutputCaseJson {
    name: String,
    spec: SpecJson,
    tile_len: u32,
    values: Vec<i64>,
    canonical_hex: String,
    tile_leaves_hex: Vec<String>,
    output_root_hex: String,
    proofs: Vec<ProofJson>,
}

#[derive(Serialize)]
struct OutputRefusalJson {
    name: String,
    kind: u8,
    shape: Vec<u32>,
    meta_hex: String,
    tile_len: u32,
    values: Vec<i64>,
    expect_error: String,
}

#[derive(Serialize)]
struct OutputFileJson {
    format: String,
    spec: String,
    cases: Vec<OutputCaseJson>,
    refusals: Vec<OutputRefusalJson>,
}

fn spec_json(s: &OutputSpecV1) -> SpecJson {
    SpecJson {
        kind: s.kind,
        kind_name: OutputKindV1::from_tag(s.kind).map(|k| k.name().to_string()).unwrap_or_default(),
        shape: s.shape.clone(),
        meta_hex: hex(&s.meta),
        borsh_hex: hex(&s.encode()),
    }
}

fn output_case(name: &str, spec: OutputSpecV1, tile_len: u32, values: Vec<i64>) -> OutputCaseJson {
    let canonical = spec.canonical_bytes(&values).unwrap();
    let tiles = output_tiles_v1(&spec, &values, tile_len).unwrap();
    let leaves = output_leaves_v1(&spec, &values, tile_len).unwrap();
    let root = output_root_v1(&spec, &values, tile_len).unwrap();
    let proofs = (0..tiles.len())
        .map(|t| {
            let path = output_tile_proof_v1(&leaves, t).unwrap();
            assert!(verify_output_tile_v1(&root, &spec, tile_len, t as u64, &tiles[t], &path), "{name}: tile {t}");
            ProofJson { tile: t as u64, tile_hex: hex(&tiles[t]), path_hex: path.iter().map(|h| hex(h)).collect() }
        })
        .collect();
    OutputCaseJson {
        name: name.into(),
        spec: spec_json(&spec),
        tile_len,
        values,
        canonical_hex: hex(&canonical),
        tile_leaves_hex: leaves.iter().map(|h| hex(h)).collect(),
        output_root_hex: hex(&root),
        proofs,
    }
}

#[test]
fn output_digests() {
    let ramp = |n: usize, lo: i64, hi: i64| -> Vec<i64> { (0..n as i64).map(|i| lo + (i * 97 + 13) % (hi - lo + 1)).collect() };
    let mut cases = Vec::new();
    // A 2×3 RGB image in 4-lane tiles: 18 lanes → 5 tiles, the last ragged (2 lanes), the fifth leaf promoted.
    cases.push(output_case("image/2x3/tile-4", OutputSpecV1::image_rgb8(2, 3), 4, ramp(18, 0, 255)));
    // The pixel extremes, one tile.
    cases.push(output_case("image/1x2/extremes", OutputSpecV1::image_rgb8(1, 2), 8, vec![0, 255, 0, 255, 0, 255]));
    cases.push(output_case("pcm/9x2/48k", OutputSpecV1::pcm_i16(9, 2, 48_000), 4, {
        let mut v = ramp(18, -32768, 32767);
        v[0] = -32768;
        v[1] = 32767;
        v
    }));
    cases.push(output_case("embedding/2x5/q16-normalised", OutputSpecV1::embedding_i32(2, 5, 16, true), 4, {
        let mut v = ramp(10, -65536, 65536);
        v[9] = i32::MIN as i64;
        v
    }));
    cases.push(output_case("video/2x1x2/30000-1001", OutputSpecV1::video_rgb8(2, 1, 2, 30_000, 1_001), 4, ramp(12, 0, 255)));
    cases.push(output_case("tensor-le/i16/[2,3]/q12", OutputSpecV1::tensor_le(1, vec![2, 3], 12), 4, ramp(6, -32768, 32767)));
    cases.push(output_case("tokens/7", OutputSpecV1::tokens(7), 4, vec![0, 1, 151_935, 42, 4_294_967_295, 7, 8]));
    let refusals = vec![
        ("pixel-above-255", OutputSpecV1::image_rgb8(1, 1), 4, vec![0, 256, 0], "Domain"),
        ("pixel-below-0", OutputSpecV1::image_rgb8(1, 1), 4, vec![-1, 0, 0], "Domain"),
        ("sample-outside-i16", OutputSpecV1::pcm_i16(1, 1, 8_000), 4, vec![32768], "Domain"),
        ("too-few-values", OutputSpecV1::image_rgb8(1, 2), 4, vec![0, 0, 0], "Count"),
        ("image-with-4-channels", OutputSpecV1 { kind: 1, shape: vec![1, 1, 4], meta: vec![] }, 4, vec![0; 4], "Shape"),
        ("unknown-kind", OutputSpecV1 { kind: 6, shape: vec![1], meta: vec![] }, 4, vec![0], "UnknownKind"),
        ("zero-sample-rate", OutputSpecV1::pcm_i16(1, 1, 0), 4, vec![0], "Meta"),
        ("zero-fps-denominator", OutputSpecV1::video_rgb8(1, 1, 1, 30, 0), 4, vec![0; 3], "Meta"),
        ("tensor-dtype-i64", OutputSpecV1::tensor_le(3, vec![1], 0), 4, vec![0], "Meta"),
        ("tile-len-3", OutputSpecV1::image_rgb8(1, 1), 3, vec![0; 3], "TileLen"),
        ("tile-len-65537", OutputSpecV1::image_rgb8(1, 1), 65_537, vec![0; 3], "TileLen"),
    ];
    let refusals = refusals
        .into_iter()
        .map(|(name, spec, tile_len, values, expect)| {
            let e = output_root_v1(&spec, &values, tile_len).unwrap_err();
            assert!(format!("{e:?}").starts_with(expect), "{name}: {e:?}");
            OutputRefusalJson {
                name: name.into(),
                kind: spec.kind,
                shape: spec.shape.clone(),
                meta_hex: hex(&spec.meta),
                tile_len,
                values,
                expect_error: expect.into(),
            }
        })
        .collect();
    let file = OutputFileJson { format: "palw-output-v1/digest-vectors/1".into(), spec: SPEC.into(), cases, refusals };
    check_or_bless("output-v1/digests.json", serde_json::to_string_pretty(&file).unwrap());
}
