#!/usr/bin/env python3
"""Generate RFC-0001 §A's consensus golden vectors (`consensus-vectors/fp-v4/`).

This is a SECOND implementation of the FP Job V4 decode pipeline, written from the RFC's text
(§A.2 / §A.3) and sharing nothing with the Rust one but the Gumbel table's generator
(`scripts/palw-gumbel-table.py`, ADR-0082 Decision 11). The vectors it writes are what the
sampler (consensus-core), the worker (misaka-palw-base0) and the panel (kaspad) tests all read, so
two independent readings of the frozen text have to agree before a single one passes.

  §A.3, as implemented below (every intermediate an unbounded Python int; every division floors):

    1. repeat     c > 0, v > 0 :  a = (v * 65536) // p        c > 0, v <= 0 :  a = (v * p) // 65536
                  c = 0        :  a = v
    2. freq/pres  b = a - c * f - (s if c > 0 else 0)
    3. bias       d = b + bias_j            (bias_j = 0 without an entry; a ban is not a bias)
    4. saturate   v'' = min(max(d, -2**31 + 1), 2**31 - 1)
    5. mask       A = {j admitted by the constraint} minus {j banned}; empty => stop
    6. select     argmax over A of  v'' * 2**24 + T * G_j              (T = 0: no noise term)
                  G_j = GUMBEL[top 13 bits of BLAKE2b-512_key=domain(seed || t_le32 || j_le64)]
                  ties to the lowest index
    7. stop       the committed answer's tail equals a stop sequence => stop here

Usage:  python3 scripts/palw-fp-v4-vectors.py            # (re)write consensus-vectors/fp-v4/*.json
        python3 scripts/palw-fp-v4-vectors.py --check    # exit 1 if a file on disk differs

`job_v4_encoding.json` is not written here: it pins the Rust wire encoding (borsh bytes and the
job hash) and is generated by `cargo test -p kaspa-consensus-core -- --ignored
regenerate_job_v4_encoding_vector`, then checked by every run of the non-ignored test.
"""

import argparse
import hashlib
import importlib.util
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "consensus-vectors", "fp-v4")

_spec = importlib.util.spec_from_file_location("gumbel", os.path.join(ROOT, "scripts", "palw-gumbel-table.py"))
_gumbel = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gumbel)
GUMBEL = _gumbel.table()

DOMAIN = b"misaka-palw/decode-select-v2/gumbel/v1"
Q24 = 1 << 24
I32_MIN, I32_MAX = -(2**31), 2**31 - 1
REPEAT_ONE, REPEAT_MAX = 1 << 16, 4 << 16
PEN_MAX = 2 << 24
BIAS_MAX = 100 << 24
BAN = -BIAS_MAX


# ---- the pipeline, from the RFC's text ---------------------------------------------------------

def repeat(v, c, p):
    if c == 0:
        return v
    return (v * REPEAT_ONE) // p if v > 0 else (v * p) // REPEAT_ONE


def freq_presence(a, c, f, s):
    return a - c * f - (s if c > 0 else 0)


def saturate(d):
    return min(max(d, I32_MIN + 1), I32_MAX)


def window_count(generated, w, lane):
    return sum(1 for x in (generated[len(generated) - w:] if w > 0 else []) if x == lane)


def bias_entry(cfg, lane):
    for tok, q in cfg["logit_bias"]:
        if tok == lane:
            return q
    return 0


def lane_value(cfg, v, lane, c):
    q = bias_entry(cfg, lane)
    if q == BAN:
        return None
    a = repeat(v, c, cfg["repeat_penalty_q"])
    b = freq_presence(a, c, cfg["frequency_penalty_q"], cfg["presence_penalty_q"])
    return saturate(b + q)


def gumbel(seed, t, lane):
    h = hashlib.blake2b(digest_size=64, key=DOMAIN)
    h.update(seed)
    h.update(t.to_bytes(4, "little"))
    h.update(lane.to_bytes(8, "little"))
    d = h.digest()
    return GUMBEL[int.from_bytes(d[:2], "big") >> 3]


def key(v2, seed, t, lane, temp):
    # RFC-0001 §A.3 step 6 / ADR-0082 D11, as written: v'' is a Q24 logit, so v'' * 2**24 is Q48; T (Q24) times
    # the Gumbel variate (Q24) is Q48 too, and the two are added WHOLE. (An earlier revision of this file, and
    # of the Rust key it mirrored, shifted the noise right by 24 — Q24 beside Q48 — which made the temperature
    # inert: finding G1 of the independent second implementation. At T = 1.0 the key now samples softmax(v'').)
    base = v2 * Q24
    return base if temp == 0 else base + temp * gumbel(seed, t, lane)


def select_v4(cfg, seed, temp, generated, row, admitted=None):
    t = len(generated)
    best = None
    for lane, v in enumerate(row):
        c = window_count(generated, cfg["penalty_window"], lane)
        v2 = lane_value(cfg, v, lane, c)
        if v2 is None or (admitted is not None and lane not in admitted):
            continue
        k = key(v2, seed, t, lane, temp)
        if best is None or k > best[1]:
            best = (lane, k)
    return None if best is None else best[0]


def select_v3(seed, temp, t, row):
    best = None
    for lane, v in enumerate(row):
        k = key(v, seed, t, lane, temp)
        if best is None or k > best[1]:
            best = (lane, k)
    return 0 if best is None else best[0]


def stop_match(stops, generated):
    for i, s in enumerate(stops):
        if s and len(generated) >= len(s) and generated[len(generated) - len(s):] == s:
            return i
    return None


def first_stop(stops, answer):
    for end in range(1, len(answer) + 1):
        m = stop_match(stops, answer[:end])
        if m is not None:
            return [end, m]
    return None


NOOP = {"repeat_penalty_q": REPEAT_ONE, "penalty_window": 0, "frequency_penalty_q": 0, "presence_penalty_q": 0,
        "logit_bias": [], "stop_sequences": []}


def cfg(**kw):
    c = dict(NOOP)
    c.update(kw)
    return c


def canonical_error(c):
    """§A.2's refusals, in the Rust validator's order, by the Rust variant's name."""
    if not (REPEAT_ONE <= c["repeat_penalty_q"] <= REPEAT_MAX):
        return "RepeatPenaltyOutOfRange"
    if not (-PEN_MAX <= c["frequency_penalty_q"] <= PEN_MAX):
        return "FrequencyPenaltyOutOfRange"
    if not (-PEN_MAX <= c["presence_penalty_q"] <= PEN_MAX):
        return "PresencePenaltyOutOfRange"
    active = c["repeat_penalty_q"] != REPEAT_ONE or c["frequency_penalty_q"] != 0 or c["presence_penalty_q"] != 0
    if active and not (1 <= c["penalty_window"] <= 256):
        return "PenaltyWindowOutOfRange"
    if not active and c["penalty_window"] != 0:
        return "PenaltyWindowWithoutPenalty"
    if len(c["logit_bias"]) > 300:
        return "TooManyBiasEntries"
    prev = None
    for tok, q in c["logit_bias"]:
        if prev is not None and tok <= prev:
            return "BiasNotAscending"
        if not (-BIAS_MAX <= q <= BIAS_MAX):
            return "BiasOutOfRange"
        if q == 0:
            return "ZeroBias"
        prev = tok
    if len(c["stop_sequences"]) > 4:
        return "TooManyStopSequences"
    for i, s in enumerate(c["stop_sequences"]):
        if not s:
            return "EmptyStopSequence"
        if len(s) > 16:
            return "StopSequenceTooLong"
        if i > 0 and c["stop_sequences"][i - 1] >= s:
            return "StopSequencesNotAscending"
    return None


# ---- deterministic inputs -----------------------------------------------------------------------

class Xs:
    def __init__(self, seed):
        self.x = (seed | 1) & (2**64 - 1)

    def next(self):
        x = self.x
        x ^= (x << 13) & (2**64 - 1)
        x ^= x >> 7
        x ^= (x << 17) & (2**64 - 1)
        self.x = x
        return x

    def spread(self, s):
        return (self.next() % (2 * s + 1)) - s

    def row(self, width, s):
        return [self.spread(s) for _ in range(width)]


SEED_HOT = bytes([7] * 32)
SEED_B = bytes(range(32))


def sampling_pairs():
    return [(bytes(32), 0), (SEED_HOT, Q24), (SEED_B, Q24 // 2), (SEED_B, 3 * Q24)]


# ---- the files ----------------------------------------------------------------------------------

def repeat_vectors():
    cases = []
    values = [I32_MIN, -(3 * Q24) - 5, -7, -1, 0, 1, 7, 10 * Q24 + 3, I32_MAX]
    for p in [REPEAT_ONE, REPEAT_ONE + 1, 81920, 98304, 131072, REPEAT_MAX]:
        for v in values:
            for c in [0, 1, 5]:
                cases.append({"value": v, "count": c, "repeat_penalty_q": p, "expected": repeat(v, c, p)})
    return {"spec": "RFC-0001 §A.3 step 1 (repeat)", "cases": cases}


def frequency_vectors():
    cases = []
    for a in [I32_MIN * 4, -(5 * Q24), -1, 0, 1, 5 * Q24, I32_MAX]:
        for c in [0, 1, 3, 256]:
            for f in [-PEN_MAX, -Q24, 0, Q24 // 2, PEN_MAX]:
                cases.append({"repeated": a, "count": c, "frequency_penalty_q": f, "expected": freq_presence(a, c, f, 0)})
    return {"spec": "RFC-0001 §A.3 step 2 (frequency, presence 0)", "cases": cases}


def presence_vectors():
    cases = []
    for a in [I32_MIN * 4, -(5 * Q24), 0, 5 * Q24, I32_MAX]:
        for c in [0, 1, 3, 256]:
            for s in [-PEN_MAX, -Q24, 0, Q24 // 2, PEN_MAX]:
                cases.append({"repeated": a, "count": c, "presence_penalty_q": s, "expected": freq_presence(a, c, 0, s)})
    return {"spec": "RFC-0001 §A.3 step 2 (presence, frequency 0)", "cases": cases}


def logit_bias_vectors():
    canonical = []
    for lb in [[], [[1, 5], [2, -5], [900, BAN], [901, BIAS_MAX]], [[2, 5], [2, 6]], [[3, 5], [2, 6]], [[3, 0]],
               [[3, BIAS_MAX + 1]], [[3, BAN - 1]], [[t, 1] for t in range(300)], [[t, 1] for t in range(301)]]:
        c = cfg(logit_bias=lb)
        canonical.append({"logit_bias": lb, "error": canonical_error(c)})
    lanes = []
    c = cfg(logit_bias=[[0, BAN], [3, 5 * Q24], [4, BIAS_MAX], [9, -(7 * Q24)], [12, -1]])
    for lane in range(14):
        for v in [I32_MIN, -Q24, 0, 2 * Q24, I32_MAX]:
            lanes.append({"logit_bias": c["logit_bias"], "lane": lane, "value": v, "expected": lane_value(c, v, lane, 0)})
    return {"spec": "RFC-0001 §A.2 (logit_bias form) and §A.3 steps 3-5 (bias, saturation, bans)",
            "canonical": canonical, "lanes": lanes}


def stop_vectors():
    canonical = []
    for ss in [[], [[1], [1, 2], [2], [3, 0, 0]], [[]], [list(range(17))], [list(range(16))], [[2], [1]], [[2], [2]],
               [[1], [2], [3], [4], [5]]]:
        canonical.append({"stop_sequences": ss, "error": canonical_error(cfg(stop_sequences=ss))})
    matches = []
    for ss, gen in [([[5, 6], [9]], [1, 5, 6]), ([[5, 6], [9]], [1, 5, 6, 7]), ([[5, 6], [9]], [9]), ([[5, 6], [9]], [6]),
                    ([[5, 6], [9]], []), ([[1, 2], [2]], [1, 2]), ([[1, 2], [2]], [3, 2]), ([list(range(16))], list(range(16))),
                    ([list(range(16))], [0] + list(range(16)))]:
        matches.append({"stop_sequences": ss, "generated": gen, "expected": stop_match(ss, gen)})
    first = []
    for ss, ans in [([[5, 6], [9]], [1, 2, 5, 6, 9]), ([[5, 6], [9]], [1, 2, 3]), ([], [1, 2, 3]), ([[2, 2]], [2, 2, 2])]:
        first.append({"stop_sequences": ss, "answer": ans, "expected": first_stop(ss, ans)})
    return {"spec": "RFC-0001 §A.2 (stop form) and §A.3 step 7", "canonical": canonical, "matches": matches, "first_stop": first}


def processor_configs():
    return [
        ("noop", NOOP),
        ("repeat-1.5-w6", cfg(repeat_penalty_q=98304, penalty_window=6)),
        ("freq-presence-w16", cfg(frequency_penalty_q=Q24 // 2, presence_penalty_q=-(Q24 // 4), penalty_window=16)),
        ("bias-and-bans", cfg(logit_bias=[[0, BAN], [3, 5 * Q24], [17, -(7 * Q24)], [21, BAN]])),
        ("everything-at-the-edge", cfg(repeat_penalty_q=REPEAT_MAX, penalty_window=256, frequency_penalty_q=PEN_MAX,
                                       presence_penalty_q=PEN_MAX, logit_bias=[[1, BIAS_MAX], [2, BAN]], stop_sequences=[[4, 4]])),
        ("order-probe", cfg(repeat_penalty_q=131072, penalty_window=4, frequency_penalty_q=Q24, presence_penalty_q=Q24 // 2,
                            logit_bias=[[1, 3 * Q24]])),
    ]


def processor_vectors():
    cases = []
    xs = Xs(0xF00D)
    for name, c in processor_configs():
        assert canonical_error(c) is None, name
        for i in range(6):
            width = 24
            row = xs.row(width, 1 << 26)
            if i == 5:
                row[1] = I32_MAX
                row[2] = I32_MIN
            gen_len = xs.next() % 40
            generated = [xs.next() % width for _ in range(gen_len)]
            for seed, temp in sampling_pairs():
                processed = [lane_value(c, v, lane, window_count(generated, c["penalty_window"], lane))
                             for lane, v in enumerate(row)]
                cases.append({"name": f"{name}/{i}", "config": c, "seed": seed.hex(), "temperature_q": temp,
                              "generated_before": generated, "row": row, "admitted": None, "processed": processed,
                              "expected_lane": select_v4(c, seed, temp, generated, row)})
    # The constraint's mask composes with the bans, and an empty admitted set selects nothing.
    c = cfg(logit_bias=[[2, BAN]])
    for admitted, row in [(None, [1, 5, 9, 7]), ([0, 1, 2], [1, 5, 9, 7]), ([2], [1, 5, 9, 7])]:
        cases.append({"name": "mask", "config": c, "seed": bytes(32).hex(), "temperature_q": 0, "generated_before": [],
                      "row": row, "admitted": admitted, "processed": [lane_value(c, v, lane, 0) for lane, v in enumerate(row)],
                      "expected_lane": select_v4(c, bytes(32), 0, [], row, None if admitted is None else set(admitted))})
    runs = []
    for name, c, limit, lanes in [
        ("stop-at-2-3", cfg(stop_sequences=[[2, 3]]), 8, [1, 2, 3, 0, 1]),
        ("budget", cfg(stop_sequences=[[2, 3]]), 3, [1, 1, 1]),
        ("stop-on-the-last-budget-token", cfg(stop_sequences=[[3]]), 2, [1, 3]),
        ("all-banned", cfg(logit_bias=[[t, BAN] for t in range(4)]), 8, [1]),
        ("repeat-walks-off", cfg(repeat_penalty_q=REPEAT_MAX, penalty_window=2), 5, None),
    ]:
        rows = []
        for step in range(len(lanes) if lanes else limit):
            if lanes:
                r = [0, 0, 0, 0]
                r[lanes[step]] = 10 * Q24
            else:
                r = [10 * Q24, 9 * Q24, 8 * Q24, 1 * Q24]
            rows.append(r)
        generated, stop, fed = [], None, []
        for r in rows:
            t = len(generated)
            raw = select_v3(bytes(32), 0, t, r)
            if stop is not None:
                fed.append(raw)
                continue
            lane = select_v4(c, bytes(32), 0, generated, r)
            if lane is None:
                stop = {"executed": t, "reason": "NoAdmissibleLane"}
                fed.append(raw)
                continue
            generated.append(lane)
            fed.append(lane)
            m = stop_match(c["stop_sequences"], generated)
            if m is not None:
                stop = {"executed": len(generated), "reason": f"StopSequence:{m}"}
            elif len(generated) >= limit:
                stop = {"executed": len(generated), "reason": "Budget"}
        runs.append({"name": name, "config": c, "limit": limit, "rows": rows, "fed": fed, "generated": generated, "stop": stop})
    return {"spec": "RFC-0001 §A.3 steps 1-7 in their total order (greedy and sampled)", "cases": cases, "decoder_runs": runs}


def noop_vectors():
    cases = []
    xs = Xs(0x5EED)
    for i in range(64):
        width = 8 + (i % 5) * 29
        row = xs.row(width, 1 << (18 + i % 10))
        generated = [xs.next() % width for _ in range(xs.next() % 50)]
        for seed, temp in sampling_pairs():
            v3 = select_v3(seed, temp, len(generated), row)
            v4 = select_v4(NOOP, seed, temp, generated, row)
            assert v3 == v4, (i, seed, temp)
            cases.append({"seed": seed.hex(), "temperature_q": temp, "generated_before": generated, "row": row,
                          "expected_lane": v3})
    return {"spec": "RFC-0001 §A.4 G7: the no-op V4 selects what the V3 rule selects", "cases": cases}


FILES = {
    "repeat_penalty.json": repeat_vectors,
    "frequency_penalty.json": frequency_vectors,
    "presence_penalty.json": presence_vectors,
    "logit_bias.json": logit_bias_vectors,
    "stop_sequences.json": stop_vectors,
    "processor_order.json": processor_vectors,
    "v4_noop_equals_v3.json": noop_vectors,
}


def render(obj):
    return json.dumps(obj, separators=(",", ":"), sort_keys=True) + "\n"


def greedy_lane(values, admitted=None):
    """The argmax of the values (None = a banned lane), ties to the lowest index, over the admitted lanes."""
    best = None
    for lane, v in enumerate(values):
        if v is None or (admitted is not None and lane not in admitted):
            continue
        if best is None or v > best[1]:
            best = (lane, v)
    return None if best is None else best[0]


def sampling_stats(obj):
    """(sampled cases, sampled cases whose expected lane is NOT the greedy lane). Finding G2: a vector set in
    which every expected lane is the greedy one passes any key, including an inert temperature."""
    sampled = non_greedy = 0
    for c in obj.get("cases", []):
        if c.get("temperature_q", 0) == 0 or c.get("expected_lane") is None:
            continue
        values = c["processed"] if "processed" in c else c["row"]
        admitted = None if c.get("admitted") is None else set(c["admitted"])
        sampled += 1
        non_greedy += c["expected_lane"] != greedy_lane(values, admitted)
    return sampled, non_greedy


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    bad = 0
    for name, make in FILES.items():
        obj = make()
        if name in ("processor_order.json", "v4_noop_equals_v3.json"):
            sampled, non_greedy = sampling_stats(obj)
            print(f"  {name}: {sampled} sampled selections, {non_greedy} of them not the greedy lane")
            # G1/G2: the temperature must decide something, or these vectors cannot tell a working sampler
            # from an inert one. At T = 0.5, 1.0 and 3.0 on rows a few units wide a good share must differ.
            assert non_greedy * 5 >= sampled, f"{name}: the temperature is inert in the vectors ({non_greedy}/{sampled})"
        body = render(obj)
        path = os.path.join(OUT, name)
        if args.check:
            if not os.path.exists(path) or open(path).read() != body:
                print(f"DIFFERS: {name}")
                bad += 1
        else:
            with open(path, "w") as f:
                f.write(body)
            print(f"wrote {name} ({len(body)} bytes)")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
