//! **The reduced SD3 fixture, lowered end to end** — the one place the tiny pipeline is built from its checkpoint
//! directory, shared by the lowerer's fidelity test (`tests/diffusers_sd3.rs`) and the SDK's class and court tests.
//!
//! Given `tests/fixtures/hf-diff/sd3_tiny/` (generated by `tools/gen_diffusers_sd3_fixture.py`), it loads the float
//! references, lowers the two CLIP text stages through the HF frontend, calibrates the denoiser and the decoder on a
//! float Euler loop over a calibration set (the integer text stages' outputs as the denoiser's inputs), and lowers the
//! denoise stage, the VAE chain and the pipeline. Non-consensus tooling: nothing here is on a validation path.

use std::path::Path;

use misaka_palw_tir::interp_v2::{InterpreterV2, MapInputs};

use super::calib::Calib;
use super::dit::{DitStage, DitStageSpec, lower_dit_stage};
use super::float::{Dit, DitInputs, Sd3Config};
use super::pipeline::{Sd3Pipeline, TextStagesV1, assemble_sd3_pipeline};
use super::sampler::SamplerTables;
use super::text::{ClipStage, lower_clip_stage};
use super::vae::{VaeChain, lower_vae};
use super::vae_float::{Fm, Vae, VaeConfig};
use crate::encoder::EncoderOutput;
use crate::weights::Checkpoint;

pub const BOS: u32 = 62;
pub const EOS: u32 = 63;
pub const PAD: u32 = 63;
/// The class's padded template length `L` (the denoiser's text rows).
pub const L: usize = 8;
pub const COUNTS: [u32; 2] = [2, 4];
pub const Q_LAT: u32 = 20;

pub fn fixture_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/hf-diff/sd3_tiny")
}

/// The generated fixture's directory, or `None` (with a line saying so) when it has not been generated.
pub fn fixture() -> Option<std::path::PathBuf> {
    let d = fixture_dir();
    if d.join("transformer/config.json").exists() && d.join("text/model.safetensors").exists() && d.join("vae/config.json").exists() {
        Some(d)
    } else {
        eprintln!("skipped: {} holds no generated fixture (run tools/gen_diffusers_sd3_fixture.py)", d.display());
        None
    }
}

pub fn json(p: &Path) -> serde_json::Value {
    serde_json::from_slice(&std::fs::read(p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))).expect("json")
}

/// `bos ‖ prompt ‖ eos ‖ pad…` to `L`.
pub fn padded(prompt: &[u32]) -> Vec<u32> {
    let mut t = vec![BOS];
    t.extend_from_slice(prompt);
    t.push(EOS);
    while t.len() < L {
        t.push(PAD);
    }
    t
}

/// A seeded stand-in for `R`'s `Normal` draw over the init-noise domain: Q24 Gaussian words in `PALW_GAUSS_Q24_V1`'s
/// range (Box–Muller over a 64-bit LCG). Used where no consensus `R` is at hand; every run compared is fed the same words.
pub fn noise_words(seed: u64, n: usize) -> Vec<i128> {
    let mut s = seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1;
    let mut next = || {
        s = s.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
        ((s >> 11) as f64 + 0.5) / (1u64 << 53) as f64
    };
    (0..n)
        .map(|_| {
            let g = (-2.0 * next().ln()).sqrt() * (2.0 * std::f64::consts::PI * next()).cos();
            ((g * (1u64 << 24) as f64).round() as i128).clamp(-72_560_101, 72_560_101)
        })
        .collect()
}

/// The text stages' float outputs for a prompt: rows `[L, d]` and the pooled vector.
pub fn text_floats(rows: &ClipStage, pool: &ClipStage, prompt: &[u32]) -> (Vec<f64>, Vec<f64>) {
    let run = |st: &ClipStage, toks: &[u32]| {
        let interp = InterpreterV2::new(&st.program).expect("the text program validates");
        interp.run(&st.params, &MapInputs::default(), toks).expect("the text program runs")
    };
    let r = run(rows, &padded(prompt));
    let rows_f: Vec<f64> = r.iter().flat_map(|s| s.output.data.iter().map(|v| *v as f64 * rows.unit)).collect();
    let mut unpadded = vec![BOS];
    unpadded.extend_from_slice(prompt);
    unpadded.push(EOS);
    let p = run(pool, &unpadded);
    let pooled_f: Vec<f64> = p.last().unwrap().output.data.iter().map(|v| *v as f64 * pool.unit).collect();
    (rows_f, pooled_f)
}

/// The float Euler loop over the Rust denoiser: the latent after each step, and the velocity.
pub fn float_loop(
    dit: &Dit,
    tables: &SamplerTables,
    si: usize,
    noise: &[f64],
    rows: &[f64],
    pooled: &[f64],
    cal: &mut Calib,
) -> (Vec<Vec<f64>>, Vec<Vec<f64>>) {
    let mut lat = noise.to_vec();
    let (mut lats, mut vels) = (Vec::new(), Vec::new());
    for i in 0..tables.timesteps[si].len() {
        let v = dit.forward(&DitInputs { latent: &lat, timestep: tables.timesteps[si][i], text: rows, n_txt: L, pooled }, cal);
        let ds = tables.sigmas[si][i + 1] - tables.sigmas[si][i];
        for (x, vv) in lat.iter_mut().zip(&v) {
            *x += ds * vv;
        }
        lats.push(lat.clone());
        vels.push(v);
    }
    (lats, vels)
}

/// Everything the tests need of the lowered fixture.
pub struct Sd3Fixture {
    pub dir: std::path::PathBuf,
    pub cfg: Sd3Config,
    pub vcfg: VaeConfig,
    pub dit: Dit,
    pub vae: Vae,
    pub tables: SamplerTables,
    pub stage: DitStage,
    pub chain: VaeChain,
    pub spec: DitStageSpec,
    pub pipeline: Sd3Pipeline,
    /// The integer text stages' programs/params are inside `pipeline`; their units:
    pub rows_unit: f64,
    pub pooled_unit: f64,
}

/// Lower the fixture end to end.
pub fn build_sd3_tiny(dir: &Path) -> Result<Sd3Fixture, String> {
    let cfg = Sd3Config::from_json(&json(&dir.join("transformer/config.json")))?;
    let vcfg = VaeConfig::from_json(&json(&dir.join("vae/config.json")))?;
    let dit = Dit::load(
        cfg.clone(),
        &Checkpoint::open(&dir.join("transformer/diffusion_pytorch_model.safetensors")).map_err(|e| e.to_string())?,
    )?;
    let vae =
        Vae::load(vcfg.clone(), &Checkpoint::open(&dir.join("vae/diffusion_pytorch_model.safetensors")).map_err(|e| e.to_string())?)?;
    let sch = json(&dir.join("scheduler/scheduler_config.json"));
    let (shift, n_train) =
        (sch["shift"].as_f64().ok_or("scheduler shift")?, sch["num_train_timesteps"].as_f64().ok_or("num_train_timesteps")?);
    let tables = SamplerTables::new(&COUNTS, shift, n_train);
    let (c, side) = (cfg.in_channels, cfg.sample_size);
    let len = c * side * side;

    // The text stages (integer), calibrated on templated random prompts.
    let calib_prompts: Vec<Vec<u32>> = vec![vec![3, 4], vec![30, 31, 32], vec![17], vec![40, 8, 9, 10], vec![50, 51]];
    let calib_seqs: Vec<Vec<usize>> = calib_prompts.iter().map(|p| padded(p).iter().map(|t| *t as usize).collect()).collect();
    let pool_seqs: Vec<Vec<usize>> = calib_prompts
        .iter()
        .map(|p| {
            let mut t = vec![BOS as usize];
            t.extend(p.iter().map(|x| *x as usize));
            t.push(EOS as usize);
            t
        })
        .collect();
    let rows_stage = lower_clip_stage(&dir.join("text"), false, EncoderOutput::Rows, &calib_seqs)?;
    let pool_stage = lower_clip_stage(&dir.join("text"), true, EncoderOutput::Final, &pool_seqs)?;

    // Calibration: the float Euler loop on the calibration set, the integer text outputs as the inputs.
    let (mut cal, mut vcal) = (Calib::new(), Calib::new());
    for (k, p) in calib_prompts.iter().enumerate() {
        let (rows, pooled) = text_floats(&rows_stage, &pool_stage, p);
        for (si, steps) in COUNTS.iter().enumerate() {
            let noise: Vec<f64> =
                noise_words(100 + k as u64 * 7 + *steps as u64, len).iter().map(|w| *w as f64 / (1u64 << 24) as f64).collect();
            let (lats, _) = float_loop(&dit, &tables, si, &noise, &rows, &pooled, &mut cal);
            vae.decode(&Fm { c, h: side, w: side, d: lats.last().unwrap().clone() }, &mut vcal);
        }
    }
    cal.unify(&["cond", "te_out", "pe_out"]);

    let (rows_unit, pooled_unit) = (rows_stage.unit, pool_stage.unit);
    let spec = DitStageSpec { n_txt: L, q_lat: Q_LAT, counts: COUNTS.to_vec(), shift, n_train, text_unit: rows_unit, pooled_unit };
    let stage = lower_dit_stage(&dit, &cal, &spec)?;
    let chain = lower_vae(&vae, &vcal, side, stage.scales.latent)?;
    let pipeline = assemble_sd3_pipeline(
        TextStagesV1 {
            rows: (rows_stage.program, rows_stage.params),
            pool: (pool_stage.program, pool_stage.params),
            bos: BOS,
            eos: EOS,
            pad: PAD,
            to_len: L as u32,
        },
        &stage,
        &chain,
    )?;
    Ok(Sd3Fixture { dir: dir.to_path_buf(), cfg, vcfg, dit, vae, tables, stage, chain, spec, pipeline, rows_unit, pooled_unit })
}
