//! `PALW-BASE-0` — the artifacts and the engine (ADR-0039, ADR-0040).
//!
//! ADR-0039 made BASE-0 the class that replaces the hash floor in PALW-only block production, on
//! the grounds that it is the only class whose kernel catalog can *close*. `consensus-core` holds
//! the closed catalog: `palw_base0` (six primitives) and `palw_base0_ops` (the ops). This crate
//! holds the other half — the **artifacts** those ops are applied to, and the engine that applies
//! them.
//!
//! The split is deliberate. Nothing here is on the block-validation path: consensus reads a class
//! by its 64-byte [`artifact::Base0ArtifactV1::artifact_digest`] and never re-derives an
//! artifact. Deleting this crate after a class were registered would leave every existing block
//! valid.
//!
//! # What is here
//!
//! * [`rope`] — the pinned integer rotary table, generated by CORDIC with no float anywhere, so
//!   the artifact is reproducible **by derivation** rather than only by distribution.
//! * [`artifact`] — shape, weights, quantisation, and the digest that pins all three into a class
//!   id.
//! * [`engine`] — the decoder-only forward pass, written strictly through the closed catalog.
//!
//! # What is not here
//!
//! Trained weights. This crate defines the container and checks its shape;
//! [`artifact::Base0ArtifactV1::derive_deterministic`] fills it from a seed so the engine and the
//! digest have something concrete to run on, and such an artifact reports
//! [`artifact::Base0ArtifactV1::is_derived`] so it can never be logged as a registered class.
//! Quantising a real trained model into these shapes is a separate data pipeline.
//!
//! # The catalog gap this crate found
//!
//! Writing the engine is what surfaced a structural defect in the frozen catalog: `Requantize` is
//! `Saturate8(RoundingShiftRight(SRDHM(acc, mult), shift))`, and because `SRDHM` contains a `>> 31`
//! its gain can never exceed 1. But `SoftMax` and `Silu` are defined on Qk inputs and the
//! accumulators feeding them are two to three orders of magnitude below Qk, so **attention came
//! out flat and SwiGLU's gate came out linear**. The repair is `palw_base0::rescale_q` — one
//! `i64` multiply and one rounding shift, with the `>> 31` no longer baked in — recorded as
//! ADR-0040 Decision H. It is the reason the op count is ten rather than nine.

pub mod artifact;
pub mod backend;
pub mod classes;
pub mod engine;
pub mod engine_a16;
pub mod gguf;
pub mod inventory;
pub mod legs;
pub mod mmap;
pub mod produce;
pub mod qwen36;
pub mod qwen36_backend;
pub mod qwen36_calibrate;
pub mod qwen36_reference;
pub mod rc;
pub mod rope;
pub mod tokenizer;

pub mod convert;
pub mod reference;
pub mod kat;
pub mod kernels;
pub mod optimized;
pub use artifact::{ArtifactError, Base0ArtifactV1, Base0LayerWeightsV1, Base0ShapeV1, LN_THETA_10000_GEN_Q};
pub use engine::{Base0Engine, EngineError, KvCache};
pub use rope::{RopeGenError, RopeTableV1};
