//! `kaspa-pq-cli` — minimal CLI for the kaspa-pq fork (Phase 5').
//!
//! What this binary does (and does **not**):
//!
//! - **Does** generate / re-derive an ML-DSA-65 keypair from a BIP39
//!   mnemonic, derive the corresponding kaspa-pq P2PKH address (per
//!   docs/kaspa-pq-spec.md §5 and §8), and sign / verify arbitrary
//!   messages with the kaspa-pq transaction context
//!   `MLDSA65_TX_CONTEXT`.
//! - **Does not** speak to a kaspa-pq node over RPC. UTXO selection,
//!   fee estimation, transaction template assembly, and `submit-tx`
//!   all require a running node + a wRPC/gRPC client; those land in a
//!   follow-up that wires this binary against `kaspa-wrpc-client`.
//!
//! Storage is a plain-text mnemonic file (one line, space-separated
//! words). This is **only acceptable for simnet / devnet PoC**; a
//! mainnet wallet must encrypt the seed at rest. The `--mnemonic-file`
//! flag points at this storage.
//!
//! Subcommands:
//!
//!   init       Generate a new BIP39 mnemonic, save it.
//!   address    Print the kaspa-pq P2PKH address at a given path.
//!   sign       Sign a hex-encoded message with the mnemonic/path.
//!   verify     Verify (pubkey_hex, message_hex, signature_hex) under
//!              `MLDSA65_TX_CONTEXT`. Network-independent.

use std::{fs, path::PathBuf};

use clap::{Parser, Subcommand, ValueEnum};
use kaspa_addresses::Prefix;
use kaspa_bip32::{Language, Mnemonic, WordCount};
use kaspa_txscript::{MLDSA65_PK_LEN, MLDSA65_SIG_LEN, MLDSA65_TX_CONTEXT};
use kaspa_wallet_keys::kaspa_pq;
use libcrux_ml_dsa::ml_dsa_65;
use thiserror::Error;

#[derive(Debug, Error)]
enum CliError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("bip32: {0}")]
    Bip32(#[from] kaspa_bip32::Error),
    #[error("hex decode: {0}: {1}")]
    Hex(String, String),
    #[error("ml-dsa-65 signature failed to verify under the kaspa-pq tx context")]
    SignatureInvalid,
    #[error("public key length mismatch: expected {expected} bytes, got {got}")]
    PublicKeyLength { expected: usize, got: usize },
    #[error("signature length mismatch: expected {expected} bytes, got {got}")]
    SignatureLength { expected: usize, got: usize },
    #[error("randomness must be 32 bytes")]
    BadRandomness,
}

#[derive(Parser, Debug)]
#[command(name = "kaspa-pq-cli", about, long_about = None, version)]
struct Cli {
    /// Path to the BIP39 mnemonic file (one line, space-separated words).
    /// `init` writes here; `address` / `sign` read here.
    #[arg(long, default_value = "kaspa-pq-mnemonic.txt", global = true)]
    mnemonic_file: PathBuf,

    /// BIP39 mnemonic passphrase. Empty by default.
    #[arg(long, default_value = "", global = true)]
    passphrase: String,

    /// kaspa-pq network the address belongs to. Affects the address
    /// prefix and the kaspa-pq keygen-seed domain separation
    /// (see docs/kaspa-pq-spec.md §8).
    #[arg(long, value_enum, default_value_t = NetworkFlag::Mainnet, global = true)]
    network: NetworkFlag,

    #[command(subcommand)]
    cmd: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Generate a fresh BIP39 mnemonic and save it to `--mnemonic-file`.
    /// Refuses to overwrite an existing file.
    Init {
        /// Number of mnemonic words. 24 is the kaspa-pq-recommended
        /// value (256-bit entropy). Smaller word counts are available
        /// for testing.
        #[arg(long, value_enum, default_value_t = WordCountFlag::W24)]
        words: WordCountFlag,
    },
    /// Print the kaspa-pq P2PKH address at the given derivation path.
    Address {
        #[arg(long, default_value_t = 0)]
        account: u32,
        #[arg(long, default_value_t = 0)]
        change: u32,
        #[arg(long, default_value_t = 0)]
        index: u32,
    },
    /// Sign a hex-encoded message with the keypair at the given
    /// derivation path. Prints the public key + signature in hex.
    Sign {
        /// Message bytes in hex. For a kaspa-pq transaction input this
        /// is the 32-byte sighash digest produced by
        /// `kaspa_consensus_core::hashing::sighash::calc_schnorr_signature_hash`.
        #[arg(long)]
        message_hex: String,
        #[arg(long, default_value_t = 0)]
        account: u32,
        #[arg(long, default_value_t = 0)]
        change: u32,
        #[arg(long, default_value_t = 0)]
        index: u32,
        /// 32-byte randomness in hex. Generated by the OS if omitted.
        #[arg(long)]
        randomness_hex: Option<String>,
    },
    /// Verify (pubkey, message, signature) under `MLDSA65_TX_CONTEXT`.
    /// Does not read the mnemonic file — self-contained.
    Verify {
        /// 1952-byte ML-DSA-65 public key in hex.
        #[arg(long)]
        public_key_hex: String,
        /// Message bytes in hex.
        #[arg(long)]
        message_hex: String,
        /// 3309-byte signature in hex.
        #[arg(long)]
        signature_hex: String,
    },
}

#[derive(Copy, Clone, Debug, ValueEnum)]
enum NetworkFlag {
    Mainnet,
    Testnet10,
    Simnet,
    Devnet,
}

impl NetworkFlag {
    fn id(self) -> &'static str {
        match self {
            NetworkFlag::Mainnet => "mainnet",
            NetworkFlag::Testnet10 => "testnet-10",
            NetworkFlag::Simnet => "simnet",
            NetworkFlag::Devnet => "devnet",
        }
    }
    fn prefix(self) -> Prefix {
        match self {
            NetworkFlag::Mainnet => Prefix::Mainnet,
            NetworkFlag::Testnet10 => Prefix::Testnet,
            NetworkFlag::Simnet => Prefix::Simnet,
            NetworkFlag::Devnet => Prefix::Devnet,
        }
    }
}

#[derive(Copy, Clone, Debug, ValueEnum)]
enum WordCountFlag {
    /// 128-bit entropy mnemonic (testing only).
    W12,
    /// 256-bit entropy mnemonic (kaspa-pq recommended).
    W24,
}

impl WordCountFlag {
    fn into_bip39(self) -> WordCount {
        match self {
            WordCountFlag::W12 => WordCount::Words12,
            WordCountFlag::W24 => WordCount::Words24,
        }
    }
}

fn decode_hex(label: &str, s: &str) -> Result<Vec<u8>, CliError> {
    if s.len() % 2 != 0 {
        return Err(CliError::Hex(label.into(), "odd hex length".into()));
    }
    let mut out = vec![0u8; s.len() / 2];
    faster_hex::hex_decode(s.as_bytes(), &mut out).map_err(|e| CliError::Hex(label.into(), e.to_string()))?;
    Ok(out)
}

fn hex_encode_string(bytes: &[u8]) -> String {
    let mut out = vec![0u8; bytes.len() * 2];
    faster_hex::hex_encode(bytes, &mut out).expect("hex encode");
    String::from_utf8(out).expect("hex output is always ASCII")
}

fn read_mnemonic(path: &PathBuf) -> Result<Mnemonic, CliError> {
    let raw = fs::read_to_string(path)?;
    let phrase = raw.trim();
    Ok(Mnemonic::new(phrase, Language::English)?)
}

fn run() -> Result<(), CliError> {
    let cli = Cli::parse();
    match cli.cmd {
        Command::Init { words } => {
            if cli.mnemonic_file.exists() {
                return Err(CliError::Io(std::io::Error::new(
                    std::io::ErrorKind::AlreadyExists,
                    format!("{} already exists; refusing to overwrite", cli.mnemonic_file.display()),
                )));
            }
            let mnemonic = Mnemonic::random(words.into_bip39(), Language::English)?;
            fs::write(&cli.mnemonic_file, format!("{}\n", mnemonic.phrase()))?;
            println!("Wrote mnemonic to {}.", cli.mnemonic_file.display());
            println!("Mnemonic:\n{}", mnemonic.phrase());
            println!();
            println!("Store this mnemonic offline. The plain-text file is a PoC affordance");
            println!("only — a mainnet wallet must encrypt the seed at rest.");
        }
        Command::Address { account, change, index } => {
            let mnemonic = read_mnemonic(&cli.mnemonic_file)?;
            let seed = mnemonic.to_seed(&cli.passphrase);
            let kp = kaspa_pq::derive_keypair(cli.network.id(), account, change, index, seed.as_bytes());
            let addr = kp.address(cli.network.prefix());
            println!("{}", String::from(addr));
        }
        Command::Sign { message_hex, account, change, index, randomness_hex } => {
            let mnemonic = read_mnemonic(&cli.mnemonic_file)?;
            let seed = mnemonic.to_seed(&cli.passphrase);
            let kp = kaspa_pq::derive_keypair(cli.network.id(), account, change, index, seed.as_bytes());
            let message = decode_hex("message_hex", &message_hex)?;
            let randomness: [u8; 32] = match randomness_hex {
                Some(h) => {
                    let bytes = decode_hex("randomness_hex", &h)?;
                    bytes.as_slice().try_into().map_err(|_| CliError::BadRandomness)?
                }
                None => {
                    use rand::RngCore;
                    let mut buf = [0u8; 32];
                    rand::thread_rng().fill_bytes(&mut buf);
                    buf
                }
            };
            let sig = kp.sign(&message, randomness);
            println!("public_key={}", hex_encode_string(kp.public_key_bytes()));
            println!("signature={}", hex_encode_string(&sig));
        }
        Command::Verify { public_key_hex, message_hex, signature_hex } => {
            let pk_bytes = decode_hex("public_key_hex", &public_key_hex)?;
            if pk_bytes.len() != MLDSA65_PK_LEN {
                return Err(CliError::PublicKeyLength { expected: MLDSA65_PK_LEN, got: pk_bytes.len() });
            }
            let sig_bytes = decode_hex("signature_hex", &signature_hex)?;
            if sig_bytes.len() != MLDSA65_SIG_LEN {
                return Err(CliError::SignatureLength { expected: MLDSA65_SIG_LEN, got: sig_bytes.len() });
            }
            let msg = decode_hex("message_hex", &message_hex)?;
            let pk_arr: [u8; MLDSA65_PK_LEN] = pk_bytes.as_slice().try_into().unwrap();
            let sig_arr: [u8; MLDSA65_SIG_LEN] = sig_bytes.as_slice().try_into().unwrap();
            let vk = ml_dsa_65::MLDSA65VerificationKey::new(pk_arr);
            let sig = ml_dsa_65::MLDSA65Signature::new(sig_arr);
            ml_dsa_65::verify(&vk, &msg, MLDSA65_TX_CONTEXT, &sig).map_err(|_| CliError::SignatureInvalid)?;
            println!("OK: signature verifies under the kaspa-pq tx context.");
        }
    }
    Ok(())
}

fn main() {
    if let Err(err) = run() {
        eprintln!("error: {err}");
        std::process::exit(1);
    }
}
